<?php
/*
* Homepage
* 
* @requestMethod GET
* @responseFormat HTML
* @source https://xd.adobe.com/view/7bbdd623-2cdd-4cf4-971f-98d886e7a2b8/screen/8735ce6f-75af-4583-8dca-6b3c775399c6/Software-page?fullscreen
*/
class IndexController extends Controller {
	public function run() {
		
$this->response->setAttribute("country", 'random#6');
$this->response->setAttribute("best_casinos", array (
  0 => 
  array (
    'id' => 4,
    'name' => 'random#7',
    'rating' => 8,
    'is_accepted' => 0,
    'softwares' => 
    array (
      0 => 'random#3',
      1 => 'random#8',
      2 => 'random#5',
      3 => 'random#10',
      4 => 'random#10',
      5 => 'random#9',
      6 => 'random#8',
      7 => 'random#9',
      8 => 'random#7',
      9 => 'random#4',
    ),
    'bonus_first_deposit' => 
    array (
      'amount' => 'random#5',
      'min_deposit' => 'random#6',
      'wagering' => 'random#3',
      'games_allowed' => 
      array (
        0 => 'random#6',
        1 => 'random#8',
        2 => 'random#1',
        3 => 'random#1',
        4 => 'random#5',
        5 => 'random#10',
        6 => 'random#9',
        7 => 'random#8',
        8 => 'random#4',
        9 => 'random#7',
      ),
      'code' => 'random#10',
    ),
    'bonus_free' => 
    array (
      'amount' => 'random#1',
      'min_deposit' => 'random#7',
      'wagering' => 'random#5',
      'games_allowed' => 
      array (
        0 => 'random#4',
        1 => 'random#4',
        2 => 'random#3',
        3 => 'random#5',
        4 => 'random#6',
        5 => 'random#10',
        6 => 'random#9',
        7 => 'random#6',
        8 => 'random#9',
        9 => 'random#8',
      ),
      'code' => 'random#3',
    ),
    'languages' => 
    array (
      0 => 'random#7',
      1 => 'random#5',
      2 => 'random#6',
      3 => 'random#2',
      4 => 'random#10',
      5 => 'random#9',
      6 => 'random#7',
      7 => 'random#8',
      8 => 'random#9',
      9 => 'random#8',
    ),
    'currencies' => 
    array (
      0 => 'random#2',
      1 => 'random#9',
      2 => 'random#7',
      3 => 'random#9',
      4 => 'random#2',
      5 => 'random#3',
      6 => 'random#9',
      7 => 'random#3',
      8 => 'random#9',
      9 => 'random#4',
    ),
    'is_live_dealer' => 1,
    'date_established' => '2018-01-17 15:37:12',
    'emails' => 
    array (
      0 => 'random#2',
      1 => 'random#6',
      2 => 'random#1',
      3 => 'random#8',
      4 => 'random#5',
      5 => 'random#10',
      6 => 'random#4',
      7 => 'random#3',
      8 => 'random#8',
      9 => 'random#7',
    ),
    'phones' => 
    array (
      0 => 'random#10',
      1 => 'random#2',
      2 => 'random#3',
      3 => 'random#1',
      4 => 'random#1',
      5 => 'random#1',
      6 => 'random#8',
      7 => 'random#9',
      8 => 'random#10',
      9 => 'random#6',
    ),
    'is_live_chat' => 1,
    'licenses' => 
    array (
      0 => 'random#8',
      1 => 'random#2',
      2 => 'random#9',
      3 => 'random#10',
      4 => 'random#4',
      5 => 'random#8',
      6 => 'random#2',
      7 => 'random#3',
      8 => 'random#1',
      9 => 'random#8',
    ),
    'certifiers' => 
    array (
      0 => 'random#5',
      1 => 'random#6',
      2 => 'random#8',
      3 => 'random#3',
      4 => 'random#10',
      5 => 'random#8',
      6 => 'random#6',
      7 => 'random#3',
      8 => 'random#5',
      9 => 'random#2',
    ),
    'affiliate_program' => 'random#2',
    'withdrawal_minimum' => 'random#6',
    'withdrawal_limits' => 
    array (
      0 => 'random#4',
      1 => 'random#3',
      2 => 'random#7',
      3 => 'random#5',
      4 => 'random#1',
      5 => 'random#6',
      6 => 'random#5',
      7 => 'random#6',
      8 => 'random#6',
      9 => 'random#2',
    ),
    'withdrawal_timeframes' => 
    array (
      0 => 'random#7',
      1 => 'random#5',
      2 => 'random#1',
      3 => 'random#1',
      4 => 'random#2',
      5 => 'random#3',
      6 => 'random#3',
      7 => 'random#2',
      8 => 'random#10',
      9 => 'random#8',
    ),
    'deposit_methods' => 
    array (
      0 => 'random#8',
      1 => 'random#8',
      2 => 'random#10',
      3 => 'random#7',
      4 => 'random#5',
      5 => 'random#5',
      6 => 'random#10',
      7 => 'random#10',
      8 => 'random#7',
      9 => 'random#2',
    ),
    'withdraw_methods' => 
    array (
      0 => 'random#6',
      1 => 'random#1',
      2 => 'random#5',
      3 => 'random#3',
      4 => 'random#6',
      5 => 'random#5',
      6 => 'random#8',
      7 => 'random#10',
      8 => 'random#1',
      9 => 'random#3',
    ),
  ),
));
$this->response->setAttribute("country_casinos", array (
  0 => 
  array (
    'id' => 2,
    'name' => 'random#8',
    'rating' => 7,
    'is_accepted' => 0,
    'softwares' => 
    array (
      0 => 'random#8',
      1 => 'random#9',
      2 => 'random#5',
      3 => 'random#1',
      4 => 'random#10',
      5 => 'random#4',
      6 => 'random#8',
      7 => 'random#8',
      8 => 'random#2',
      9 => 'random#7',
    ),
    'bonus_first_deposit' => 
    array (
      'amount' => 'random#5',
      'min_deposit' => 'random#7',
      'wagering' => 'random#2',
      'games_allowed' => 
      array (
        0 => 'random#4',
        1 => 'random#6',
        2 => 'random#9',
        3 => 'random#5',
        4 => 'random#1',
        5 => 'random#10',
        6 => 'random#10',
        7 => 'random#4',
        8 => 'random#5',
        9 => 'random#4',
      ),
      'code' => 'random#1',
    ),
    'bonus_free' => 
    array (
      'amount' => 'random#5',
      'min_deposit' => 'random#5',
      'wagering' => 'random#4',
      'games_allowed' => 
      array (
        0 => 'random#6',
        1 => 'random#2',
        2 => 'random#1',
        3 => 'random#8',
        4 => 'random#9',
        5 => 'random#9',
        6 => 'random#2',
        7 => 'random#10',
        8 => 'random#9',
        9 => 'random#6',
      ),
      'code' => 'random#8',
    ),
    'languages' => 
    array (
      0 => 'random#6',
      1 => 'random#7',
      2 => 'random#5',
      3 => 'random#10',
      4 => 'random#3',
      5 => 'random#6',
      6 => 'random#3',
      7 => 'random#9',
      8 => 'random#5',
      9 => 'random#8',
    ),
    'currencies' => 
    array (
      0 => 'random#10',
      1 => 'random#4',
      2 => 'random#7',
      3 => 'random#3',
      4 => 'random#9',
      5 => 'random#1',
      6 => 'random#3',
      7 => 'random#4',
      8 => 'random#5',
      9 => 'random#7',
    ),
    'is_live_dealer' => 1,
    'date_established' => '2018-01-17 15:37:12',
    'emails' => 
    array (
      0 => 'random#6',
      1 => 'random#7',
      2 => 'random#6',
      3 => 'random#5',
      4 => 'random#5',
      5 => 'random#8',
      6 => 'random#5',
      7 => 'random#3',
      8 => 'random#3',
      9 => 'random#2',
    ),
    'phones' => 
    array (
      0 => 'random#9',
      1 => 'random#10',
      2 => 'random#6',
      3 => 'random#8',
      4 => 'random#3',
      5 => 'random#2',
      6 => 'random#1',
      7 => 'random#1',
      8 => 'random#7',
      9 => 'random#9',
    ),
    'is_live_chat' => 0,
    'licenses' => 
    array (
      0 => 'random#1',
      1 => 'random#5',
      2 => 'random#3',
      3 => 'random#9',
      4 => 'random#6',
      5 => 'random#6',
      6 => 'random#2',
      7 => 'random#10',
      8 => 'random#2',
      9 => 'random#1',
    ),
    'certifiers' => 
    array (
      0 => 'random#6',
      1 => 'random#9',
      2 => 'random#7',
      3 => 'random#1',
      4 => 'random#4',
      5 => 'random#4',
      6 => 'random#5',
      7 => 'random#6',
      8 => 'random#7',
      9 => 'random#6',
    ),
    'affiliate_program' => 'random#5',
    'withdrawal_minimum' => 'random#6',
    'withdrawal_limits' => 
    array (
      0 => 'random#2',
      1 => 'random#2',
      2 => 'random#9',
      3 => 'random#3',
      4 => 'random#3',
      5 => 'random#10',
      6 => 'random#9',
      7 => 'random#1',
      8 => 'random#10',
      9 => 'random#9',
    ),
    'withdrawal_timeframes' => 
    array (
      0 => 'random#6',
      1 => 'random#3',
      2 => 'random#8',
      3 => 'random#1',
      4 => 'random#9',
      5 => 'random#10',
      6 => 'random#1',
      7 => 'random#1',
      8 => 'random#10',
      9 => 'random#7',
    ),
    'deposit_methods' => 
    array (
      0 => 'random#9',
      1 => 'random#7',
      2 => 'random#7',
      3 => 'random#2',
      4 => 'random#10',
      5 => 'random#2',
      6 => 'random#8',
      7 => 'random#6',
      8 => 'random#8',
      9 => 'random#2',
    ),
    'withdraw_methods' => 
    array (
      0 => 'random#2',
      1 => 'random#9',
      2 => 'random#4',
      3 => 'random#1',
      4 => 'random#2',
      5 => 'random#6',
      6 => 'random#10',
      7 => 'random#1',
      8 => 'random#6',
      9 => 'random#10',
    ),
  ),
));
$this->response->setAttribute("new_casinos", array (
  0 => 
  array (
    'id' => 10,
    'name' => 'random#1',
    'rating' => 2,
    'is_accepted' => 1,
    'softwares' => 
    array (
      0 => 'random#1',
      1 => 'random#10',
      2 => 'random#7',
      3 => 'random#2',
      4 => 'random#10',
      5 => 'random#7',
      6 => 'random#8',
      7 => 'random#9',
      8 => 'random#3',
      9 => 'random#4',
    ),
    'bonus_first_deposit' => 
    array (
      'amount' => 'random#10',
      'min_deposit' => 'random#3',
      'wagering' => 'random#6',
      'games_allowed' => 
      array (
        0 => 'random#7',
        1 => 'random#9',
        2 => 'random#3',
        3 => 'random#9',
        4 => 'random#1',
        5 => 'random#1',
        6 => 'random#2',
        7 => 'random#1',
        8 => 'random#3',
        9 => 'random#7',
      ),
      'code' => 'random#10',
    ),
    'bonus_free' => 
    array (
      'amount' => 'random#3',
      'min_deposit' => 'random#2',
      'wagering' => 'random#9',
      'games_allowed' => 
      array (
        0 => 'random#3',
        1 => 'random#3',
        2 => 'random#1',
        3 => 'random#10',
        4 => 'random#4',
        5 => 'random#1',
        6 => 'random#7',
        7 => 'random#5',
        8 => 'random#10',
        9 => 'random#4',
      ),
      'code' => 'random#2',
    ),
    'languages' => 
    array (
      0 => 'random#9',
      1 => 'random#7',
      2 => 'random#6',
      3 => 'random#8',
      4 => 'random#9',
      5 => 'random#1',
      6 => 'random#5',
      7 => 'random#7',
      8 => 'random#3',
      9 => 'random#3',
    ),
    'currencies' => 
    array (
      0 => 'random#8',
      1 => 'random#4',
      2 => 'random#4',
      3 => 'random#8',
      4 => 'random#7',
      5 => 'random#10',
      6 => 'random#7',
      7 => 'random#9',
      8 => 'random#2',
      9 => 'random#6',
    ),
    'is_live_dealer' => 0,
    'date_established' => '2018-01-17 15:37:12',
    'emails' => 
    array (
      0 => 'random#4',
      1 => 'random#7',
      2 => 'random#1',
      3 => 'random#7',
      4 => 'random#7',
      5 => 'random#7',
      6 => 'random#2',
      7 => 'random#7',
      8 => 'random#1',
      9 => 'random#3',
    ),
    'phones' => 
    array (
      0 => 'random#5',
      1 => 'random#7',
      2 => 'random#9',
      3 => 'random#2',
      4 => 'random#5',
      5 => 'random#10',
      6 => 'random#7',
      7 => 'random#2',
      8 => 'random#3',
      9 => 'random#9',
    ),
    'is_live_chat' => 1,
    'licenses' => 
    array (
      0 => 'random#6',
      1 => 'random#3',
      2 => 'random#7',
      3 => 'random#2',
      4 => 'random#3',
      5 => 'random#4',
      6 => 'random#1',
      7 => 'random#4',
      8 => 'random#9',
      9 => 'random#2',
    ),
    'certifiers' => 
    array (
      0 => 'random#8',
      1 => 'random#6',
      2 => 'random#3',
      3 => 'random#5',
      4 => 'random#2',
      5 => 'random#9',
      6 => 'random#6',
      7 => 'random#8',
      8 => 'random#9',
      9 => 'random#9',
    ),
    'affiliate_program' => 'random#3',
    'withdrawal_minimum' => 'random#6',
    'withdrawal_limits' => 
    array (
      0 => 'random#7',
      1 => 'random#5',
      2 => 'random#1',
      3 => 'random#6',
      4 => 'random#1',
      5 => 'random#2',
      6 => 'random#8',
      7 => 'random#10',
      8 => 'random#1',
      9 => 'random#4',
    ),
    'withdrawal_timeframes' => 
    array (
      0 => 'random#2',
      1 => 'random#7',
      2 => 'random#6',
      3 => 'random#4',
      4 => 'random#10',
      5 => 'random#7',
      6 => 'random#8',
      7 => 'random#9',
      8 => 'random#8',
      9 => 'random#6',
    ),
    'deposit_methods' => 
    array (
      0 => 'random#4',
      1 => 'random#10',
      2 => 'random#10',
      3 => 'random#6',
      4 => 'random#9',
      5 => 'random#6',
      6 => 'random#4',
      7 => 'random#8',
      8 => 'random#4',
      9 => 'random#6',
    ),
    'withdraw_methods' => 
    array (
      0 => 'random#3',
      1 => 'random#1',
      2 => 'random#10',
      3 => 'random#3',
      4 => 'random#7',
      5 => 'random#1',
      6 => 'random#5',
      7 => 'random#5',
      8 => 'random#10',
      9 => 'random#6',
    ),
  ),
));
$this->response->setAttribute("no_deposit_casinos", array (
  0 => 
  array (
    'id' => 8,
    'name' => 'random#1',
    'rating' => 3,
    'is_accepted' => 0,
    'softwares' => 
    array (
      0 => 'random#5',
      1 => 'random#3',
      2 => 'random#10',
      3 => 'random#3',
      4 => 'random#2',
      5 => 'random#8',
      6 => 'random#8',
      7 => 'random#6',
      8 => 'random#8',
      9 => 'random#7',
    ),
    'bonus_first_deposit' => 
    array (
      'amount' => 'random#1',
      'min_deposit' => 'random#6',
      'wagering' => 'random#2',
      'games_allowed' => 
      array (
        0 => 'random#4',
        1 => 'random#4',
        2 => 'random#6',
        3 => 'random#9',
        4 => 'random#7',
        5 => 'random#6',
        6 => 'random#9',
        7 => 'random#10',
        8 => 'random#2',
        9 => 'random#9',
      ),
      'code' => 'random#5',
    ),
    'bonus_free' => 
    array (
      'amount' => 'random#6',
      'min_deposit' => 'random#9',
      'wagering' => 'random#1',
      'games_allowed' => 
      array (
        0 => 'random#4',
        1 => 'random#10',
        2 => 'random#3',
        3 => 'random#8',
        4 => 'random#4',
        5 => 'random#6',
        6 => 'random#7',
        7 => 'random#6',
        8 => 'random#7',
        9 => 'random#5',
      ),
      'code' => 'random#3',
    ),
    'languages' => 
    array (
      0 => 'random#2',
      1 => 'random#2',
      2 => 'random#10',
      3 => 'random#3',
      4 => 'random#7',
      5 => 'random#2',
      6 => 'random#6',
      7 => 'random#1',
      8 => 'random#8',
      9 => 'random#5',
    ),
    'currencies' => 
    array (
      0 => 'random#8',
      1 => 'random#3',
      2 => 'random#3',
      3 => 'random#7',
      4 => 'random#5',
      5 => 'random#2',
      6 => 'random#2',
      7 => 'random#1',
      8 => 'random#10',
      9 => 'random#2',
    ),
    'is_live_dealer' => 0,
    'date_established' => '2018-01-17 15:37:12',
    'emails' => 
    array (
      0 => 'random#9',
      1 => 'random#4',
      2 => 'random#2',
      3 => 'random#3',
      4 => 'random#10',
      5 => 'random#9',
      6 => 'random#9',
      7 => 'random#6',
      8 => 'random#3',
      9 => 'random#2',
    ),
    'phones' => 
    array (
      0 => 'random#8',
      1 => 'random#4',
      2 => 'random#2',
      3 => 'random#10',
      4 => 'random#1',
      5 => 'random#3',
      6 => 'random#6',
      7 => 'random#2',
      8 => 'random#1',
      9 => 'random#10',
    ),
    'is_live_chat' => 1,
    'licenses' => 
    array (
      0 => 'random#3',
      1 => 'random#3',
      2 => 'random#5',
      3 => 'random#8',
      4 => 'random#5',
      5 => 'random#6',
      6 => 'random#9',
      7 => 'random#5',
      8 => 'random#8',
      9 => 'random#3',
    ),
    'certifiers' => 
    array (
      0 => 'random#4',
      1 => 'random#1',
      2 => 'random#5',
      3 => 'random#6',
      4 => 'random#1',
      5 => 'random#3',
      6 => 'random#5',
      7 => 'random#6',
      8 => 'random#6',
      9 => 'random#6',
    ),
    'affiliate_program' => 'random#4',
    'withdrawal_minimum' => 'random#9',
    'withdrawal_limits' => 
    array (
      0 => 'random#7',
      1 => 'random#3',
      2 => 'random#10',
      3 => 'random#10',
      4 => 'random#8',
      5 => 'random#1',
      6 => 'random#10',
      7 => 'random#8',
      8 => 'random#10',
      9 => 'random#3',
    ),
    'withdrawal_timeframes' => 
    array (
      0 => 'random#1',
      1 => 'random#5',
      2 => 'random#1',
      3 => 'random#5',
      4 => 'random#1',
      5 => 'random#9',
      6 => 'random#9',
      7 => 'random#8',
      8 => 'random#2',
      9 => 'random#2',
    ),
    'deposit_methods' => 
    array (
      0 => 'random#9',
      1 => 'random#6',
      2 => 'random#8',
      3 => 'random#9',
      4 => 'random#9',
      5 => 'random#2',
      6 => 'random#4',
      7 => 'random#5',
      8 => 'random#8',
      9 => 'random#7',
    ),
    'withdraw_methods' => 
    array (
      0 => 'random#4',
      1 => 'random#5',
      2 => 'random#10',
      3 => 'random#3',
      4 => 'random#5',
      5 => 'random#8',
      6 => 'random#4',
      7 => 'random#5',
      8 => 'random#6',
      9 => 'random#3',
    ),
  ),
));
$this->response->setAttribute("new_games", array (
  0 => 
  array (
    'id' => 8,
    'name' => 'random#6',
    'type' => 'random#7',
    'software' => 'random#8',
    'release_date' => 'random#1',
    'technologies' => 
    array (
      0 => 'random#7',
      1 => 'random#7',
      2 => 'random#9',
      3 => 'random#4',
      4 => 'random#8',
      5 => 'random#1',
      6 => 'random#2',
      7 => 'random#4',
      8 => 'random#9',
      9 => 'random#1',
    ),
    'is_mobile' => 0,
    'is_3d' => 0,
    'overview' => 'random#4',
    'times_played' => 7,
    'play' => 
    array (
      'status' => 'random#9',
      'pattern' => 'random#1',
      'match' => 'random#1',
    ),
  ),
));
	}
}
