<?php
require_once("application/models/dao/GameManufacturers.php");
require_once("CasinosCounterController.php");
/*
* Software list by number of casinos.
*
* @requestMethod GET
* @responseFormat HTML
* @source https://xd.adobe.com/view/7bbdd623-2cdd-4cf4-971f-98d886e7a2b8/screen/2d8654a1-8033-4b0c-b193-aaaf41785d65/Software-Lists?fullscreen
*/
class SoftwaresController extends CasinosCounterController
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->response->attributes('software_logo_small', $this->getSoftwareLogo($this->response->attributes('results')));
    }

    protected function getCounter()
    {
        return new GameManufacturers();
    }

    private function getSoftwareLogo($logo_name)
    {
        $logo = array();
        $index =0;
        foreach ($logo_name as $key => $value) {
            $logo[$index++] = "/public/sync/software_logo_light/80x53/".strtolower(str_replace(" ", "_", $key)).".png";
        }
        return $logo;
    }
}
