<?php
class BankingMethodsController extends Controller {
    public function run() {
        $this->response->setAttribute("menu_top", array (
  0 => 
  array (
    'title' => 'CASINOS',
    'url' => '/casinos',
    'is_active' => false,
  ),
  1 => 
  array (
    'title' => 'SOFTWARES',
    'url' => '/softwares',
    'is_active' => false,
  ),
  2 => 
  array (
    'title' => 'BONUSES',
    'url' => '/bonus-list',
    'is_active' => false,
  ),
  3 => 
  array (
    'title' => 'COUNTRIES',
    'url' => '/countries',
    'is_active' => false,
  ),
  4 => 
  array (
    'title' => 'COMPATIBILITY',
    'url' => '/compatability',
    'is_active' => false,
  ),
  5 => 
  array (
    'title' => 'BANKING',
    'url' => '/banking',
    'is_active' => true,
  ),
  6 => 
  array (
    'title' => 'FEATURES',
    'url' => '/features',
    'is_active' => false,
  ),
  7 => 
  array (
    'title' => 'GAMES',
    'url' => '/games',
    'is_active' => false,
  ),
));
$this->response->setAttribute("results", array (
  'Visa' => '1077',
  'MasterCard' => '1034',
  'Neteller' => '958',
  'Skrill Moneybookers' => '832',
  'Paysafe Card' => '793',
  'Visa Electron' => '588',
  'Wire Transfer' => '534',
  'Maestro' => '529',
  'EcoPayz EcoCard' => '361',
  'SOFORT Banking' => '330',
  'Trustly' => '318',
  'giropay' => '275',
  'EntroPay' => '254',
  'iDEAL' => '241',
  'QIWI' => '189',
  'PayPal' => '180',
  'WebMoney' => '173',
  'Bitcoin Wallets' => '171',
  'POLi' => '168',
  'Euteller' => '145',
  'Moneta.ru' => '138',
  'Zimpler' => '124',
  'Wirecard' => '113',
  'Przelewy24' => '113',
  'MULTIBANCO' => '111',
  'iDebit' => '108',
  'UseMyServices' => '102',
  'Yandex.Money' => '87',
  'Boku' => '77',
  'American Express' => '77',
  'Neosurf' => '75',
  'TrustPay' => '75',
  'Diners Club' => '73',
  'Boleto Bancario' => '72',
  'eKonto' => '69',
  'Postepay' => '69',
  'eCheck' => '66',
  'Abaqoos' => '66',
  'Instant Banking By Citadel' => '66',
  'AstroPay' => '64',
  'PugglePay' => '59',
  'Dotpay' => '57',
  'Ticket Premium' => '49',
  'Todito Cash' => '44',
  'Bancontact Mister Cash' => '41',
  'EWIRE' => '40',
  'FundSend' => '37',
  'UPayCard' => '35',
  'Ezi Pay' => '35',
  'Entercash' => '34',
  'Sporopay' => '32',
  'ClickandBuy' => '30',
  'Teleingreso' => '29',
  'Cheque' => '28',
  'SafetyPay' => '26',
  'Siru Mobile' => '26',
  'CartaSi' => '25',
  'Kalibra Card' => '25',
  'EasyEFT' => '23',
  'ePay.bg' => '21',
  'PayU' => '17',
  'Discover' => '14',
  'Epro' => '13',
  'JCB' => '12',
  'Western Union' => '10',
  'OKPAY' => '10',
  'Carte Bleue' => '10',
  'Money Order' => '9',
  'LiqPay' => '9',
  'Wallet One' => '8',
  'Lottomaticard' => '8',
  'AGMO' => '8',
  'Dankort' => '8',
  'swiff' => '7',
  'Page en Efectivo' => '7',
  'Phone Bill' => '7',
  'eNETS' => '7',
  'Payforit' => '6',
  'MST Gift Card' => '6',
  'PaySpark' => '6',
  'EURO 6000' => '6',
  'Speedcard' => '6',
  'Transfer Money' => '6',
  'Paytrail' => '5',
  'OchaPay' => '5',
  'Paybox' => '5',
  'SID' => '5',
  'Money@Mail.ru' => '5',
  'Privat24' => '4',
  'Interkassa' => '4',
  'Direct Money' => '4',
  'iBANQ' => '4',
  'Intercash' => '3',
  'CASHU' => '3',
  'Kalixa' => '3',
  'Vanilla Card' => '3',
  'Switch' => '3',
  'Euroset' => '3',
  'Allied Wallet' => '2',
  'Cuenta Digital' => '2',
  'ELV' => '2',
  'INPAY' => '2',
  'Pago Facil' => '2',
  'MoneyGram' => '2',
  '4B' => '2',
  'PayNearMe' => '1',
  'AsiaPay' => '1',
  'GoCash' => '1',
  'easydebit' => '1',
  'BT Landlines' => '1',
  'MyMonedero' => '1',
));

    }
}
        