<?php
class BankingMethodsController extends Controller {
    public function run() {
        $this->response->setAttribute("country", array (
  'id' => '43',
  'code' => 'RO',
  'name' => 'Romania',
));
$this->response->setAttribute("menu_top", array (
  0 => 
  array (
    'title' => 'NO DEPOSIT CASINOS',
    'url' => '/bonus-list/no-deposit-bonus',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'NEW CASINOS',
    'url' => '/casinos/new',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'CASINOS',
    'url' => '/casinos',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Best Casinos' => '/casinos/best',
      'Live Casinos' => '/features/live-dealer',
      'Mobile Casinos' => '/casinos/mobile',
      'eCOGRA Casinos' => '/features/ecogra-casinos',
      'Stay Away Casinos' => '/casinos/stay-away',
      'Popular Casinos' => '/casinos/popular',
      'All Casinos' => '/casinos',
    ),
    'have_submenu' => true,
  ),
  3 => 
  array (
    'title' => 'SOFTWARES',
    'url' => '/softwares',
    'is_active' => false,
    'submenuItems' => 
    array (
      'RTG Casinos' => '/softwares/rtg',
      'Rival Casinos' => '/softwares/rival',
      'NetEnt Casinos' => '/softwares/netent',
      'Playtech Casinos' => '/softwares/playtech',
      'MicroGaming Casinos' => '/softwares/microgaming',
      'BetSoft Casinos' => '/softwares/betsoft',
      'Saucify Casinos' => '/softwares/saucify',
      'Cryptologic Casinos' => '/softwares/cryptologic',
      'All Softwares' => '/softwares',
    ),
    'have_submenu' => true,
  ),
  4 => 
  array (
    'title' => 'COUNTRIES',
    'url' => '/countries',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Romania Casinos' => '/countries-list/romania',
      'USA Casinos' => '/countries-list/united-states',
      'UK Casinos' => '/countries-list/united-kingdom',
      'Australia Casinos' => '/countries-list/australia',
      'Germany Casinos' => '/countries-list/germany',
      'New Zealand Casinos' => '/countries-list/new-zealand',
      'Netherlands Casinos' => '/countries-list/netherlands',
      'Sweden Casinos' => '/countries-list/sweden',
      'All Countries' => '/countries ',
    ),
    'have_submenu' => true,
  ),
  5 => 
  array (
    'title' => 'BANKING',
    'url' => '/banking',
    'is_active' => true,
    'submenuItems' => 
    array (
      'Neteller Casinos' => '/banking/neteller',
      'Skrill Moneybookers Casinos' => '/banking/skrill-moneybookers',
      'PayPal Casinos' => '/banking/paypal',
      'Bitcoin Wallets Casinos' => '/banking/bitcoin-wallets',
      'EcoPayz EcoCard Casinos' => '/banking/ecopayz',
      'Paysafe Card' => '/banking/paysafe-card',
      'All Banking' => '/banking',
    ),
    'have_submenu' => true,
  ),
  6 => 
  array (
    'title' => 'GAMES',
    'url' => '/games',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Video Slots' => '/games/video-slots',
      'Classic Slots' => '/games/slots',
      'Video Poker' => '/games/video-poker',
      'Scratch Cards' => '/games/scratch-cards',
      'Blackjack' => '/games/blackjack',
      'Roulette' => '/games/roulette',
      'Table Games' => '/games/table-games',
      'Bingo' => '/games/bingo',
      'Baccarat' => '/games/baccarat',
      'Craps' => '/games/craps',
      'Keno' => '/games/keno',
      'Other' => '/games/other',
      'All Games' => '/games',
    ),
    'have_submenu' => true,
  ),
));
$this->response->setAttribute("results", array (
  'Visa' => '1005',
  'MasterCard' => '967',
  'Neteller' => '885',
  'Skrill Moneybookers' => '770',
  'Paysafe Card' => '738',
  'Visa Electron' => '566',
  'Maestro' => '512',
  'Wire Transfer' => '494',
  'EcoPayz' => '324',
  'SOFORT Banking' => '282',
  'Trustly' => '257',
  'EntroPay' => '242',
  'giropay' => '236',
  'iDEAL' => '225',
  'POLi' => '171',
  'PayPal' => '167',
  'QIWI' => '162',
  'WebMoney' => '161',
  'Moneta.ru' => '137',
  'Euteller' => '130',
  'Bitcoin Wallets' => '124',
  'Przelewy24' => '122',
  'MULTIBANCO' => '113',
  'Wirecard' => '111',
  'iDebit' => '108',
  'UseMyServices' => '101',
  'eKonto' => '78',
  'Neosurf' => '77',
  'TrustPay' => '77',
  'Abaqoos' => '75',
  'Zimpler' => '74',
  'Diners Club' => '73',
  'American Express' => '73',
  'Postepay' => '70',
  'Instant Banking By Citadel' => '68',
  'Yandex.Money' => '68',
  'Boku' => '66',
  'Boleto Bancario' => '66',
  'eCheck' => '65',
  'Dotpay' => '62',
  'PugglePay' => '56',
  'Ticket Premium' => '51',
  'AstroPay' => '49',
  'FundSend' => '44',
  'EWIRE' => '44',
  'Bancontact Mister Cash' => '42',
  'Todito Cash' => '38',
  'UPayCard' => '38',
  'Ezi Pay' => '35',
  'Teleingreso' => '33',
  'ClickandBuy' => '32',
  'PayU' => '30',
  'Siru Mobile' => '29',
  'Cheque' => '28',
  'Sporopay' => '28',
  'CartaSi' => '28',
  'Kalibra Card' => '25',
  'SafetyPay' => '22',
  'ePay.bg' => '21',
  'Entercash' => '21',
  'Epro' => '16',
  'Discover' => '14',
  'JCB' => '13',
  'Speedcard' => '11',
  'Western Union' => '11',
  'LiqPay' => '10',
  'swiff' => '10',
  'AGMO' => '10',
  'Lottomaticard' => '9',
  'Money Order' => '9',
  'OKPAY' => '9',
  'Wallet One' => '9',
  'EasyEFT' => '9',
  'Dankort' => '9',
  'Carte Bleue' => '8',
  'INPAY' => '8',
  'Page en Efectivo' => '7',
  'eNETS' => '7',
  'EURO 6000' => '7',
  'Payforit' => '7',
  'Interkassa' => '7',
  'Money@Mail.ru' => '7',
  'MST Gift Card' => '6',
  'OchaPay' => '6',
  'PaySpark' => '6',
  'Phone Bill' => '6',
  'Paytrail' => '5',
  'Paybox' => '5',
  'Transfer Money' => '5',
  'CASHU' => '5',
  'SID' => '4',
  'Intercash' => '4',
  'Cuenta Digital' => '3',
  'Privat24' => '3',
  'iBANQ' => '3',
  'Pago Facil' => '3',
  'Vanilla Card' => '3',
  'MoneyGram' => '3',
  'Kalixa' => '3',
  '4B' => '3',
  'Direct Money' => '3',
  'Euroset' => '2',
  'Allied Wallet' => '2',
  'Cirrus Card' => '2',
  'ELV' => '2',
  'AsiaPay' => '2',
  'Switch' => '2',
  'banking2' => '1',
  'Quick Pesa' => '1',
  'PayNearMe' => '1',
  'William Hill CASHDIRECT' => '1',
  'Insta Cash' => '1',
  'GoCash' => '1',
  'easydebit' => '1',
  'MyMonedero' => '1',
  'BT Landlines' => '1',
  'Bestmoney' => '1',
));
$this->response->setAttribute("tms", array (
  'upper_text' => '<p>Banking -&nbsp; update</p>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using &#39;Content here, content here&#39;, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for &#39;lorem ipsum&#39; will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
',
));
$this->response->setAttribute("page_info", array (
  'head_title' => 'Full List of Online Casinos Payment Methods - CasinosLists.com',
  'head_description' => ' Online Casino Banking Methods | We\'ve summed all the accepted payment methods for online casinos, including Credit Cards, eWallets, Crypto and more.',
  'body_title' => 'Online Casino Banking Methods',
));
$this->response->setAttribute("version", '0.8.3.7');

    }
}
        