<?php
class CasinosByLabelController extends Controller {
    public function run() {
        $this->response->setAttribute("selected_entity", 'Best');
$this->response->setAttribute("menu", array (
  '/countries-list/united-states' => 'United States Casinos',
  '/casinos/best' => 'Best Casinos',
  '/bonus-list/no-deposit-bonus' => 'No Deposit Casinos',
  '/casinos/safe' => 'Safe Casinos',
  '/casinos/new' => 'New Casinos',
  '/casinos/recommended' => 'Recommended Casinos',
  '/casinos/stay-away' => 'Stay Away Casinos',
));
$this->response->setAttribute("country", array (
  'id' => '34',
  'code' => 'US',
  'name' => 'United States',
));
$this->response->setAttribute("total_casinos", 107);
$this->response->setAttribute("casinos", array (
  0 => 
  array (
    'id' => '1376',
    'name' => 'MrXbet Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'World Match',
      3 => 'iSoftBet',
      4 => 'BetSoft',
      5 => 'IGT',
      6 => 'Evolution Gaming',
      7 => 'Ezugi',
      8 => 'Play n GO',
      9 => 'XPG',
      10 => 'Kiron Interactive',
      11 => 'Betgames TV',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => ' €10',
      'wagering' => '40xB',
      'games_allowed' => 'All except jackpot 6000, Scrooge, Devil’s Delight, The Wish Master, Super Nudge 6000, Castle builder, Pearls of India, Tower Quest',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-05-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  1 => 
  array (
    'id' => '952',
    'name' => 'Naija Gaming Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'MicroGaming',
      3 => 'BetSoft',
      4 => 'Evolution Gaming',
      5 => 'TAIN',
      6 => 'Ezugi',
      7 => 'Play n GO',
      8 => 'Genii',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€5',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'bonusplease',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-10-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  2 => 
  array (
    'id' => '1220',
    'name' => 'Merkur Win Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'World Match',
      2 => 'Evolution Gaming',
      3 => 'Edict eGaming',
      4 => 'Capecod Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '€€20',
      'wagering' => '30xB',
      'games_allowed' => 'All',
      'code' => 'PROMO200CASINO',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2009-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  3 => 
  array (
    'id' => '1214',
    'name' => 'House of Jack Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'BetSoft',
      2 => 'Quickspin',
      3 => 'Play n GO',
      4 => 'Spigo',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 100 FS',
      'min_deposit' => '$/€20',
      'wagering' => '50x(D+B)',
      'games_allowed' => 'All (FS-Spinions)',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-05-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  4 => 
  array (
    'id' => '1192',
    'name' => 'Casino Calzone',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'NextGen Gaming',
      3 => 'MicroGaming',
      4 => 'WMS Gaming',
      5 => 'Yggdrasil Gaming',
      6 => 'Thunderkick',
      7 => 'Quickspin',
      8 => 'Play n GO',
      9 => 'ELK Studios',
      10 => 'Big Time Gaming',
      11 => 'Bally',
      12 => 'Blueprint Gaming',
      13 => 'Merkur Gaming',
      14 => 'Williams Interactive',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€/£10',
      'wagering' => '45xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-02-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  5 => 
  array (
    'id' => '1127',
    'name' => 'Svenska Bingo',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'iSoftBet',
      2 => 'Playtech',
      3 => 'NetEnt',
      4 => 'IGT',
      5 => 'Evolution Gaming',
      6 => 'OpenBet',
      7 => 'Eyecon',
      8 => 'Blueprint Gaming',
      9 => 'Realistic Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '100 SEK',
      'wagering' => '4xB',
      'games_allowed' => 'Roulette and Live Casino',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  6 => 
  array (
    'id' => '1124',
    'name' => 'Bet East Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'Ezugi',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£10',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All except BlackJack,Roulette and Table Games',
      'code' => '200FIRST',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  7 => 
  array (
    'id' => '1035',
    'name' => 'SuomiKasino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'MicroGaming',
      3 => 'Playtech',
      4 => 'BetSoft',
      5 => 'Games OS',
      6 => 'WMS Gaming',
      7 => 'Yggdrasil Gaming',
      8 => 'Thunderkick',
      9 => 'Evolution Gaming',
      10 => 'Quickspin',
      11 => 'Play n GO',
      12 => 'Relax Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 120 FS',
      'min_deposit' => '€10',
      'wagering' => '35xB',
      'games_allowed' => 'All (FS - Starburst,Gonzo\'s Quest,Twin Spin)',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2013-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  8 => 
  array (
    'id' => '1004',
    'name' => 'Bingo Extra',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'IGT',
      3 => 'Play n GO',
      4 => 'Eyecon',
      5 => 'Realistic Games',
      6 => 'Multicommerce Game Studio',
      7 => 'Scientific Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '400%',
      'min_deposit' => '€/£10',
      'wagering' => '4x(D+B)',
      'games_allowed' => 'Bingo',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  9 => 
  array (
    'id' => '892',
    'name' => '138.com Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Multislot',
      2 => 'SBTech',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€/£10',
      'wagering' => '30(D+B)',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  10 => 
  array (
    'id' => '858',
    'name' => 'Bingo Botemania',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'Gamesys',
      1 => 'High 5 Games',
      2 => 'Endemol Games',
      3 => 'Fremantle',
      4 => 'PopCap',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '€10',
      'wagering' => '4xB',
      'games_allowed' => 'Bingo',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2007-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  11 => 
  array (
    'id' => '855',
    'name' => 'BetBright Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'NextGen Gaming',
      2 => 'Nektan',
      3 => 'NetEnt',
      4 => '1X2 Gaming',
      5 => 'ELK Studios',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '10 GBP',
      'wagering' => '50xB',
      'games_allowed' => 'All except Baccarat, Craps, Casino War, All Aces, Jacks or Better, Red Dog, Sic Bo, Max Damages & Alien Attack',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-08-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  12 => 
  array (
    'id' => '852',
    'name' => 'Pink Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'iSoftBet',
      2 => 'Playtech',
      3 => 'NetEnt',
      4 => 'IGT',
      5 => 'Evolution Gaming',
      6 => 'Eyecon',
      7 => 'Realistic Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '£10',
      'wagering' => '20x(D+B)',
      'games_allowed' => 'All except Roulette and Live Casino',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '£10',
      'min_deposit' => '',
      'wagering' => '99xB',
      'games_allowed' => 'All except Roulette and Live Casino',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  13 => 
  array (
    'id' => '835',
    'name' => 'SveaCasino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'Amaya Gaming',
      3 => 'Yggdrasil Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => 'SEK€200',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  14 => 
  array (
    'id' => '776',
    'name' => 'Spin Genie Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'IGT',
      3 => 'Eyecon',
      4 => 'Realistic Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '£10',
      'wagering' => '30xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-10-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  15 => 
  array (
    'id' => '549',
    'name' => 'WONClub Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'BetSoft',
      2 => 'Evolution Gaming',
      3 => 'Quickspin',
      4 => 'Ezugi',
      5 => 'GameArt',
      6 => 'XPG',
      7 => 'Pragmatic Play',
      8 => 'BetConstruct',
      9 => 'Betgames TV',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '25%',
      'min_deposit' => '€/£20',
      'wagering' => '20xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-12-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  16 => 
  array (
    'id' => '533',
    'name' => 'Vegas Regal Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£25',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All except Video Poker & Progresive Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£120',
      'min_deposit' => '',
      'wagering' => '100xB',
      'games_allowed' => 'All except Video Poker & Progressive Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2009-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  17 => 
  array (
    'id' => '492',
    'name' => 'VegasBerry Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Oryx Gaming',
      2 => 'MicroGaming',
      3 => 'Quickfire',
      4 => '1X2 Gaming',
      5 => 'RCT Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '150%',
      'min_deposit' => '$/€/£20',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  18 => 
  array (
    'id' => '458',
    'name' => 'Reel Spin Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '40 FS',
      'min_deposit' => '$35',
      'wagering' => '35xB',
      'games_allowed' => 'Lucha Libre',
      'code' => '40BIGSPINS',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2013-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  19 => 
  array (
    'id' => '406',
    'name' => 'Bingorella',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'IGT',
      1 => 'NYX Interactive',
      2 => 'NetEnt',
      3 => 'Eyecon',
      4 => 'Pariplay',
      5 => 'GGP',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '£10 + 10 FS',
      'min_deposit' => '$/€/£10',
      'wagering' => '50xB',
      'games_allowed' => 'The Magical Forest',
      'code' => 'ONE',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
));

    }
}
        