<?php
class CasinosBySoftwareController extends Controller {
    public function run() {
        $this->response->setAttribute("country", array (
  'id' => '34',
  'code' => 'US',
  'name' => 'United States',
));
$this->response->setAttribute("menu_top", array (
  0 => 
  array (
    'title' => 'NO DEPOSIT CASINOS',
    'url' => '/bonus-list/no-deposit-bonus',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'NEW CASINOS',
    'url' => '/casinos/new',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'CASINOS',
    'url' => '/casinos',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Best Casinos' => '/casinos/best',
      'Live Casinos' => '/features/live-dealer',
      'Mobile Casinos' => '/casinos/mobile',
      'eCOGRA Casinos' => '/features/ecogra-casinos',
      'Stay Away Casinos' => '/casinos/stay-away',
      'Popular Casinos' => '/casinos/popular',
      'All Casinos' => '/casinos',
    ),
    'have_submenu' => true,
  ),
  3 => 
  array (
    'title' => 'SOFTWARES',
    'url' => '/softwares',
    'is_active' => true,
    'submenuItems' => 
    array (
      'RTG Casinos' => '/softwares/rtg',
      'Rival Casinos' => '/softwares/rival',
      'NetEnt Casinos' => '/softwares/netent',
      'Playtech Casinos' => '/softwares/playtech',
      'MicroGaming Casinos' => '/softwares/microgaming',
      'BetSoft Casinos' => '/softwares/betsoft',
      'Saucify Casinos' => '/softwares/saucify',
      'Cryptologic Casinos' => '/softwares/cryptologic',
      'All Softwares' => '/softwares',
    ),
    'have_submenu' => true,
  ),
  4 => 
  array (
    'title' => 'COUNTRIES',
    'url' => '/countries',
    'is_active' => false,
    'submenuItems' => 
    array (
      'USA Casinos' => '/countries-list/united-states',
      'UK Casinos' => '/countries-list/united-kingdom',
      'Australia Casinos' => '/countries-list/australia',
      'Germany Casinos' => '/countries-list/germany',
      'New Zealand Casinos' => '/countries-list/new-zealand',
      'Netherlands Casinos' => '/countries-list/netherlands',
      'Sweden Casinos' => '/countries-list/sweden',
      'All Countries' => '/countries ',
    ),
    'have_submenu' => true,
  ),
  5 => 
  array (
    'title' => 'BANKING',
    'url' => '/banking',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Neteller Casinos' => '/banking/neteller',
      'Skrill Moneybookers Casinos' => '/banking/skrill-moneybookers',
      'PayPal Casinos' => '/banking/paypal',
      'Bitcoin Wallets Casinos' => '/banking/bitcoin-wallets',
      'EcoPayz EcoCard Casinos' => '/banking/ecopayz',
      'Paysafe Card' => '/banking/paysafe-card',
      'All Banking' => '/banking',
    ),
    'have_submenu' => true,
  ),
  6 => 
  array (
    'title' => 'GAMES',
    'url' => '/games',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Video Slots' => '/games/video-slots',
      'Classic Slots' => '/games/classic-slots',
      'Video Poker' => '/games/video-poker',
      'Scratch Cards' => '/games/scratch-cards',
      'Blackjack' => '/games/blackjack',
      'Roulette' => '/games/roulette',
      'Table Games' => '/games/table-games',
      'Bingo' => '/games/bingo',
      'Baccarat' => '/games/baccarat',
      'Craps' => '/games/craps',
      'Keno' => '/games/keno',
      'Other' => '/games/other',
      'All Games' => '/games',
    ),
    'have_submenu' => true,
  ),
));
$this->response->setAttribute("selected_entity", 'Saucify');
$this->response->setAttribute("is_mobile", false);
$this->response->setAttribute("menu_bottom", array (
  0 => 
  array (
    'title' => 'All Softwares',
    'url' => '/softwares',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'Saucify Casinos',
    'url' => '/softwares/saucify',
    'is_active' => true,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'RTG Casinos',
    'url' => '/softwares/rtg',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  3 => 
  array (
    'title' => 'Rival Casinos',
    'url' => '/softwares/rival',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  4 => 
  array (
    'title' => 'NetEnt Casinos',
    'url' => '/softwares/netent',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  5 => 
  array (
    'title' => 'Playtech Casinos',
    'url' => '/softwares/playtech',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  6 => 
  array (
    'title' => 'MicroGaming Casinos',
    'url' => '/softwares/microgaming',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  7 => 
  array (
    'title' => 'BetSoft Casinos',
    'url' => '/softwares/betsoft',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  8 => 
  array (
    'title' => 'Cryptologic Casinos',
    'url' => '/softwares/cryptologic',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  9 => 
  array (
    'title' => 'IGT Casinos',
    'url' => '/softwares/igt',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  10 => 
  array (
    'title' => 'NYX Interactive Casinos',
    'url' => '/softwares/nyx-interactive',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
));
$this->response->setAttribute("sort_criteria", 1);
$this->response->setAttribute("filter", 'software');
$this->response->setAttribute("total_casinos", '25');
$this->response->setAttribute("casinos", array (
  0 => 
  array (
    'id' => '1058',
    'name' => 'Jackpot Wheel Casino',
    'code' => 'jackpot_wheel_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'JACKPOT100',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£35',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'JACKPOT35',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jul. 01, 2016',
    'status' => '0',
  ),
  1 => 
  array (
    'id' => '1057',
    'name' => 'Jumba Bet Casino',
    'code' => 'jumba_bet_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'LISTS200',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '50',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'Big Game Slot',
      'code' => ' LISTS50',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jul. 01, 2016',
    'status' => '0',
  ),
  2 => 
  array (
    'id' => '426',
    'name' => 'Vegas Crest Casino',
    'code' => 'vegas_crest_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'VistaGaming',
      2 => 'Booming Games',
      3 => 'Rival',
      4 => 'Saucify',
      5 => 'Endorphina',
      6 => 'Habanero',
      7 => 'GameArt',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200% + 30 FS',
      'min_deposit' => '$/€/£25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All (FS - Pinocchio)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '10',
      'min_deposit' => '',
      'wagering' => '99xB',
      'games_allowed' => 'The Tipsy Tourist',
      'code' => 'No code required',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2014-06-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jun. 01, 2014',
    'status' => '0',
  ),
  3 => 
  array (
    'id' => '348',
    'name' => 'Mandarin Palace',
    'code' => 'mandarin_palace',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '115%',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All except Progressives',
      'code' => '1STCASINOSLISTSMP',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£20',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'All except Progressives',
      'code' => 'FREECASINOLISTSMP',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2009-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2009',
    'status' => '0',
  ),
  4 => 
  array (
    'id' => '347',
    'name' => 'Wizbet Casino',
    'code' => 'wizbet_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£20',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'All',
      'code' => '1STCASINOSLISTSWB',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '30',
      'min_deposit' => '',
      'wagering' => '45xB',
      'games_allowed' => 'MaxCash',
      'code' => 'FREECASINOLISTSWB',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2009-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2009',
    'status' => '0',
  ),
  5 => 
  array (
    'id' => '346',
    'name' => 'Treasure Mile Casino',
    'code' => 'treasure_mile_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '120%',
      'min_deposit' => '$20',
      'wagering' => '40xB',
      'games_allowed' => 'All except Progressives',
      'code' => 'NONSTOPBONUSTM',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '30',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'Nascash',
      'code' => 'FREENONSTOPBONUS',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2009-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2009',
    'status' => '0',
  ),
  6 => 
  array (
    'id' => '329',
    'name' => 'Lucky Creek Casino',
    'code' => 'lucky_creek_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '110%',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All except Progressives',
      'code' => '1STCASINOSLISTSLC',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£25',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'All except Progressives',
      'code' => 'FREECASINOLISTSLC',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2009-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2009',
    'status' => '0',
  ),
  7 => 
  array (
    'id' => '286',
    'name' => 'Grand Eagle Casino',
    'code' => 'grand_eagle_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '110%',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All except Progressives',
      'code' => '1STCASINOSLISTSGE',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£25',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'All except Progressives',
      'code' => 'FREECASINOLISTSGE ',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2009-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2009',
    'status' => '0',
  ),
  8 => 
  array (
    'id' => '656',
    'name' => 'SlotsMillion Casino',
    'code' => 'slotsmillion_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Leander Games',
      2 => 'NextGen Gaming',
      3 => 'MicroGaming',
      4 => 'Cryptologic',
      5 => 'iSoftBet',
      6 => 'Playtech',
      7 => 'BetSoft',
      8 => 'Games OS',
      9 => 'MGA',
      10 => 'Casino Technology',
      11 => 'Pragmatic Play',
      12 => 'Rival',
      13 => 'Lightning Box Games',
      14 => 'Saucify',
      15 => 'Thunderkick',
      16 => 'Quickspin',
      17 => '1X2 Gaming',
      18 => 'Push Gaming',
      19 => 'Wagermill',
      20 => '2By2 Gaming',
      21 => 'Playson',
      22 => 'Play n GO',
      23 => 'ELK Studios',
      24 => 'Genesis Gaming',
      25 => 'Big Time Gaming',
      26 => 'Rabcat',
      27 => 'Merkur Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 100 FS',
      'min_deposit' => '€/£20',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All (FS - Gonzos Quest, Twin Spin, Jack and the Beanstalk, Spinata Grande, Fruit Shop)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-12-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Dec. 01, 2014',
    'status' => '0',
  ),
  9 => 
  array (
    'id' => '369',
    'name' => 'BingoFest',
    'code' => 'bingofest',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'VistaGaming',
      1 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$/€/£25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '20  + $25',
      'min_deposit' => '',
      'wagering' => '99xB',
      'games_allowed' => 'Bingo (FS - Wicked Reels)',
      'code' => 'No code required',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2003-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Mar. 01, 2003',
    'status' => '0',
  ),
  10 => 
  array (
    'id' => '363',
    'name' => 'CyberBingo',
    'code' => 'cyberbingo',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'VistaGaming',
      1 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$/€/£25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No Code Required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '20  + $25',
      'min_deposit' => '',
      'wagering' => '99xB',
      'games_allowed' => 'Bingo (FS - Wicked Reels)',
      'code' => 'No Code Required',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '1996-08-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Aug. 01, 1996',
    'status' => '0',
  ),
  11 => 
  array (
    'id' => '358',
    'name' => 'BingoSpirit',
    'code' => 'bingosky',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'VistaGaming',
      1 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$/€/£25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$25 + 20',
      'min_deposit' => '',
      'wagering' => '99xB',
      'games_allowed' => 'Bingo (FS - Wicked Reels)',
      'code' => 'No code required',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2004-11-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Nov. 01, 2004',
    'status' => '3',
  ),
  12 => 
  array (
    'id' => '85',
    'name' => 'Big Dollar Casino',
    'code' => 'bet_big_dollar',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£20',
      'wagering' => '20xD',
      'games_allowed' => 'Slots (Progressive Slots excluded) & Keno ',
      'code' => 'WELCOME200',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£15',
      'min_deposit' => '',
      'wagering' => '45xB',
      'games_allowed' => 'All',
      'code' => 'CASINOSLISTS15',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2006-05-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'May. 01, 2006',
    'status' => '0',
  ),
  13 => 
  array (
    'id' => '84',
    'name' => 'Villa Fortuna Casino',
    'code' => 'bet_villa_fortuna',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'VFPW1',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£20',
      'min_deposit' => '',
      'wagering' => '45xB',
      'games_allowed' => 'All',
      'code' => 'MFC20V',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2008-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2008',
    'status' => '0',
  ),
  14 => 
  array (
    'id' => '428',
    'name' => 'Fone Casino',
    'code' => 'fone_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'FONE1000',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '20',
      'min_deposit' => '',
      'wagering' => '45xB',
      'games_allowed' => 'Legends of Greece',
      'code' => 'FC4TBFCL',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2011-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Sep. 01, 2011',
    'status' => '0',
  ),
  15 => 
  array (
    'id' => '232',
    'name' => 'Black Lotus Casino',
    'code' => 'black_lotus_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'BLC500',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '20',
      'min_deposit' => '',
      'wagering' => '45xB',
      'games_allowed' => 'Arcadia i3D',
      'code' => 'TBFCL',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2012-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2012',
    'status' => '0',
  ),
  16 => 
  array (
    'id' => '230',
    'name' => 'Lotus Asia Casino',
    'code' => 'lotus_asia_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'LOT200WB',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '20',
      'min_deposit' => '',
      'wagering' => '45xB',
      'games_allowed' => 'Slots & Legends of Olympia',
      'code' => 'LAC4TBFCL',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2011-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2011',
    'status' => '0',
  ),
  17 => 
  array (
    'id' => '339',
    'name' => 'Tropezia Palace Casino',
    'code' => 'tropezia_palace_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'MGA',
      2 => 'Nektan',
      3 => 'Leander Games',
      4 => 'Saucify',
      5 => 'Yggdrasil Gaming',
      6 => 'Thunderkick',
      7 => 'Quickspin',
      8 => '2By2 Gaming',
      9 => 'Playson',
      10 => 'Play n GO',
      11 => 'ELK Studios',
      12 => 'Big Time Gaming',
      13 => 'Blueprint Gaming',
      14 => 'Lightning Box Games',
      15 => 'Ainsworth',
      16 => 'Felt Gaming',
      17 => 'BetSoft',
      18 => 'iSoftBet',
      19 => 'Cryptologic',
      20 => 'MicroGaming',
      21 => 'NextGen Gaming',
      22 => 'NetEnt',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£10',
      'wagering' => '20x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2010-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2010',
    'status' => '0',
  ),
  18 => 
  array (
    'id' => '49',
    'name' => 'Planet Casino',
    'code' => 'planet_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£20',
      'wagering' => '60xB',
      'games_allowed' => 'All',
      'code' => 'Planet1',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$25',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'All',
      'code' => 'LAUNCH',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2011-06-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jun. 01, 2011',
    'status' => '0',
  ),
  19 => 
  array (
    'id' => '958',
    'name' => 'Casino Grand Bay',
    'code' => 'casino_grand_bay',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£25',
      'wagering' => '40xB',
      'games_allowed' => 'All except Roulette,Three Card Poker & Baccarat',
      'code' => '1CGB100P',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2001-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Apr. 01, 2001',
    'status' => '1',
  ),
  20 => 
  array (
    'id' => '382',
    'name' => 'Lake Palace Casino',
    'code' => 'lake_palace_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '110%',
      'min_deposit' => '$/€/£25',
      'wagering' => '40xB',
      'games_allowed' => 'All except Roulette & Three Card Poker,Baccarat',
      'code' => 'LPNW1',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2001-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2001',
    'status' => '1',
  ),
  21 => 
  array (
    'id' => '380',
    'name' => 'Jupiter Club Casino',
    'code' => 'jupiter_club_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£25',
      'wagering' => '40xB',
      'games_allowed' => 'All except Roulette & Three Card Poker,Baccarat',
      'code' => '1JCC100P',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2001-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Apr. 01, 2001',
    'status' => '1',
  ),
  22 => 
  array (
    'id' => '330',
    'name' => 'Platinum Reels Casino',
    'code' => 'platinum_reels_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'CASINOSLISTS200',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '60',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'Reels of Rock',
      'code' => 'CASINOSLISTS60',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2011-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2011',
    'status' => '1',
  ),
  23 => 
  array (
    'id' => '322',
    'name' => 'Roadhouse Reels',
    'code' => 'roadhouse_reels',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '110%',
      'min_deposit' => '$/€/£25',
      'wagering' => '40xB',
      'games_allowed' => 'All except Roulette & Tri Card Poker,Baccarat',
      'code' => 'RHWB1',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2001-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Apr. 01, 2001',
    'status' => '1',
  ),
  24 => 
  array (
    'id' => '288',
    'name' => 'Bella Vegas Casino',
    'code' => 'bella_vegas_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£25',
      'wagering' => '40xB',
      'games_allowed' => 'All except Roulette & Three Card Poker,Baccarat',
      'code' => '1BVO100P',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2001-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Apr. 01, 2001',
    'status' => '1',
  ),
));
$this->response->setAttribute("page_info", array (
  'head_title' => 'Saucify Casinos List: Find All Saucify Casinos At CasinosLists.com',
  'head_description' => 'Full Saucify Casinos List | Details Information About Saucify Casinos, All Saucify Casinos and Games on one List - 2018',
  'body_title' => 'Saucify Casinos List December 2018',
));
$this->response->setAttribute("version", '0.8.3.6');
$this->response->setAttribute("tms", array (
));

    }
}
        