<?php
class CasinosByCompatibilityController extends Controller {
    public function run() {
        $this->response->setAttribute("selected_entity", 'Mac');
$this->response->setAttribute("menu", array (
  '/countries-list/united-states' => 'United States Casinos',
  '/compatability/mac' => 'Mac Casinos',
  '/bonus-list/no-deposit-bonus' => 'No Deposit Casinos',
  '/casinos/best' => 'Best Casinos',
  '/casinos/safe' => 'Safe Casinos',
  '/casinos/new' => 'New Casinos',
  '/casinos/recommended' => 'Recommended Casinos',
  '/casinos/stay-away' => 'Stay Away Casinos',
));
$this->response->setAttribute("country", array (
  'id' => '34',
  'code' => 'US',
  'name' => 'United States',
));
$this->response->setAttribute("total_casinos", 1088);
$this->response->setAttribute("casinos", array (
  0 => 
  array (
    'id' => '29',
    'name' => 'Tropica Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£25',
      'wagering' => '25x(D+B)',
      'games_allowed' => 'All except Keno,Roulette,Craps & Baccarat,Double Up,Red Dog,Sicbo,Progressive Games',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£50',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2009-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  1 => 
  array (
    'id' => '1357',
    'name' => 'Babe Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NextGen Gaming',
      2 => 'Wazdan',
      3 => 'iSoftBet',
      4 => 'Cryptologic',
      5 => 'Evolution Gaming',
      6 => 'OMI Gaming',
      7 => 'Ezugi',
      8 => 'Multislot',
      9 => 'Playson',
      10 => 'Patagonia Entertainment',
      11 => 'ELK Studios',
      12 => 'Genesis Gaming',
      13 => 'Habanero',
      14 => 'GameArt',
      15 => 'Pariplay',
      16 => 'Genii',
      17 => 'Booming Games',
      18 => 'Pragmatic Play',
      19 => 'BetConstruct',
      20 => 'EGT',
      21 => 'Zeus Services',
      22 => 'Spigo',
      23 => 'Iron Dog Studio',
      24 => 'Join Games',
      25 => 'Casino Technology',
      26 => 'MrSlotty Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200% + 100 FS',
      'min_deposit' => '€10',
      'wagering' => '40xB',
      'games_allowed' => 'Slots (FS - Fresh Fruits, Bake House, Santa Surprise, Under Water)',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  2 => 
  array (
    'id' => '1315',
    'name' => 'Breakout Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Pragmatic Play',
      2 => 'Evolution Gaming',
      3 => 'Quickfire',
      4 => '1X2 Gaming',
      5 => 'Pariplay',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€10',
      'wagering' => '70xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-10-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  3 => 
  array (
    'id' => '1193',
    'name' => 'Mars Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'iSoftBet',
      2 => 'BetSoft',
      3 => 'NetEnt',
      4 => 'Ezugi',
      5 => 'SoftSwiss',
      6 => 'Amatic Industries',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 50 FS',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-02-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  4 => 
  array (
    'id' => '1189',
    'name' => 'Hera Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'RTG',
      1 => 'Yggdrasil Gaming',
      2 => 'Pragmatic Play',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$30',
      'wagering' => '30xD',
      'games_allowed' => 'All',
      'code' => 'TBFCL1ST',
    ),
    'bonus_free' => 
    array (
      'amount' => '$50',
      'min_deposit' => '',
      'wagering' => '50xB',
      'games_allowed' => 'All',
      'code' => 'TBFCLFREE50',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-02-02',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  5 => 
  array (
    'id' => '1184',
    'name' => 'Burnbet Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Unicum',
      2 => 'Novomatic',
      3 => 'Playtech',
      4 => 'BetSoft',
      5 => 'RTG',
      6 => 'Aristocrat',
      7 => 'Igrosoft',
      8 => 'EGT',
      9 => 'Mega Jack',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€/£20',
      'wagering' => '35xB',
      'games_allowed' => 'All except Realtime Gaming,Playtech,Betsoft,Netent slots',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-01-15',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  6 => 
  array (
    'id' => '1164',
    'name' => 'Aunty Acid Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Cozy Games',
      2 => 'Eyecon',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$/€/£10',
      'wagering' => '10x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£15',
      'min_deposit' => '',
      'wagering' => '10x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2005-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  7 => 
  array (
    'id' => '1090',
    'name' => 'Quackpot Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$/€/£10',
      'wagering' => '20xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£10',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  8 => 
  array (
    'id' => '1089',
    'name' => 'Merlin Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$/€/£10',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£10',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  9 => 
  array (
    'id' => '1088',
    'name' => 'Lucky Ladies Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Cozy Games',
      2 => 'Eyecon',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300%',
      'min_deposit' => '£5',
      'wagering' => '20xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  10 => 
  array (
    'id' => '1087',
    'name' => 'Girly Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '350%',
      'min_deposit' => '$/€/£10',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£15',
      'min_deposit' => '',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  11 => 
  array (
    'id' => '1085',
    'name' => 'Eat Sleep Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$/€/£10',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£10',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  12 => 
  array (
    'id' => '1084',
    'name' => 'Viking Winners Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$/€/£10',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£10',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  13 => 
  array (
    'id' => '1083',
    'name' => 'Time Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '£10',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '£15',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  14 => 
  array (
    'id' => '1082',
    'name' => 'The Prize Finder Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '£10',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '£10',
      'min_deposit' => '',
      'wagering' => '',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  15 => 
  array (
    'id' => '1080',
    'name' => 'Champers Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$/€/£10',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£10',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  16 => 
  array (
    'id' => '1073',
    'name' => 'Naughty Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '£10',
      'wagering' => '40xB',
      'games_allowed' => 'Slots & Bingo',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '£15',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Cozy Games',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  17 => 
  array (
    'id' => '1071',
    'name' => 'Lucky Touch Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$/€/£10',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£10',
      'min_deposit' => '',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  18 => 
  array (
    'id' => '1070',
    'name' => 'Play2win Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300%',
      'min_deposit' => '$/€/£10',
      'wagering' => '20x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  19 => 
  array (
    'id' => '1045',
    'name' => 'Love My Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '£500',
      'min_deposit' => '£10',
      'wagering' => '10x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '£15',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2005-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
));

    }
}
        