<?php
class CasinoWarningController extends Controller {
    public function run() {
        $this->response->setAttribute("casino", array (
  'id' => '10',
  'name' => 'Casino Bellevue',
  'rating' => 6,
  'softwares' => 'RTG',
  'languages' => NULL,
  'currencies' => NULL,
  'bonus_first_deposit' => NULL,
  'bonus_free' => NULL,
  'is_live_dealer' => NULL,
  'date_established' => NULL,
  'emails' => NULL,
  'phones' => NULL,
  'is_live_chat' => NULL,
  'licenses' => NULL,
  'certifiers' => NULL,
  'affiliate_program' => NULL,
  'affiliate_link' => 'http://ads.bellevueaffiliates.com/redirect.aspx?pid=25992&bid=1726',
  'withdrawal_minimum' => NULL,
  'withdrawal_limits' => NULL,
  'withdrawal_timeframes' => NULL,
  'deposit_methods' => NULL,
  'withdraw_methods' => NULL,
  'is_country_accepted' => NULL,
  'is_language_accepted' => NULL,
  'is_currency_accepted' => NULL,
  'status' => 'Attention',
  'is_open' => '0',
));
$this->response->setAttribute("recommended_casinos", array (
  0 => 
  array (
    'id' => '1189',
    'name' => 'Hera Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'RTG',
      1 => 'Pragmatic Play',
      2 => 'Yggdrasil Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$30',
      'wagering' => '30xD',
      'games_allowed' => 'All',
      'code' => 'TBFCL1ST',
    ),
    'bonus_free' => 
    array (
      'amount' => '$50',
      'min_deposit' => '',
      'wagering' => '50xB',
      'games_allowed' => 'All',
      'code' => 'TBFCLFREE50',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-02-02',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  1 => 
  array (
    'id' => '1029',
    'name' => '5Dimes Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'RTG',
      1 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '50%',
      'min_deposit' => '$50',
      'wagering' => '1xB',
      'games_allowed' => 'All except Roulette,Craps & Baccarat and Progressive Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '1998-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  2 => 
  array (
    'id' => '830',
    'name' => 'Diamond Reels Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '225%',
      'min_deposit' => '$25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'DRBFC225',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  3 => 
  array (
    'id' => '509',
    'name' => 'Platinum Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Tom Horn',
      2 => 'Alps Games',
      3 => 'Mega Jack',
      4 => 'Unicum',
      5 => 'EGT',
      6 => 'XPG',
      7 => 'Igrosoft',
      8 => 'Aristocrat',
      9 => 'RTG',
      10 => 'NetEnt',
      11 => 'BetSoft',
      12 => 'Playtech',
      13 => 'Novomatic',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€11',
      'wagering' => '20xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  4 => 
  array (
    'id' => '107',
    'name' => 'Slots Inferno',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '$980',
      'min_deposit' => '$20',
      'wagering' => '120x(D+B)',
      'games_allowed' => 'Slots',
      'code' => 'WIN1000',
    ),
    'bonus_free' => 
    array (
      'amount' => '$100',
      'min_deposit' => '',
      'wagering' => '25xB',
      'games_allowed' => 'Slots',
      'code' => 'CASINOSLISTS100',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2011-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
));
$this->response->setAttribute("menu", array (
  '/countries-list/united-states' => 'United States Casinos',
  '/warn/Casino-Bellevue' => 'Casino Bellevue',
  '/bonus-list/no-deposit-bonus' => 'No Deposit Casinos',
  '/casinos/best' => 'Best Casinos',
  '/casinos/safe' => 'Safe Casinos',
  '/casinos/new' => 'New Casinos',
  '/casinos/recommended' => 'Recommended Casinos',
  '/casinos/stay-away' => 'Stay Away Casinos',
));

    }
}
        