<?php
class CasinosFilterController extends Controller {
    public function run() {
        $this->response->setAttribute("country", array (
  'id' => '34',
  'code' => 'US',
  'name' => 'United States',
));
$this->response->setAttribute("total_casinos", 36);
$this->response->setAttribute("casinos", array (
  0 => 
  array (
    'id' => '1029',
    'name' => '5Dimes Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'RTG',
      1 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '50%',
      'min_deposit' => '$50',
      'wagering' => '1xB',
      'games_allowed' => 'All except Roulette,Craps & Baccarat and Progressive Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '1998-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  1 => 
  array (
    'id' => '682',
    'name' => 'Casino Girl',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'Novomatic',
      2 => 'Playtech',
      3 => 'NetEnt',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '250%',
      'min_deposit' => '$/€20',
      'wagering' => '85xB',
      'games_allowed' => 'Betsoft Slots',
      'code' => '250SLOTS',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  2 => 
  array (
    'id' => '591',
    'name' => 'LaRomere Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots (5 x Win)',
      'code' => '1STCASINOSLISTS',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  3 => 
  array (
    'id' => '509',
    'name' => 'Platinum Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Novomatic',
      2 => 'Playtech',
      3 => 'BetSoft',
      4 => 'NetEnt',
      5 => 'RTG',
      6 => 'Aristocrat',
      7 => 'Igrosoft',
      8 => 'XPG',
      9 => 'EGT',
      10 => 'Unicum',
      11 => 'Mega Jack',
      12 => 'Alps Games',
      13 => 'Tom Horn',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€11',
      'wagering' => '20xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  4 => 
  array (
    'id' => '334',
    'name' => 'MoneyStorm Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£20',
      'wagering' => '60xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-12-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  5 => 
  array (
    'id' => '118',
    'name' => 'Pamper Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '2000%',
      'min_deposit' => '$/€/£20',
      'wagering' => '80xB',
      'games_allowed' => 'Slots',
      'code' => '2000SLOTS',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£100',
      'min_deposit' => '',
      'wagering' => '80xB',
      'games_allowed' => 'All',
      'code' => '100FREE',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2007-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  6 => 
  array (
    'id' => '113',
    'name' => 'AC Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '2222%',
      'min_deposit' => '$/€20',
      'wagering' => '50xB',
      'games_allowed' => 'Slots',
      'code' => '2000SLOTS',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2010-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  7 => 
  array (
    'id' => '74',
    'name' => 'Carat Bingo',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'Aberrant',
      3 => 'Play n GO',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€10',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'Slots,Bingo & Casino',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  8 => 
  array (
    'id' => '976',
    'name' => 'Royal Flamingo Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'PlayPearls',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£25',
      'wagering' => '30xB',
      'games_allowed' => 'All',
      'code' => 'FIRST',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2006-11-07',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  9 => 
  array (
    'id' => '785',
    'name' => 'VegasCasino.io',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'Quickspin',
      2 => 'Ezugi',
      3 => 'Play n GO',
      4 => 'Endorphina',
      5 => 'GameArt',
      6 => 'Booming Games',
      7 => 'Pragmatic Play',
      8 => 'BetGames',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '150%',
      'min_deposit' => '0.001 ........ .... .. . BTC.',
      'wagering' => '35xB',
      'games_allowed' => 'All',
      'code' => 'WELCOME150',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-12-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  10 => 
  array (
    'id' => '241',
    'name' => 'Tradition Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£30',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2007-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  11 => 
  array (
    'id' => '1171',
    'name' => '1xBit Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'Novomatic',
      3 => 'Playtech',
      4 => 'BetSoft',
      5 => 'IGT',
      6 => 'Aristocrat',
      7 => 'Evolution Gaming',
      8 => 'Ezugi',
      9 => 'Playson',
      10 => 'Igrosoft',
      11 => 'Play n GO',
      12 => 'Endorphina',
      13 => 'GameArt',
      14 => 'Amatic Industries',
      15 => 'XPG',
      16 => 'Pragmatic Play',
      17 => 'EGT',
      18 => 'Tom Horn',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '0.005 BTC',
      'wagering' => '5xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2007-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  12 => 
  array (
    'id' => '1124',
    'name' => 'Bet East Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Ezugi',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£10',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All except BlackJack,Roulette and Table Games',
      'code' => '200FIRST',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  13 => 
  array (
    'id' => '1065',
    'name' => 'Betive Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NextGen Gaming',
      2 => 'MicroGaming',
      3 => 'iSoftBet',
      4 => 'Evolution Gaming',
      5 => 'Quickspin',
      6 => 'Quickfire',
      7 => 'ELK Studios',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€10',
      'wagering' => '45xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  14 => 
  array (
    'id' => '1064',
    'name' => 'HRwager Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'SoftSwiss',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$0100',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All except Craps,Roulette and Dice Games',
      'code' => 'WELCOME500',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-12-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  15 => 
  array (
    'id' => '990',
    'name' => 'Bogart Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'SoftSwiss',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$0100',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All except Roulette,Craps & Dice Games',
      'code' => 'WELCOME500',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2009-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  16 => 
  array (
    'id' => '987',
    'name' => 'BetPhoenix Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'SoftSwiss',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$25',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All except Roulette,Craps & Dice games',
      'code' => 'WELCOME500',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2006-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  17 => 
  array (
    'id' => '921',
    'name' => 'BetOnline Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$25',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'All except Blackjack,Baccarat,Roulette,Craps,Video Poker,Live dealer and Mobile Casino games',
      'code' => 'CASINO1',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2003-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  18 => 
  array (
    'id' => '658',
    'name' => 'Sports Betting Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'Visionary iGaming',
      2 => 'Digital Gaming Solutions',
      3 => 'UC8 Slots',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$25',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'All except Blackjack,Baccarat,Roulette,Craps,Video Poker,Live dealer and Mobile Casino games',
      'code' => 'CASINO1',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2003-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  19 => 
  array (
    'id' => '441',
    'name' => 'Mobilautomaten Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'MicroGaming',
      3 => 'Playtech',
      4 => 'BetSoft',
      5 => 'Games OS',
      6 => 'WMS Gaming',
      7 => 'Yggdrasil Gaming',
      8 => 'Thunderkick',
      9 => 'Evolution Gaming',
      10 => 'Quickspin',
      11 => 'Play n GO',
      12 => 'Relax Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€10',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '€10',
      'min_deposit' => '',
      'wagering' => '45xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-06-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  20 => 
  array (
    'id' => '312',
    'name' => '1xBet Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'Novomatic',
      3 => 'Playtech',
      4 => 'BetSoft',
      5 => 'Aristocrat',
      6 => 'Evolution Gaming',
      7 => 'Ezugi',
      8 => 'Igrosoft',
      9 => 'Play n GO',
      10 => 'Endorphina',
      11 => 'GameArt',
      12 => 'Amatic Industries',
      13 => 'EGT',
      14 => 'Betgames TV',
      15 => 'Tom Horn',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£50.5',
      'wagering' => '5xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2007-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  21 => 
  array (
    'id' => '255',
    'name' => 'SuperCasino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Playtech',
      1 => 'IGT',
      2 => 'Quickspin',
      3 => 'Virtue Fusion',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£10',
      'wagering' => '25x(D+B)',
      'games_allowed' => 'All except Video Poker',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2005-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  22 => 
  array (
    'id' => '147',
    'name' => 'Coral Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Playtech',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '£/€50',
      'min_deposit' => '€/£10',
      'wagering' => '24xB',
      'games_allowed' => 'All (except Baccarat and Blackjack)',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  23 => 
  array (
    'id' => '1261',
    'name' => '1xSlots Casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'NextGen Gaming',
      2 => 'MicroGaming',
      3 => 'Rival',
      4 => 'Thunderkick',
      5 => 'Quickspin',
      6 => 'Playson',
      7 => 'Play n GO',
      8 => 'Endorphina',
      9 => 'Inteplay',
      10 => 'ELK Studios',
      11 => 'Habanero',
      12 => 'GameArt',
      13 => 'Amatic Industries',
      14 => 'Booming Games',
      15 => 'Pragmatic Play',
      16 => 'EGT',
      17 => 'Tom Horn Gaming',
      18 => 'Evoplay',
      19 => 'Casino Technology',
      20 => 'MrSlotty Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 30 FS',
      'min_deposit' => '10',
      'wagering' => '35xB',
      'games_allowed' => 'All except Roulette, Dice, Baccarat & Blackjack',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
  24 => 
  array (
    'id' => '1093',
    'name' => 'DabberBingo',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'NextGen Gaming',
      3 => 'IGT',
      4 => 'Amaya Gaming',
      5 => 'Thunderkick',
      6 => 'Evolution Gaming',
      7 => 'Eyecon',
      8 => 'GTS',
      9 => 'Bally',
      10 => 'Pariplay',
      11 => 'GGP',
      12 => 'Dragonfish',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '£90 + 10 FS',
      'min_deposit' => '€/£10',
      'wagering' => '0',
      'games_allowed' => 'All (FS - I Love Christmas)',
      'code' => 'GIFT',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-12-16',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
  ),
));

    }
}
        