<?php
class CasinosByBonusTypeController extends Controller {
    public function run() {
        $this->response->setAttribute("selected_entity", 'Free Spins');
$this->response->setAttribute("menu", array (
  '/countries-list/united-states' => 'United States Casinos',
  '/bonus-list/free-spins' => 'Free Spins Casinos',
  '/bonus-list/no-deposit-bonus' => 'No Deposit Casinos',
  '/casinos/best' => 'Best Casinos',
  '/casinos/safe' => 'Safe Casinos',
  '/casinos/new' => 'New Casinos',
  '/casinos/recommended' => 'Recommended Casinos',
  '/casinos/stay-away' => 'Stay Away Casinos',
));
$this->response->setAttribute("country", array (
  'id' => '34',
  'code' => 'US',
  'name' => 'United States',
));
$this->response->setAttribute("total_casinos", 200);
$this->response->setAttribute("casinos", array (
  0 => 
  array (
    'id' => '1357',
    'name' => 'Babe Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NextGen Gaming',
      2 => 'Cryptologic',
      3 => 'iSoftBet',
      4 => 'Wazdan',
      5 => 'Evolution Gaming',
      6 => 'OMI Gaming',
      7 => 'Ezugi',
      8 => 'Multislot',
      9 => 'Playson',
      10 => 'ELK Studios',
      11 => 'Genesis Gaming',
      12 => 'Habanero',
      13 => 'GameArt',
      14 => 'Pariplay',
      15 => 'Genii',
      16 => 'Booming Games',
      17 => 'Pragmatic Play',
      18 => 'BetConstruct',
      19 => 'EGT',
      20 => 'Zeus Services',
      21 => 'Spigo',
      22 => 'Iron Dog Studio',
      23 => 'Join Games',
      24 => 'Casino Technology',
      25 => 'MrSlotty Games',
      26 => 'Patagonia Entertainment',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200% + 100 FS',
      'min_deposit' => '€10',
      'wagering' => '40xB',
      'games_allowed' => 'Slots (FS - Fresh Fruits, Bake House, Santa Surprise, Under Water)',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  1 => 
  array (
    'id' => '1315',
    'name' => 'Breakout Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Evolution Gaming',
      2 => 'Quickfire',
      3 => '1X2 Gaming',
      4 => 'Pariplay',
      5 => 'Pragmatic Play',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€10',
      'wagering' => '70xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-10-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  2 => 
  array (
    'id' => '988',
    'name' => 'OG Palace Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '150%',
      'min_deposit' => '$/€/£25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All except Progressives,Gameset,Doubleup',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2010-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  3 => 
  array (
    'id' => '942',
    'name' => 'Lucky Admiral Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
      1 => 'MicroGaming',
      2 => 'Eyecon',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 20 FS',
      'min_deposit' => '£10',
      'wagering' => '65x(D+B)',
      'games_allowed' => 'Starbust Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-12-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  4 => 
  array (
    'id' => '917',
    'name' => 'Jojobet Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'iSoftBet',
      3 => 'Evolution Gaming',
      4 => 'Play n GO',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 15 FS',
      'min_deposit' => '$/€10',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'Netent Games',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  5 => 
  array (
    'id' => '882',
    'name' => 'Versailles Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'BetSoft',
      2 => 'Vivo Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300%',
      'min_deposit' => '$/€/£25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots (FS - Star Jewels Slot)',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  6 => 
  array (
    'id' => '851',
    'name' => 'Win2Fun Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'MicroGaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€20',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-11-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  7 => 
  array (
    'id' => '830',
    'name' => 'Diamond Reels Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '225%',
      'min_deposit' => '$25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'DRBFC225',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  8 => 
  array (
    'id' => '790',
    'name' => 'Sugar Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Oryx Gaming',
      2 => 'MicroGaming',
      3 => 'BetSoft',
      4 => 'Evolution Gaming',
      5 => 'Quickfire',
      6 => '1X2 Gaming',
      7 => 'Ezugi',
      8 => 'Intervision Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 55 FS',
      'min_deposit' => '$/€/£10',
      'wagering' => '50x(D+B)',
      'games_allowed' => 'Slots except Scrooge, Devil\'s Delight and Bloodsuckers',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-05-20',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  9 => 
  array (
    'id' => '684',
    'name' => 'NederBet Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'BetSoft',
      3 => 'Evolution Gaming',
      4 => 'TAIN',
      5 => 'Play n GO',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '125% + 20 FS',
      'min_deposit' => '$/€25',
      'wagering' => '25xB',
      'games_allowed' => 'Slots (FS - Guns N Roses)',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2010-11-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  10 => 
  array (
    'id' => '657',
    'name' => 'Parasino Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NextGen Gaming',
      2 => 'World Match',
      3 => 'MicroGaming',
      4 => 'BetSoft',
      5 => 'Evolution Gaming',
      6 => 'Portomaso Gaming',
      7 => '1X2 Gaming',
      8 => 'Ezugi',
      9 => 'Play n GO',
      10 => 'SoftSwiss',
      11 => 'ELK Studios',
      12 => 'GameArt',
      13 => 'Pariplay',
      14 => 'Genii',
      15 => 'XPG',
      16 => 'Pragmatic Play',
      17 => 'BetConstruct',
      18 => 'Zeus Services',
      19 => 'MrSlotty Games',
      20 => 'Betgames TV',
      21 => 'Tom Horn',
      22 => 'Playsoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 30 FS',
      'min_deposit' => '$/€/£10',
      'wagering' => '35xB',
      'games_allowed' => 'All except Video Poker,Roulette,Table Games & Live Casino',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-06-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  11 => 
  array (
    'id' => '591',
    'name' => 'LaRomere Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots (5 x Win)',
      'code' => '1STCASINOSLISTS',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  12 => 
  array (
    'id' => '587',
    'name' => 'Carat Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'Aberrant',
      3 => 'Play n GO',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€20',
      'wagering' => '40xB',
      'games_allowed' => 'Slots & Bingo',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  13 => 
  array (
    'id' => '389',
    'name' => 'Crazy Spins Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'BetSoft',
      2 => 'Play n GO',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£10',
      'wagering' => '50x(D+B)',
      'games_allowed' => 'All except jackpot & live casino',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2013-05-08',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  14 => 
  array (
    'id' => '330',
    'name' => 'Platinum Reels Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'CASINOSLISTS200',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2011-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  15 => 
  array (
    'id' => '319',
    'name' => 'Intrabahis Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Evolution Gaming',
      2 => 'XPG',
      3 => 'Betgames TV',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£10',
      'wagering' => '80xB',
      'games_allowed' => 'NetEnt Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-12-08',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  16 => 
  array (
    'id' => '250',
    'name' => 'Grand Wild Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'MicroGaming',
      3 => 'iSoftBet',
      4 => 'Games OS',
      5 => 'Playson',
      6 => 'Pragmatic Play',
      7 => 'BetConstruct',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '150%',
      'min_deposit' => '$/€/£25',
      'wagering' => '1x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2013-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  17 => 
  array (
    'id' => '74',
    'name' => 'Carat Bingo',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'Aberrant',
      3 => 'Play n GO',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€10',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'Slots,Bingo & Casino',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  18 => 
  array (
    'id' => '952',
    'name' => 'Naija Gaming Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'MicroGaming',
      3 => 'BetSoft',
      4 => 'Evolution Gaming',
      5 => 'TAIN',
      6 => 'Ezugi',
      7 => 'Play n GO',
      8 => 'Genii',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€5',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'bonusplease',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-10-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  19 => 
  array (
    'id' => '610',
    'name' => 'Mr Mega Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'Amaya Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£10',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All',
      'code' => 'CASINOSLISTS1ST',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2010-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
));

    }
}
        