<?php
class CasinosByLabelController extends Controller {
    public function run() {
        $this->response->setAttribute("country", array (
  'id' => '34',
  'code' => 'US',
  'name' => 'United States',
));
$this->response->setAttribute("menu_top", array (
  0 => 
  array (
    'title' => 'NO DEPOSIT CASINOS',
    'url' => '/bonus-list/no-deposit-bonus',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'NEW CASINOS',
    'url' => '/casinos/new',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'CASINOS',
    'url' => '/casinos',
    'is_active' => true,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'Best Casinos',
        'url' => '/casinos/best',
        'is_active' => true,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'Live Casinos',
        'url' => '/features/live-dealer',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'Mobile Casinos',
        'url' => '/casinos/mobile',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'eCOGRA Casinos',
        'url' => '/features/ecogra-casinos',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'Stay Away Casinos',
        'url' => '/casinos/stay-away',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      5 => 
      array (
        'title' => 'Popular Casinos',
        'url' => '/casinos/popular',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      6 => 
      array (
        'title' => 'All Casinos',
        'url' => '/casinos',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
  3 => 
  array (
    'title' => 'SOFTWARES',
    'url' => '/softwares',
    'is_active' => false,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'RTG Casinos',
        'url' => '/softwares/rtg',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'Rival Casinos',
        'url' => '/softwares/rival',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'NetEnt Casinos',
        'url' => '/softwares/netent',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'Playtech Casinos',
        'url' => '/softwares/playtech',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'MicroGaming Casinos',
        'url' => '/softwares/microgaming',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      5 => 
      array (
        'title' => 'BetSoft Casinos',
        'url' => '/softwares/betsoft',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      6 => 
      array (
        'title' => 'Saucify Casinos',
        'url' => '/softwares/saucify',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      7 => 
      array (
        'title' => 'Cryptologic Casinos',
        'url' => '/softwares/cryptologic',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      8 => 
      array (
        'title' => 'All Softwares',
        'url' => '/softwares',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
  4 => 
  array (
    'title' => 'COUNTRIES',
    'url' => '/countries',
    'is_active' => false,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'USA Casinos',
        'url' => '/countries-list/united-states',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'UK Casinos',
        'url' => '/countries-list/united-kingdom',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'Australia Casinos',
        'url' => '/countries-list/australia',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'Germany Casinos',
        'url' => '/countries-list/germany',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'New Zealand Casinos',
        'url' => '/countries-list/new-zealand',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      5 => 
      array (
        'title' => 'Netherlands Casinos',
        'url' => '/countries-list/netherlands',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      6 => 
      array (
        'title' => 'Sweden Casinos',
        'url' => '/countries-list/sweden',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      7 => 
      array (
        'title' => 'All Countries',
        'url' => '/countries ',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
  5 => 
  array (
    'title' => 'BANKING',
    'url' => '/banking',
    'is_active' => false,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'Neteller Casinos',
        'url' => '/banking/neteller',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'Skrill Moneybookers Casinos',
        'url' => '/banking/skrill-moneybookers',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'PayPal Casinos',
        'url' => '/banking/paypal',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'Bitcoin Wallets Casinos',
        'url' => '/banking/bitcoin-wallets',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'EcoPayz EcoCard Casinos',
        'url' => '/banking/ecopayz-ecocard',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      5 => 
      array (
        'title' => 'Paysafe Card',
        'url' => '/banking/paysafe-card',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      6 => 
      array (
        'title' => 'All Banking',
        'url' => '/banking',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
  6 => 
  array (
    'title' => 'GAMES',
    'url' => '/games',
    'is_active' => false,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'Video Slots',
        'url' => '/games/video-slots',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'Classic Slots',
        'url' => '/games/slots',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'Video Poker',
        'url' => '/games/video-poker',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'Scratch Cards',
        'url' => '/games/scratch-cards',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'Blackjack',
        'url' => '/games/blackjack',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      5 => 
      array (
        'title' => 'Roulette',
        'url' => '/games/roulette',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      6 => 
      array (
        'title' => 'Table Games',
        'url' => '/games/table-games',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      7 => 
      array (
        'title' => 'Bingo',
        'url' => '/games/bingo',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      8 => 
      array (
        'title' => 'Baccarat',
        'url' => '/games/baccarat',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      9 => 
      array (
        'title' => 'Craps',
        'url' => '/games/craps',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      10 => 
      array (
        'title' => 'Keno',
        'url' => '/games/keno',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      11 => 
      array (
        'title' => 'Other',
        'url' => '/games/other',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      12 => 
      array (
        'title' => 'All Games',
        'url' => '/games',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
));
$this->response->setAttribute("selected_entity", 'Best');
$this->response->setAttribute("is_mobile", false);
$this->response->setAttribute("menu_bottom", array (
  0 => 
  array (
    'title' => 'United States Casinos',
    'url' => '/countries-list/united-states',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'No Deposit Casinos',
    'url' => '/bonus-list/no-deposit-bonus',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'Best Casinos',
    'url' => '/casinos/best',
    'is_active' => true,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  3 => 
  array (
    'title' => 'Mobile Casinos',
    'url' => '/casinos/mobile',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  4 => 
  array (
    'title' => 'New Casinos',
    'url' => '/casinos/new',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  5 => 
  array (
    'title' => 'Stay Away Casinos',
    'url' => '/casinos/stay-away',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  6 => 
  array (
    'title' => 'All Casinos',
    'url' => '/casinos',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
));
$this->response->setAttribute("sort_criteria", 2);
$this->response->setAttribute("filter", 'label');
$this->response->setAttribute("total_casinos", '26');
$this->response->setAttribute("casinos", array (
  0 => 
  array (
    'id' => '985',
    'name' => 'Bitstarz Casino',
    'code' => 'bitstarz_casino',
    'rating' => 1,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'iSoftBet',
      2 => 'BetSoft',
      3 => 'Ezugi',
      4 => 'Endorphina',
      5 => 'SoftSwiss',
      6 => 'Amatic Industries',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% +180 FS',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All (FS - Starburst,Fruit Zen or Boomanji)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '20',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'Free Spins',
      'bonus_type_Abbreviation' => 'FS',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Terrible',
    'all_softwares' => 'iSoftBet, BetSoft, Ezugi, Endorphina, SoftSwiss, Amatic Industries',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Nov. 00, 0000',
    'status' => '0',
  ),
  1 => 
  array (
    'id' => '806',
    'name' => 'BoyleSports Casino',
    'code' => 'boylecasino',
    'rating' => 2,
    'softwares' => 
    array (
      0 => 'Playtech',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 50 FS',
      'min_deposit' => '$/€/£20',
      'wagering' => '20xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2011-02-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Terrible',
    'all_softwares' => NULL,
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Feb. 01, 2011',
    'status' => '0',
  ),
  2 => 
  array (
    'id' => '719',
    'name' => 'CasinoWilds',
    'code' => 'bling_city_casino',
    'rating' => 3,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NextGen Gaming',
      2 => 'Oryx Gaming',
      3 => 'World Match',
      4 => 'MicroGaming',
      5 => 'Cryptologic',
      6 => 'iSoftBet',
      7 => 'BetSoft',
      8 => 'Wazdan',
      9 => 'Evolution Gaming',
      10 => 'OMI Gaming',
      11 => '1X2 Gaming',
      12 => 'Ezugi',
      13 => 'iGaming2Go',
      14 => 'Multislot',
      15 => 'Edict eGaming',
      16 => 'Playson',
      17 => 'Play n GO',
      18 => 'Endorphina',
      19 => 'ELK Studios',
      20 => 'Habanero',
      21 => 'GameArt',
      22 => 'Pariplay',
      23 => 'Amatic Industries',
      24 => 'Genii',
      25 => 'Booming Games',
      26 => 'Pragmatic Play',
      27 => 'EGT',
      28 => 'Zeus Services',
      29 => 'Spigo',
      30 => 'Join Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200% + 60 FS',
      'min_deposit' => '€20',
      'wagering' => '38xB',
      'games_allowed' => 'All (FS - Starburst,Gonzo’s Quest and Aloha! Cluster Pays)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-02-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Poor',
    'all_softwares' => 'NextGen Gaming, Oryx Gaming, World Match, MicroGaming, Cryptologic, iSoftBet, BetSoft, Wazdan, Evolution Gaming, OMI Gaming, 1X2 Gaming, Ezugi, iGaming2Go, Multislot, Edict eGaming, Playson, Play n GO, Endorphina, ELK Studios, Habanero, GameArt, Pariplay, Amatic Industries, Genii, Booming Games, Pragmatic Play, EGT, Zeus Services, Spigo, Join Games',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Feb. 01, 2014',
    'status' => '0',
  ),
  3 => 
  array (
    'id' => '114',
    'name' => 'Play Casino Games',
    'code' => 'play_casino_games',
    'rating' => 4,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'NYX Interactive',
      2 => 'NextGen Gaming',
      3 => 'NetEnt',
      4 => 'Thunderkick',
      5 => 'Quickspin',
      6 => '1X2 Gaming',
      7 => '2By2 Gaming',
      8 => 'ELK Studios',
      9 => 'Genesis Gaming',
      10 => 'Big Time Gaming',
      11 => 'Rabcat',
      12 => 'Blueprint Gaming',
      13 => 'Lightning Box Games',
      14 => 'Scientific Games',
      15 => 'Gamevy',
      16 => 'Chance Interactive',
      17 => 'Core Gaming',
      18 => 'Iron Dog Studio',
      19 => 'Betdigital',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£10',
      'wagering' => '50xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Poor',
    'all_softwares' => 'NYX Interactive, NextGen Gaming, NetEnt, Thunderkick, Quickspin, 1X2 Gaming, 2By2 Gaming, ELK Studios, Genesis Gaming, Big Time Gaming, Rabcat, Blueprint Gaming, Lightning Box Games, Scientific Games, Gamevy, Chance Interactive, Core Gaming, Iron Dog Studio, Betdigital',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Nov. 00, 0000',
    'status' => '0',
  ),
  4 => 
  array (
    'id' => '170',
    'name' => 'Oshi Casino',
    'code' => 'oshi_casino',
    'rating' => 5,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'iSoftBet',
      2 => 'BetSoft',
      3 => 'Ezugi',
      4 => 'Endorphina',
      5 => 'SoftSwiss',
      6 => 'Habanero',
      7 => 'Belatra Games',
      8 => 'Amatic Industries',
      9 => 'Booming Games',
      10 => 'Pragmatic Play',
      11 => 'MrSlotty Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '0% - 150%',
      'min_deposit' => '€10',
      'wagering' => '40xB',
      'games_allowed' => 'Aztec Magic,Brave Viking,Domnitors,Fantasy Park,Platinum Lightning,Book of Pyramids,Cherry Fiesta & ',
      'code' => 'Unique generated codes',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-10-12',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Good',
    'all_softwares' => 'iSoftBet, BetSoft, Ezugi, Endorphina, SoftSwiss, Habanero, Belatra Games, Amatic Industries, Booming Games, Pragmatic Play, MrSlotty Games',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Oct. 12, 2015',
    'status' => '0',
  ),
  5 => 
  array (
    'id' => '1005',
    'name' => 'Vulkan Platinum Casino',
    'code' => 'vulkan_platinum_casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Novomatic',
      2 => 'Igrosoft',
      3 => 'Evoplay',
      4 => 'Playsoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '500 RUB',
      'wagering' => '20xB',
      'games_allowed' => 'All except Roulette',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Good',
    'all_softwares' => 'Novomatic, Igrosoft, Evoplay, Playsoft',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Nov. 00, 0000',
    'status' => '0',
  ),
  6 => 
  array (
    'id' => '1195',
    'name' => 'Smashing Casino',
    'code' => 'smashing_casino',
    'rating' => 7,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'GameScale',
      2 => 'Playson',
      3 => 'GameArt',
      4 => 'Booming Games',
      5 => 'Spinomenal',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300% + 50 FS',
      'min_deposit' => '€/£20',
      'wagering' => '33x(D+B)',
      'games_allowed' => 'All Betsoft Games',
      'code' => 'SMASH50',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '€5',
      'min_deposit' => '',
      'wagering' => '99xB',
      'games_allowed' => 'Betsoft Slots',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
      'bonus_type_Abbreviation' => 'NDB',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-06-05',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Very good',
    'all_softwares' => 'GameScale, Playson, GameArt, Booming Games, Spinomenal',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Jun. 05, 2017',
    'status' => '0',
  ),
  7 => 
  array (
    'id' => '1189',
    'name' => 'Hera Casino',
    'code' => 'hera_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'RTG',
      1 => 'Yggdrasil Gaming',
      2 => 'Pragmatic Play',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$30',
      'wagering' => '30xD',
      'games_allowed' => 'All',
      'code' => 'TBFCL1ST',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '$50',
      'min_deposit' => '',
      'wagering' => '50xB',
      'games_allowed' => 'All',
      'code' => 'TBFCLFREE50',
      'type' => 'No Deposit Bonus',
      'bonus_type_Abbreviation' => 'NDB',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-02-02',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Very good',
    'all_softwares' => 'Yggdrasil Gaming, Pragmatic Play',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Feb. 02, 2016',
    'status' => '0',
  ),
  8 => 
  array (
    'id' => '1079',
    'name' => 'SpaceLilly Casino',
    'code' => 'spacelilly_casino',
    'rating' => 9,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'iSoftBet',
      3 => 'BetSoft',
      4 => 'Evolution Gaming',
      5 => 'Quickspin',
      6 => 'Ezugi',
      7 => 'GameArt',
      8 => 'GGL live',
      9 => 'Pragmatic Play',
      10 => 'Kiron Interactive',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€20',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-11-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'MicroGaming, iSoftBet, BetSoft, Evolution Gaming, Quickspin, Ezugi, GameArt, GGL live, Pragmatic Play, Kiron Interactive',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Nov. 01, 2016',
    'status' => '0',
  ),
  9 => 
  array (
    'id' => '1022',
    'name' => 'Mummies Bingo',
    'code' => 'mummies_bingo',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '£10',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '£10',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
      'bonus_type_Abbreviation' => 'NDB',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => NULL,
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Nov. 00, 0000',
    'status' => '0',
  ),
  10 => 
  array (
    'id' => '1020',
    'name' => 'Wild Slots Casino',
    'code' => 'wild_slots_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'NextGen Gaming',
      3 => 'MicroGaming',
      4 => 'Cryptologic',
      5 => 'BetSoft',
      6 => 'IGT',
      7 => 'Aristocrat',
      8 => 'Leander Games',
      9 => 'Thunderkick',
      10 => 'Evolution Gaming',
      11 => 'Quickspin',
      12 => 'Play n GO',
      13 => 'ELK Studios',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 100 FS',
      'min_deposit' => '$/€/£20',
      'wagering' => '50xB',
      'games_allowed' => 'All (FS - Wild Wild West)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-10-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'No score',
    'all_softwares' => 'NYX Interactive, NextGen Gaming, MicroGaming, Cryptologic, BetSoft, IGT, Aristocrat, Leander Games, Thunderkick, Evolution Gaming, Quickspin, Play n GO, ELK Studios',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Oct. 01, 2016',
    'status' => '0',
  ),
  11 => 
  array (
    'id' => '872',
    'name' => 'Hunky Bingo',
    'code' => 'hunky_bingo',
    'rating' => 9,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'NextGen Gaming',
      3 => 'IGT',
      4 => 'Amaya Gaming',
      5 => 'Thunderkick',
      6 => 'Evolution Gaming',
      7 => 'Eyecon',
      8 => 'GTS',
      9 => 'Bally',
      10 => 'Pariplay',
      11 => 'GGP',
      12 => 'Dragonfish',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '450% + 10 FS',
      'min_deposit' => '$/€/£10',
      'wagering' => '0',
      'games_allowed' => 'Slots & Bingo (FS - Fluffy Favourites)',
      'code' => 'WELCOME',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'NYX Interactive, NextGen Gaming, IGT, Amaya Gaming, Thunderkick, Evolution Gaming, Eyecon, GTS, Bally, Pariplay, GGP, Dragonfish',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Mar. 01, 2015',
    'status' => '0',
  ),
  12 => 
  array (
    'id' => '661',
    'name' => 'Mr Slot Casino',
    'code' => 'mr_slot_casino',
    'rating' => 9,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NextGen Gaming',
      2 => 'MicroGaming',
      3 => 'Cryptologic',
      4 => 'Leander Games',
      5 => 'Thunderkick',
      6 => 'Quickspin',
      7 => '1X2 Gaming',
      8 => 'iGaming2Go',
      9 => 'Wagermill',
      10 => '2By2 Gaming',
      11 => 'ELK Studios',
      12 => 'Genesis Gaming',
      13 => 'Big Time Gaming',
      14 => 'Rabcat',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 50 FS',
      'min_deposit' => '$/€/£10',
      'wagering' => '50xB',
      'games_allowed' => 'All (FS - Starburst)',
      'code' => '50STAR',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '10',
      'min_deposit' => '',
      'wagering' => '50xB',
      'games_allowed' => 'Fairytale Legends: Hansel & Gretel',
      'code' => '10FAIRY',
      'type' => 'Free Spins',
      'bonus_type_Abbreviation' => 'FS',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'NextGen Gaming, MicroGaming, Cryptologic, Leander Games, Thunderkick, Quickspin, 1X2 Gaming, iGaming2Go, Wagermill, 2By2 Gaming, ELK Studios, Genesis Gaming, Big Time Gaming, Rabcat',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Jul. 01, 2016',
    'status' => '0',
  ),
  13 => 
  array (
    'id' => '1221',
    'name' => 'Miami Dice Casino',
    'code' => 'miami_dice_casino',
    'rating' => 9,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'MicroGaming',
      3 => 'Amaya Gaming',
      4 => 'Aristocrat',
      5 => 'Leander Games',
      6 => 'Thunderkick',
      7 => 'Evolution Gaming',
      8 => 'Quickspin',
      9 => '1X2 Gaming',
      10 => '2By2 Gaming',
      11 => 'ELK Studios',
      12 => 'Genesis Gaming',
      13 => 'Blueprint Gaming',
      14 => 'Merkur Gaming',
      15 => 'White Hat Gaming',
      16 => 'Multicommerce Game Studio',
      17 => 'Lightning Box Games',
      18 => 'Games Warehouse',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200% + 50 FS',
      'min_deposit' => '€/£20',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All except Table Games',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-12-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'NYX Interactive, MicroGaming, Amaya Gaming, Aristocrat, Leander Games, Thunderkick, Evolution Gaming, Quickspin, 1X2 Gaming, 2By2 Gaming, ELK Studios, Genesis Gaming, Blueprint Gaming, Merkur Gaming, White Hat Gaming, Multicommerce Game Studio, Lightning Box Games, Games Warehouse',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Dec. 01, 2016',
    'status' => '0',
  ),
  14 => 
  array (
    'id' => '1215',
    'name' => 'SlotoHit Casino',
    'code' => 'slotohit_casino',
    'rating' => 9,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'iSoftBet',
      2 => 'Games OS',
      3 => 'NetEnt',
      4 => 'MrSlotty Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '150%',
      'min_deposit' => '$/€/£10',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-05-26',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'iSoftBet, Games OS, NetEnt, MrSlotty Games',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'May. 26, 2017',
    'status' => '0',
  ),
  15 => 
  array (
    'id' => '1185',
    'name' => 'Swag Bingo',
    'code' => 'swag_bingo',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '£10',
      'wagering' => '10xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '£15',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
      'bonus_type_Abbreviation' => 'NDB',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-04-03',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'Cozy Games',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Apr. 03, 2017',
    'status' => '0',
  ),
  16 => 
  array (
    'id' => '1145',
    'name' => 'Castle Jackpot Casino',
    'code' => 'castle_jackpot_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'iSoftBet',
      2 => 'Playtech',
      3 => 'NetEnt',
      4 => 'Evolution Gaming',
      5 => 'OpenBet',
      6 => 'Eyecon',
      7 => 'Blueprint Gaming',
      8 => 'Realistic Games',
      9 => 'WMS',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '£10',
      'wagering' => '20x(D+B)',
      'games_allowed' => 'All except Roulette and Live Casino',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '£10',
      'min_deposit' => '',
      'wagering' => '99xB',
      'games_allowed' => 'All except Roulette and Live Casino',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
      'bonus_type_Abbreviation' => 'NDB',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'iSoftBet, Playtech, NetEnt, Evolution Gaming, OpenBet, Eyecon, Blueprint Gaming, Realistic Games, WMS',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Nov. 00, 0000',
    'status' => '0',
  ),
  17 => 
  array (
    'id' => '1000',
    'name' => 'Coin Palace Casino',
    'code' => 'coin_palace_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'BetSoft',
      2 => 'Ezugi',
      3 => 'Endorphina',
      4 => 'SoftSwiss',
      5 => 'Amatic Industries',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '150% + 200 FS',
      'min_deposit' => '$/€/£20',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'All (FS - Starburst,Attraction,Aliens,Fruit Zen,Boomanji,Sugar Pop)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'BetSoft, Ezugi, Endorphina, SoftSwiss, Amatic Industries',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Jan. 01, 2014',
    'status' => '0',
  ),
  18 => 
  array (
    'id' => '856',
    'name' => 'VIPSpel Casino',
    'code' => 'vipspel_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'iSoftBet',
      2 => 'Playtech',
      3 => 'Games OS',
      4 => 'NetEnt',
      5 => 'Playson',
      6 => 'Gaminator',
      7 => 'MrSlotty Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£10',
      'wagering' => '30xB',
      'games_allowed' => 'All except GamesOS',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '30',
      'min_deposit' => '',
      'wagering' => '70xB',
      'games_allowed' => 'Warlords',
      'code' => 'VS30TBFCLEXC',
      'type' => 'Free Spins',
      'bonus_type_Abbreviation' => 'FS',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2014-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'iSoftBet, Playtech, Games OS, NetEnt, Playson, Gaminator, MrSlotty Games',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Jan. 01, 2014',
    'status' => '0',
  ),
  19 => 
  array (
    'id' => '450',
    'name' => 'Funclub Casino',
    'code' => 'funclub_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$30',
      'wagering' => '20x(D+B) / 40x(D+B)',
      'games_allowed' => 'All except Jackpot Games',
      'code' => 'LISTS200',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '$50',
      'min_deposit' => '',
      'wagering' => '30x(D+B) / 60x(D+B)',
      'games_allowed' => 'All except Jackpot Games',
      'code' => 'FCFREE50',
      'type' => 'No Deposit Bonus',
      'bonus_type_Abbreviation' => 'NDB',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => NULL,
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Mar. 01, 2016',
    'status' => '0',
  ),
  20 => 
  array (
    'id' => '381',
    'name' => 'Royal Planet Casino',
    'code' => 'royal_planet_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '125%',
      'min_deposit' => '$/€/£25',
      'wagering' => '60x(D+B)',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£110',
      'min_deposit' => '',
      'wagering' => '2xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
      'bonus_type_Abbreviation' => 'NDB',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-07-05',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => NULL,
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Jul. 05, 2016',
    'status' => '0',
  ),
  21 => 
  array (
    'id' => '94',
    'name' => 'Stakes Casino',
    'code' => 'stakes_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'MicroGaming',
      2 => 'iSoftBet',
      3 => 'BetSoft',
      4 => 'Evolution Gaming',
      5 => 'RCT Gaming',
      6 => 'GameArt',
      7 => 'Intervision Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 50 FS',
      'min_deposit' => '$/€10',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'Slots,Jackpot 6000 & Mega Joker except Scrooge,Devil\'s Delight,Bloodsuckers & Dead or Alive (FS - St',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-05-21',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'MicroGaming, iSoftBet, BetSoft, Evolution Gaming, RCT Gaming, GameArt, Intervision Gaming',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'May. 21, 2016',
    'status' => '0',
  ),
  22 => 
  array (
    'id' => '93',
    'name' => 'Tip Top Bingo',
    'code' => 'tip_top_bingo',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'WMS Gaming',
      2 => 'WagerWorks',
      3 => 'Eyecon',
      4 => 'GTS',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '400%',
      'min_deposit' => '$/€/£10',
      'wagering' => '3x(D+B)',
      'games_allowed' => 'Bingo',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'WMS Gaming, WagerWorks, Eyecon, GTS',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Jan. 01, 2015',
    'status' => '0',
  ),
  23 => 
  array (
    'id' => '1251',
    'name' => 'test aaa',
    'code' => 'dsadddd',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => '1X2 Gaming',
      2 => 'BetSoft',
      3 => 'NetEnt',
      4 => 'Evolution Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '1',
      'min_deposit' => '1',
      'wagering' => '1',
      'games_allowed' => '1',
      'code' => '1',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-10-17',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => '1X2 Gaming, BetSoft, NetEnt, Evolution Gaming',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Oct. 17, 2017',
    'status' => '0',
  ),
  24 => 
  array (
    'id' => '489',
    'name' => 'Cherry Casino',
    'code' => 'cherry_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'BetSoft',
      3 => 'Amaya Gaming',
      4 => 'Yggdrasil Gaming',
      5 => 'Thunderkick',
      6 => 'Quickspin',
      7 => 'Quickfire',
      8 => 'Play n GO',
      9 => 'ELK Studios',
      10 => 'Bally',
      11 => 'Merkur Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '80 FS',
      'min_deposit' => '€20',
      'wagering' => '40xB',
      'games_allowed' => 'Vikings go Wild',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '20',
      'min_deposit' => '',
      'wagering' => '50xB',
      'games_allowed' => 'Starburst,Pyramid,Piggy Riches & Dazzle me',
      'code' => 'No code required',
      'type' => 'Free Spins',
      'bonus_type_Abbreviation' => 'FS',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2000-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => 'NYX Interactive, BetSoft, Amaya Gaming, Yggdrasil Gaming, Thunderkick, Quickspin, Quickfire, Play n GO, ELK Studios, Bally, Merkur Gaming',
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Jan. 01, 2000',
    'status' => '0',
  ),
  25 => 
  array (
    'id' => '1039',
    'name' => 'Planet Kings Casino',
    'code' => 'planet_kings_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
      'bonus_type_Abbreviation' => NULL,
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£25',
      'min_deposit' => '',
      'wagering' => '50xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
      'bonus_type_Abbreviation' => 'NDB',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-11-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'tc_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'is_tc_link' => '0',
    'logo_big' => '/public/sync/casino_logo_light/124x82/no-logo-124x82.png',
    'logo_small' => '/public/sync/casino_logo_light/85x56/no-logo-85x56.png',
    'new' => false,
    'score_class' => 'Excellent',
    'all_softwares' => NULL,
    'deposit_minimum' => NULL,
    'welcome_package' => NULL,
    'casino_deposit_methods' => NULL,
    'casino_game_types' => NULL,
    'date_formatted' => 'Nov. 01, 2016',
    'status' => '0',
  ),
));
$this->response->setAttribute("page_type", 'label');
$this->response->setAttribute("bonus_free_type", array (
  0 => 'FS',
  1 => NULL,
  2 => NULL,
  3 => NULL,
  4 => NULL,
  5 => NULL,
  6 => 'NDB',
  7 => 'NDB',
  8 => NULL,
  9 => 'NDB',
  10 => NULL,
  11 => NULL,
  12 => 'FS',
  13 => NULL,
  14 => NULL,
  15 => 'NDB',
  16 => 'NDB',
  17 => NULL,
  18 => 'FS',
  19 => 'NDB',
  20 => 'NDB',
  21 => NULL,
  22 => NULL,
  23 => NULL,
  24 => 'FS',
  25 => 'NDB',
));
$this->response->setAttribute("page_info", array (
  'head_title' => 'Best Online Casino Sites! Based on Authentic and Real Users Rankings',
  'head_description' => 'Best Online Casino Sites for 2019 with Genuine Players\' Voting | CasinosLists.com has listed the top-rated online casinos ranked by real casino players',
  'body_title' => 'Best Online Casinos 2019 (Based on Real Players\' Votings)',
));
$this->response->setAttribute("version", '0.8.7.02');
$this->response->setAttribute("use_bundle", false);
$this->response->setAttribute("tms", array (
  'upper_text' => '<p><u><b>Visits</b></u></p>

<ol>
	<li>newest game:&nbsp;0</li>
	<li>best game:&nbsp;&nbsp;59</li>
	<li>newest casino:&nbsp;15</li>
	<li>best casino:&nbsp;35</li>
</ol>

<p>As a leading casinos directory, CasinosList.com is constantly trying to provide you with useful and up-to-date information and allow you to have fun at the top-rated online casinos and earn as much as possible. Each casino page has its own review and ratings made by real casino players. In the end, the only trustworthy information you&rsquo;ll get about a casino&rsquo;s features or promotions is though committed gamblers. So let us guide you through our amazing portal and make your choice from our&nbsp;26 best online casinos. If you register from United States, you have&nbsp;3 options to choose from, so why hold back? Currently, the top-rated online casinos listed on our portal is <a href="/visit/bitstarz-casino">Bitstarz Casino</a>, offering a&nbsp;100% +180 FS first deposit bonus. Additionally, you can filter your results by clicking our &ldquo;Free Bonus&rdquo; button and seize some amazing no deposit bonuses.</p>

<p>&nbsp;</p>

<p>Faced with so much diversity it is not always easy to distinguish the wheat from the chaff. Which are the online casinos that offer the best games, the most recent and innovative, which are the ones whose withdrawal methods are excellent and above all, which of them offer the best opportunities to win and whose bonuses are the most attractive. In fact, the world of online gaming is so vast and evolving at such a speed that every week new online casinos enter the market while old ones renew themselves. We at CasinosLists.com try to keep up with the pace and always be well informed about new opportunities for our visitors.</p>
',
));

    }
}
        