<?php
class CasinosByCountryController extends Controller {
    public function run() {
        $this->response->setAttribute("selected_entity", 'France');
$this->response->setAttribute("menu", array (
  '/countries-list/united-states' => 'United States Casinos',
  '/countries-list/france' => 'France Casinos',
  '/bonus-list/no-deposit-bonus' => 'No Deposit Casinos',
  '/casinos/best' => 'Best Casinos',
  '/casinos/safe' => 'Safe Casinos',
  '/casinos/new' => 'New Casinos',
  '/casinos/recommended' => 'Recommended Casinos',
  '/casinos/stay-away' => 'Stay Away Casinos',
));
$this->response->setAttribute("country", array (
  'id' => '34',
  'code' => 'US',
  'name' => 'United States',
));
$this->response->setAttribute("total_casinos", 323);
$this->response->setAttribute("casinos", array (
  0 => 
  array (
    'id' => '29',
    'name' => 'Tropica Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$/€/£25',
      'wagering' => '25x(D+B)',
      'games_allowed' => 'All except Keno,Roulette,Craps & Baccarat,Double Up,Red Dog,Sicbo,Progressive Games',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£50',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2009-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  1 => 
  array (
    'id' => '1193',
    'name' => 'Mars Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Amatic Industries',
      2 => 'SoftSwiss',
      3 => 'Ezugi',
      4 => 'NetEnt',
      5 => 'BetSoft',
      6 => 'iSoftBet',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 50 FS',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-02-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  2 => 
  array (
    'id' => '1189',
    'name' => 'Hera Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'RTG',
      1 => 'Pragmatic Play',
      2 => 'Yggdrasil Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$30',
      'wagering' => '30xD',
      'games_allowed' => 'All',
      'code' => 'TBFCL1ST',
    ),
    'bonus_free' => 
    array (
      'amount' => '$50',
      'min_deposit' => '',
      'wagering' => '50xB',
      'games_allowed' => 'All',
      'code' => 'TBFCLFREE50',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-02-02',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  3 => 
  array (
    'id' => '1184',
    'name' => 'Burnbet Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Novomatic',
      2 => 'Unicum',
      3 => 'Mega Jack',
      4 => 'EGT',
      5 => 'Igrosoft',
      6 => 'Aristocrat',
      7 => 'RTG',
      8 => 'BetSoft',
      9 => 'Playtech',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€/£20',
      'wagering' => '35xB',
      'games_allowed' => 'All except Realtime Gaming,Playtech,Betsoft,Netent slots',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-01-15',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  4 => 
  array (
    'id' => '1016',
    'name' => 'Ramses Gold Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Amaya Gaming',
      2 => 'Leander Games',
      3 => 'Nektan',
      4 => 'BetSoft',
      5 => 'NextGen Gaming',
      6 => 'NYX Interactive',
      7 => 'Thunderkick',
      8 => 'ELK Studios',
      9 => '1X2 Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300%',
      'min_deposit' => '$/€/£20',
      'wagering' => '33x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  5 => 
  array (
    'id' => '988',
    'name' => 'OG Palace Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '150%',
      'min_deposit' => '$/€/£25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All except Progressives,Gameset,Doubleup',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2010-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  6 => 
  array (
    'id' => '962',
    'name' => 'Gibson Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '400%',
      'min_deposit' => '$/€/£25',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'Roulette,Craps,All except Baccarat,DoubleUp,RedDog,Sicbo & Slot Progressive.',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£25',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2014-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  7 => 
  array (
    'id' => '958',
    'name' => 'Casino Grand Bay',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£25',
      'wagering' => '40xB',
      'games_allowed' => 'All except Roulette,Three Card Poker & Baccarat',
      'code' => '1CGB100P',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2001-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  8 => 
  array (
    'id' => '939',
    'name' => 'Bingo Date',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '£5',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'CCASH100',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-12-12',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  9 => 
  array (
    'id' => '920',
    'name' => 'Boss Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Intervision Gaming',
      2 => 'GameArt',
      3 => 'Oryx Gaming',
      4 => 'Evolution Gaming',
      5 => 'NetEnt',
      6 => 'BetSoft',
      7 => 'iSoftBet',
      8 => '1X2 Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€20',
      'wagering' => '45xB',
      'games_allowed' => 'All',
      'code' => 'WELCOME',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  10 => 
  array (
    'id' => '917',
    'name' => 'Jojobet Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Play n GO',
      2 => 'Evolution Gaming',
      3 => 'iSoftBet',
      4 => 'MicroGaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 15 FS',
      'min_deposit' => '$/€10',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'Netent Games',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  11 => 
  array (
    'id' => '882',
    'name' => 'Versailles Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'BetSoft',
      2 => 'Vivo Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300%',
      'min_deposit' => '$/€/£25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots (FS - Star Jewels Slot)',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  12 => 
  array (
    'id' => '851',
    'name' => 'Win2Fun Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'MicroGaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '€20',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-11-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  13 => 
  array (
    'id' => '830',
    'name' => 'Diamond Reels Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '225%',
      'min_deposit' => '$25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'DRBFC225',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  14 => 
  array (
    'id' => '790',
    'name' => 'Sugar Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Intervision Gaming',
      2 => 'Ezugi',
      3 => '1X2 Gaming',
      4 => 'Quickfire',
      5 => 'Evolution Gaming',
      6 => 'BetSoft',
      7 => 'MicroGaming',
      8 => 'Oryx Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 55 FS',
      'min_deposit' => '$/€/£10',
      'wagering' => '50x(D+B)',
      'games_allowed' => 'Slots except Scrooge, Devil\'s Delight and Bloodsuckers',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-05-20',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  15 => 
  array (
    'id' => '755',
    'name' => 'Vegas2Web Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'BetSoft',
      2 => 'Vivo Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '150% + 25 FS',
      'min_deposit' => '$/€25',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€20',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2010-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  16 => 
  array (
    'id' => '698',
    'name' => '7Bit Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Amatic Industries',
      2 => 'SoftSwiss',
      3 => 'Endorphina',
      4 => 'Ezugi',
      5 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 25 FS',
      'min_deposit' => '$/€20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-11-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  17 => 
  array (
    'id' => '684',
    'name' => 'NederBet Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'BetSoft',
      2 => 'Play n GO',
      3 => 'TAIN',
      4 => 'Evolution Gaming',
      5 => 'MicroGaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '125% + 20 FS',
      'min_deposit' => '$/€25',
      'wagering' => '25xB',
      'games_allowed' => 'Slots (FS - Guns N Roses)',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2010-11-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  18 => 
  array (
    'id' => '682',
    'name' => 'Casino Girl',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'NetEnt',
      2 => 'Playtech',
      3 => 'Novomatic',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '250%',
      'min_deposit' => '$/€20',
      'wagering' => '85xB',
      'games_allowed' => 'Betsoft Slots',
      'code' => '250SLOTS',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  19 => 
  array (
    'id' => '677',
    'name' => 'Vulkano Games Casino',
    'rating' => NULL,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Igrosoft',
      2 => 'Aristocrat',
      3 => 'Playtech',
      4 => 'Novomatic',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$10',
      'wagering' => '35xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2009-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
));

    }
}
        