<?php
class CountriesController extends Controller {
    public function run() {
        $this->response->setAttribute("country", array (
  'id' => '43',
  'code' => 'RO',
  'name' => 'Romania',
));
$this->response->setAttribute("menu_top", array (
  0 => 
  array (
    'title' => 'NO DEPOSIT CASINOS',
    'url' => '/bonus-list/no-deposit-bonus',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'NEW CASINOS',
    'url' => '/casinos/new',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'CASINOS',
    'url' => '/casinos',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Best Casinos' => '/casinos/best',
      'Live Casinos' => '/features/live-dealer',
      'Mobile Casinos' => '/casinos/mobile',
      'eCOGRA Casinos' => '/features/ecogra-casinos',
      'Stay Away Casinos' => '/casinos/stay-away',
      'Popular Casinos' => '/casinos/popular',
      'All Casinos' => '/casinos',
    ),
    'have_submenu' => true,
  ),
  3 => 
  array (
    'title' => 'SOFTWARES',
    'url' => '/softwares',
    'is_active' => false,
    'submenuItems' => 
    array (
      'RTG Casinos' => '/softwares/rtg',
      'Rival Casinos' => '/softwares/rival',
      'NetEnt Casinos' => '/softwares/netent',
      'Playtech Casinos' => '/softwares/playtech',
      'MicroGaming Casinos' => '/softwares/microgaming',
      'BetSoft Casinos' => '/softwares/betsoft',
      'Saucify Casinos' => '/softwares/saucify',
      'Cryptologic Casinos' => '/softwares/cryptologic',
      'All Softwares' => '/softwares',
    ),
    'have_submenu' => true,
  ),
  4 => 
  array (
    'title' => 'COUNTRIES',
    'url' => '/countries',
    'is_active' => true,
    'submenuItems' => 
    array (
      'Romania Casinos' => '/countries-list/romania',
      'USA Casinos' => '/countries-list/united-states',
      'UK Casinos' => '/countries-list/united-kingdom',
      'Australia Casinos' => '/countries-list/australia',
      'Germany Casinos' => '/countries-list/germany',
      'New Zealand Casinos' => '/countries-list/new-zealand',
      'Netherlands Casinos' => '/countries-list/netherlands',
      'Sweden Casinos' => '/countries-list/sweden',
      'All Countries' => '/countries ',
    ),
    'have_submenu' => true,
  ),
  5 => 
  array (
    'title' => 'BANKING',
    'url' => '/banking',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Neteller Casinos' => '/banking/neteller',
      'Skrill Moneybookers Casinos' => '/banking/skrill-moneybookers',
      'PayPal Casinos' => '/banking/paypal',
      'Bitcoin Wallets Casinos' => '/banking/bitcoin-wallets',
      'EcoPayz EcoCard Casinos' => '/banking/ecopayz',
      'Paysafe Card' => '/banking/paysafe-card',
      'All Banking' => '/banking',
    ),
    'have_submenu' => true,
  ),
  6 => 
  array (
    'title' => 'GAMES',
    'url' => '/games',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Video Slots' => '/games/video-slots',
      'Classic Slots' => '/games/slots',
      'Video Poker' => '/games/video-poker',
      'Scratch Cards' => '/games/scratch-cards',
      'Blackjack' => '/games/blackjack',
      'Roulette' => '/games/roulette',
      'Table Games' => '/games/table-games',
      'Bingo' => '/games/bingo',
      'Baccarat' => '/games/baccarat',
      'Craps' => '/games/craps',
      'Keno' => '/games/keno',
      'Other' => '/games/other',
      'All Games' => '/games',
    ),
    'have_submenu' => true,
  ),
));
$this->response->setAttribute("results", array (
  'Romania' => '484',
  'Sweden' => '963',
  'New Zealand' => '933',
  'Liechtenstein' => '926',
  'Iceland' => '922',
  'San Marino' => '921',
  'Norway' => '916',
  'Aland Islands' => '912',
  'Saint Kitts and Nevis' => '906',
  'Saint Eustatius and Saba Bonaire' => '905',
  'Saint Lucia' => '903',
  'Sint Maarten (Dutch part)' => '899',
  'Chile' => '897',
  'Finland' => '895',
  'Svalbard and Jan Mayen' => '895',
  'Jersey' => '893',
  'Guernsey' => '892',
  'Uruguay' => '892',
  'Andorra' => '891',
  'Malta' => '891',
  'Tokelau' => '888',
  'Barbados' => '887',
  'Bermuda' => '887',
  'Seychelles' => '887',
  'The Democratic Republic of the Congo' => '885',
  'Switzerland' => '885',
  'Tonga' => '885',
  'Federated States of Micronesia' => '884',
  'Luxembourg' => '884',
  'Montserrat' => '883',
  'Saint Vincent and the Grenadines' => '883',
  'Bahamas' => '882',
  'Madagascar' => '882',
  'Anguilla' => '882',
  'Isle of Man' => '881',
  'Monaco' => '881',
  'Turks and Caicos Islands' => '880',
  'Holy See (Vatican City State)' => '880',
  'South Georgia and the South Sandwich Islands' => '878',
  'Tuvalu' => '873',
  'British Virgin Islands' => '873',
  'Trinidad and Tobago' => '873',
  'Aruba' => '873',
  'Solomon Islands' => '872',
  'El Salvador' => '872',
  'Austria' => '871',
  'Saint Helena' => '871',
  'Fiji' => '871',
  'Pitcairn Islands' => '870',
  'Paraguay' => '869',
  'Colombia' => '869',
  'United Republic of Tanzania' => '869',
  'Christmas Island' => '869',
  'Falkland Islands (Malvinas)' => '868',
  'Guatemala' => '867',
  'Honduras' => '866',
  'Suriname' => '865',
  'Peru' => '865',
  'Dominican Republic' => '865',
  'Maldives' => '864',
  'Faroe Islands' => '864',
  'Cayman Islands' => '863',
  'Niue' => '862',
  'British Indian Ocean Territory' => '861',
  'Palau' => '861',
  'Jamaica' => '861',
  'Sao Tome and Principe' => '859',
  'Mauritius' => '858',
  'Marshall Islands' => '858',
  'Venezuela' => '858',
  'Lesotho' => '857',
  'Mali' => '857',
  'Norfolk Island' => '856',
  'Macedonia' => '854',
  'Vanuatu' => '854',
  'Timor-Leste' => '854',
  'Germany' => '854',
  'Togo' => '854',
  'Gambia' => '853',
  'Brunei Darussalam' => '852',
  'Botswana' => '852',
  'Mexico' => '851',
  'Swaziland' => '851',
  'Ireland' => '850',
  'Cameroon' => '850',
  'Senegal' => '849',
  'Mongolia' => '849',
  'Djibouti' => '848',
  'Curacao' => '848',
  'Gabon' => '848',
  'Grenada' => '848',
  'Brazil' => '847',
  'Kiribati' => '847',
  'Nepal' => '847',
  'South Sudan' => '846',
  'Cocos (Keeling) Islands' => '846',
  'Oman' => '845',
  'Egypt' => '845',
  'Mozambique' => '845',
  'Kazakhstan' => '845',
  'Greenland' => '845',
  'Zambia' => '844',
  'Bolivia' => '844',
  'Cape Verde' => '844',
  'Equatorial Guinea' => '844',
  'United Arab Emirates' => '843',
  'Saudi Arabia' => '841',
  'Burkina Faso' => '841',
  'Nicaragua' => '840',
  'Palestinian Territory' => '840',
  'Qatar' => '840',
  'Comoros' => '839',
  'Namibia' => '839',
  'Tunisia' => '839',
  'Dominica' => '838',
  'Central African Republic' => '837',
  'Argentina' => '836',
  'Georgia' => '836',
  'Benin' => '834',
  'Belize' => '833',
  'Lao People\'s Democratic Republic' => '833',
  'Ghana' => '832',
  'Malawi' => '831',
  'Sri Lanka' => '830',
  'Bahrain' => '828',
  'Vietnam' => '828',
  'Kenya' => '827',
  'Gibraltar' => '827',
  'Macau' => '824',
  'Panama' => '822',
  'Cook Islands' => '821',
  'Haiti' => '821',
  'Guinea-Bissau' => '820',
  'Mauritania' => '820',
  'Sierra Leone' => '820',
  'Bhutan' => '817',
  'Lebanon' => '816',
  'Burundi' => '816',
  'Republic of Moldova' => '815',
  'Morocco' => '814',
  'Chad' => '813',
  'Liberia' => '810',
  'Taiwan' => '810',
  'Papua New Guinea' => '810',
  'Ecuador' => '809',
  'Republic of Korea' => '807',
  'Rwanda' => '807',
  'Costa Rica' => '806',
  'Saint Barthelemy' => '805',
  'Cambodia' => '803',
  'Congo' => '802',
  'Turkmenistan' => '802',
  'Eritrea' => '800',
  'Guyana' => '800',
  'Kyrgyzstan' => '799',
  'Jordan' => '795',
  'Saint Martin' => '794',
  'Tajikistan' => '789',
  'Japan' => '786',
  'Democratic People\'s Republic of Korea' => '785',
  'Antigua and Barbuda' => '783',
  'Slovakia' => '782',
  'Cote D\'Ivoire' => '781',
  'Kuwait' => '779',
  'Guinea' => '775',
  'French Southern Territories' => '772',
  'Uzbekistan' => '771',
  'Saint Pierre and Miquelon' => '771',
  'Nauru' => '769',
  'New Caledonia' => '767',
  'Wallis and Futuna' => '760',
  'Ethiopia' => '760',
  'Mayotte' => '759',
  'Algeria' => '759',
  'Montenegro' => '758',
  'Canada' => '756',
  'Uganda' => '755',
  'Martinique' => '752',
  'Australia' => '748',
  'Greece' => '747',
  'Guadeloupe' => '746',
  'Reunion' => '744',
  'Islamic Republic of Iran' => '742',
  'Armenia' => '737',
  'Angola' => '735',
  'Bangladesh' => '733',
  'Azerbaijan' => '728',
  'India' => '727',
  'Croatia' => '727',
  'Slovenia' => '724',
  'Belarus' => '722',
  'Bosnia and Herzegovina' => '722',
  'Somalia' => '722',
  'Cuba' => '722',
  'Thailand' => '718',
  'Virgin Islands US' => '718',
  'Northern Mariana Islands' => '715',
  'Malaysia' => '714',
  'Portugal' => '712',
  'Lithuania' => '706',
  'Latvia' => '705',
  'Albania' => '704',
  'Serbia' => '703',
  'Puerto Rico' => '696',
  'Nigeria' => '696',
  'Poland' => '694',
  'Czech Republic' => '693',
  'Ukraine' => '688',
  'Yemen' => '686',
  'American Samoa' => '685',
  'United Kingdom' => '685',
  'China' => '684',
  'French Polynesia' => '684',
  'Zimbabwe' => '683',
  'Niger' => '679',
  'Hong Kong' => '675',
  'Guam' => '669',
  'Samoa' => '668',
  'Cyprus' => '667',
  'Singapore' => '666',
  'French Guiana' => '664',
  'South Africa' => '661',
  'Libya' => '661',
  'Russian Federation' => '644',
  'Indonesia' => '644',
  'Myanmar' => '641',
  'Philippines' => '637',
  'Netherlands' => '628',
  'Sudan' => '624',
  'Pakistan' => '616',
  'Estonia' => '613',
  'Syrian Arab Republic' => '590',
  'Afghanistan' => '570',
  'Iraq' => '569',
  'Hungary' => '561',
  'United States Minor Outlying Islands' => '534',
  'Bulgaria' => '522',
  'Italy' => '513',
  'Belgium' => '507',
  'Denmark' => '479',
  'Turkey' => '434',
  'Spain' => '408',
  'France' => '327',
  'United States' => '225',
  'Israel' => '21',
));
$this->response->setAttribute("tms", array (
  'upper_text' => '<p>Countries -&nbsp; update</p>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using &#39;Content here, content here&#39;, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for &#39;lorem ipsum&#39; will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
',
));
$this->response->setAttribute("page_info", array (
  'head_title' => 'Online Casinos by Accepted Country - CasinosLists.com',
  'head_description' => ' Choose the best online casinos available for players in your country - UK Online Casinos, USA Online Casinos, Australian Online Casinos and more',
  'body_title' => 'Online Casinos by Accepted Country',
));
$this->response->setAttribute("version", '0.8.3.7');

    }
}
        