<?php
class GamesByTypeController extends Controller {
    public function run() {
        $this->response->setAttribute("selected_entity", 'Roulette');
$this->response->setAttribute("game_types", array (
  0 => 'Video Slots',
  1 => 'Video Poker',
  2 => 'Classic Slots',
  3 => 'Scratch Cards',
  4 => 'Blackjack',
  5 => 'Other',
  6 => 'Roulette',
  7 => 'Table Games',
  8 => 'Keno',
  9 => 'Bingo',
  10 => 'Baccarat',
  11 => 'Craps',
));
$this->response->setAttribute("total_games", 156);
$this->response->setAttribute("games", array (
  6875 => 
  array (
    'id' => '6875',
    'name' => 'NetEnt French Roulette',
    'type' => NULL,
    'software' => 'NetEnt',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6868 => 
  array (
    'id' => '6868',
    'name' => 'LuckyStreak Roulette',
    'type' => NULL,
    'software' => 'LuckyStreak',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6637 => 
  array (
    'id' => '6637',
    'name' => 'Saucify European Roulette',
    'type' => NULL,
    'software' => 'Saucify',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6635 => 
  array (
    'id' => '6635',
    'name' => 'Intouch Games European Roulette',
    'type' => NULL,
    'software' => 'Intouch Games',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6489 => 
  array (
    'id' => '6489',
    'name' => 'Digital Gaming Solutions American Roulette',
    'type' => NULL,
    'software' => 'Digital Gaming Solutions',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6341 => 
  array (
    'id' => '6341',
    'name' => 'Visionary iGaming American Roulette',
    'type' => NULL,
    'software' => 'Visionary iGaming',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6340 => 
  array (
    'id' => '6340',
    'name' => 'Visionary iGaming European Roulette',
    'type' => NULL,
    'software' => 'Visionary iGaming',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6322 => 
  array (
    'id' => '6322',
    'name' => 'Takisto European Roulette',
    'type' => NULL,
    'software' => 'Takisto',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6318 => 
  array (
    'id' => '6318',
    'name' => 'Takisto American Roulette',
    'type' => NULL,
    'software' => 'Takisto',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6295 => 
  array (
    'id' => '6295',
    'name' => '888 Software French Roulette',
    'type' => NULL,
    'software' => '888 Software',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6294 => 
  array (
    'id' => '6294',
    'name' => 'European Low Stakes Roulette',
    'type' => NULL,
    'software' => '888 Software',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6264 => 
  array (
    'id' => '6264',
    'name' => '888 Software 3D Roulette',
    'type' => NULL,
    'software' => '888 Software',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6230 => 
  array (
    'id' => '6230',
    'name' => 'Flamys Roulette',
    'type' => NULL,
    'software' => 'R Franco',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6130 => 
  array (
    'id' => '6130',
    'name' => 'Roulette Royal',
    'type' => NULL,
    'software' => 'NeoGames',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6129 => 
  array (
    'id' => '6129',
    'name' => 'NeoGames Roulette Pro',
    'type' => NULL,
    'software' => 'NeoGames',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6128 => 
  array (
    'id' => '6128',
    'name' => 'Roulette Lounge',
    'type' => NULL,
    'software' => 'NeoGames',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6060 => 
  array (
    'id' => '6060',
    'name' => 'NeoGames European Roulette',
    'type' => NULL,
    'software' => 'NeoGames',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  5984 => 
  array (
    'id' => '5984',
    'name' => 'European Roulette',
    'type' => NULL,
    'software' => 'Holland Power Gaming',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  5951 => 
  array (
    'id' => '5951',
    'name' => 'Arrows Edge European Roulette',
    'type' => NULL,
    'software' => 'Arrows Edge',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  5946 => 
  array (
    'id' => '5946',
    'name' => 'Arrows Edge American Roulette',
    'type' => NULL,
    'software' => 'Arrows Edge',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  5854 => 
  array (
    'id' => '5854',
    'name' => 'Euro Games Technology European Roulette',
    'type' => NULL,
    'software' => 'Euro Games Technology',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  5655 => 
  array (
    'id' => '5655',
    'name' => 'Roulette with Track',
    'type' => NULL,
    'software' => 'Playson',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  5602 => 
  array (
    'id' => '5602',
    'name' => 'Mini Roulette V2',
    'type' => NULL,
    'software' => 'OpenBet',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  5593 => 
  array (
    'id' => '5593',
    'name' => 'Roulette Single Euro Lo Roller',
    'type' => NULL,
    'software' => 'OpenBet',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
));

    }
}
        