<?php
class GamesByTypeController extends Lucinda\MVC\STDOUT\Controller {
    public function run() {
        $this->response->attributes("country", array (
  'id' => '34',
  'code' => 'US',
  'name' => 'United States',
  'languages' => 
  array (
    0 => 'English',
  ),
));
$this->response->attributes("menu_top", array (
  0 => 
  array (
    'title' => 'NO DEPOSIT CASINOS',
    'url' => '/bonus-list/no-deposit-bonus',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'NEW CASINOS',
    'url' => '/casinos/new',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'LIVE',
    'url' => '/features/live-dealer',
    'is_active' => false,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'Live Roulette Casinos',
        'url' => '/live-dealer/roulette',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'Live Blackjack Casinos',
        'url' => '/live-dealer/blackjack',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'Live Baccarat Casinos',
        'url' => '/live-dealer/baccarat',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'Live Craps Casinos',
        'url' => '/live-dealer/craps',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'Live Dealer Casinos',
        'url' => '/features/live-dealer',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
  3 => 
  array (
    'title' => 'CASINOS',
    'url' => '/casinos',
    'is_active' => false,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'Best Casinos',
        'url' => '/casinos/best',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'Low Minimum Deposit Casinos',
        'url' => '/casinos/low-minimum-deposit',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'Mobile Casinos',
        'url' => '/casinos/mobile',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'Low Wagering Casinos',
        'url' => '/casinos/low-wagering',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'Fast Payout Casinos',
        'url' => ' /casinos/fast-payout',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      5 => 
      array (
        'title' => 'eCOGRA Casinos',
        'url' => '/features/ecogra-casinos',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      6 => 
      array (
        'title' => 'Blacklisted Casinos',
        'url' => '/casinos/stay-away',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      7 => 
      array (
        'title' => 'No Account Casinos',
        'url' => '/casinos/no-account-casinos',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      8 => 
      array (
        'title' => 'All Casinos',
        'url' => '/casinos',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
  4 => 
  array (
    'title' => 'SOFTWARES',
    'url' => '/softwares',
    'is_active' => false,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'RTG Casinos',
        'url' => '/softwares/rtg',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'Rival Casinos',
        'url' => '/softwares/rival',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'NetEnt Casinos',
        'url' => '/softwares/netent',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'Playtech Casinos',
        'url' => '/softwares/playtech',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'MicroGaming Casinos',
        'url' => '/softwares/microgaming',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      5 => 
      array (
        'title' => 'BetSoft Casinos',
        'url' => '/softwares/betsoft',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      6 => 
      array (
        'title' => 'Saucify Casinos',
        'url' => '/softwares/saucify',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      7 => 
      array (
        'title' => 'Cryptologic Casinos',
        'url' => '/softwares/cryptologic',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      8 => 
      array (
        'title' => 'All Softwares',
        'url' => '/softwares',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
  5 => 
  array (
    'title' => 'COUNTRIES',
    'url' => '/countries',
    'is_active' => false,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'USA Casinos',
        'url' => '/countries-list/united-states',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'UK Casinos',
        'url' => '/countries-list/united-kingdom',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'Australia Casinos',
        'url' => '/countries-list/australia',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'New Zealand Casinos',
        'url' => '/countries-list/new-zealand',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'Netherlands Casinos',
        'url' => '/countries-list/netherlands',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      5 => 
      array (
        'title' => 'Sweden Casinos',
        'url' => '/countries-list/sweden',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      6 => 
      array (
        'title' => 'All Countries',
        'url' => '/countries ',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
  6 => 
  array (
    'title' => 'BANKING',
    'url' => '/banking',
    'is_active' => false,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'Neteller Casinos',
        'url' => '/banking/neteller',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'Skrill Moneybookers Casinos',
        'url' => '/banking/skrill-moneybookers',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'PayPal Casinos',
        'url' => '/banking/paypal',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'Bitcoin Casinos',
        'url' => '/banking/bitcoin',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'EcoPayz EcoCard Casinos',
        'url' => '/banking/ecopayz-ecocard',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      5 => 
      array (
        'title' => 'Paysafe Card',
        'url' => '/banking/paysafecard',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      6 => 
      array (
        'title' => 'All Banking',
        'url' => '/banking',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
  7 => 
  array (
    'title' => 'GAMES',
    'url' => '/games',
    'is_active' => true,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'Video Slots',
        'url' => '/games/video-slots',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'Classic Slots',
        'url' => '/games/classic-slots',
        'is_active' => true,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'Video Poker',
        'url' => '/games/video-poker',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      3 => 
      array (
        'title' => 'Scratch Cards',
        'url' => '/games/scratch-cards',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      4 => 
      array (
        'title' => 'Blackjack',
        'url' => '/games/blackjack',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      5 => 
      array (
        'title' => 'Roulette',
        'url' => '/games/roulette',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      6 => 
      array (
        'title' => 'Table Games',
        'url' => '/games/table-games',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      7 => 
      array (
        'title' => 'Bingo',
        'url' => '/games/bingo',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      8 => 
      array (
        'title' => 'Baccarat',
        'url' => '/games/baccarat',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      9 => 
      array (
        'title' => 'Craps',
        'url' => '/games/craps',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      10 => 
      array (
        'title' => 'Keno',
        'url' => '/games/keno',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      11 => 
      array (
        'title' => 'Other',
        'url' => '/games/other',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      12 => 
      array (
        'title' => 'All Games',
        'url' => '/games',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
  8 => 
  array (
    'title' => 'BLOG',
    'url' => '/blog',
    'is_active' => false,
    'submenuItems' => 
    array (
      0 => 
      array (
        'title' => 'News',
        'url' => '/blog/news',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      1 => 
      array (
        'title' => 'Guides',
        'url' => '/blog/guides',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
      2 => 
      array (
        'title' => 'All Blog Articles',
        'url' => '/blog',
        'is_active' => false,
        'submenuItems' => 
        array (
        ),
        'have_submenu' => false,
      ),
    ),
    'have_submenu' => true,
  ),
));
$this->response->attributes("selected_entity", 'Slots');
$this->response->attributes("menu_bottom", array (
  0 => 
  array (
    'title' => 'Video Slots',
    'url' => '/games/video-slots',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'Classic Slots',
    'url' => '/games/classic-slots',
    'is_active' => true,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'Video Poker',
    'url' => '/games/video-poker',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  3 => 
  array (
    'title' => 'Scratch Cards',
    'url' => '/games/scratch-cards',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  4 => 
  array (
    'title' => 'Other',
    'url' => '/games/other',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  5 => 
  array (
    'title' => 'Blackjack',
    'url' => '/games/blackjack',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  6 => 
  array (
    'title' => 'Roulette',
    'url' => '/games/roulette',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  7 => 
  array (
    'title' => 'Table Games',
    'url' => '/games/table-games',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  8 => 
  array (
    'title' => 'Bingo',
    'url' => '/games/bingo',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  9 => 
  array (
    'title' => 'Keno',
    'url' => '/games/keno',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  10 => 
  array (
    'title' => 'Baccarat',
    'url' => '/games/baccarat',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  11 => 
  array (
    'title' => 'Craps',
    'url' => '/games/craps',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
));
$this->response->attributes("software", array (
  0 => 'Saucify',
  1 => 'NetEnt',
  2 => 'RTG',
  3 => 'Playtech',
  4 => 'Rival',
  5 => 'BetSoft',
  6 => 'MicroGaming',
  7 => 'Slotland Entertainment',
  8 => 'NextGen Gaming',
  9 => 'GameScale',
  10 => 'Play n GO',
  11 => 'iSoftBet',
  12 => '1X2 Gaming',
  13 => 'Wazdan',
  14 => 'Booming Games',
  15 => 'Barcrest Games',
  16 => 'Novomatic',
  17 => 'Amatic Industries',
  18 => 'PlayPearls',
  19 => 'Zeusplay',
  20 => 'Thunderkick',
  21 => 'Pragmatic Play',
  22 => 'Realistic Games',
  23 => 'Core Gaming',
  24 => 'Eyecon',
  25 => 'Gamevy',
  26 => 'IGT',
  27 => 'Tom Horn Gaming',
  28 => 'WMS Gaming',
  29 => 'Leander Games',
  30 => 'World Match',
  31 => 'Xatronic Software',
  32 => 'WGS',
  33 => 'Gamomat',
  34 => 'Cayetano Gaming',
  35 => 'GAMING1',
  36 => 'Playson',
  37 => 'EGT',
  38 => 'NeoGames',
  39 => 'Intouch Games',
  40 => 'ELK Studios',
  41 => 'R.Franco',
  42 => 'Arrows Edge',
  43 => 'Quickspin',
  44 => 'Belatra Games',
  45 => 'Red Tiger Gaming',
  46 => 'Red Rake Gaming',
  47 => 'Betdigital',
  48 => 'Inspired',
  49 => 'Kalamba Games',
  50 => 'Push Gaming',
  51 => 'Gameplay Interactive',
  52 => 'Casino Technology',
  53 => 'SA Gaming',
  54 => 'Nolimit City',
  55 => 'Skywind Group',
  56 => 'Synot Games',
  57 => 'Spadegaming',
  58 => 'Felix Gaming',
  59 => 'Booongo',
  60 => 'Betixon',
  61 => 'Endorphina',
  62 => 'Inbet Games',
  63 => 'Relax Gaming',
  64 => 'Habanero',
  65 => 'BGaming',
  66 => 'Genesis Gaming',
  67 => 'The Art of Games',
  68 => 'NetGame',
  69 => 'Bomba Games',
  70 => 'August Gaming',
  71 => 'Amazing Gaming',
  72 => 'KA Gaming',
  73 => 'Blueprint Gaming',
  74 => 'BF Games',
  75 => 'Spinmatic',
  76 => 'Revolver Gaming',
  77 => 'FAZI',
  78 => 'OMI Gaming',
  79 => 'High 5 Games',
  80 => 'Ganapati',
  81 => 'Reel NRG',
  82 => 'StakeLogic',
  83 => 'Chance Interactive',
  84 => 'Nektan',
  85 => 'Swintt',
  86 => 'MGA',
  87 => 'Yggdrasil Gaming',
  88 => 'Pariplay',
  89 => 'AllWaySpin',
  90 => 'Evoplay',
  91 => 'Ruby Play',
  92 => 'Gamzix',
  93 => 'Nucleus Gaming',
  94 => 'Espresso Games',
  95 => 'Onlyplay',
  96 => 'Genii',
  97 => 'Mancala Gaming',
));
$this->response->attributes("total_games", 633);
$this->response->attributes("games", array (
  0 => 
  array (
    'id' => '13998',
    'manufacturer' => 'Mancala Gaming',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Coco Tiki',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Coco_Tiki_ss.jpg',
  ),
  1 => 
  array (
    'id' => '13988',
    'manufacturer' => 'Xatronic Software',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Multi Seven',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Multi_Seven_ss.jpg',
  ),
  2 => 
  array (
    'id' => '13982',
    'manufacturer' => 'Booongo',
    'type' => NULL,
    'quality' => NULL,
    'name' => '3 Coins',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '1',
    'logo' => '/public/sync/game_ss/300x220/3_Coins_ss.jpg',
  ),
  3 => 
  array (
    'id' => '13882',
    'manufacturer' => 'Pragmatic Play',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Dragon Kingdom Eyes of Fire',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '1',
    'logo' => '/public/sync/game_ss/300x220/Dragon_Kingdom_Eyes_of_Fire_ss.jpg',
  ),
  4 => 
  array (
    'id' => '13859',
    'manufacturer' => 'Yggdrasil Gaming',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Giza Infinity Reels',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Giza_Infinity_Reels_ss.jpg',
  ),
  5 => 
  array (
    'id' => '13835',
    'manufacturer' => 'Genii',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Bright Star',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '1',
    'logo' => '/public/sync/game_ss/300x220/Bright_Star_ss.jpg',
  ),
  6 => 
  array (
    'id' => '13819',
    'manufacturer' => 'StakeLogic',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Candyways Bonanza Megaways',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '1',
    'logo' => '/public/sync/game_ss/300x220/Candyways_Bonanza_Megaways_ss.jpg',
  ),
  7 => 
  array (
    'id' => '13813',
    'manufacturer' => 'MicroGaming',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Foxpot',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Foxpot_ss.jpg',
  ),
  8 => 
  array (
    'id' => '13804',
    'manufacturer' => 'Tom Horn Gaming',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Sweet Crush',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Sweet_Crush_ss.jpg',
  ),
  9 => 
  array (
    'id' => '13793',
    'manufacturer' => 'Genii',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Beijing Nights',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '4',
    'logo' => '/public/sync/game_ss/300x220/Beijing_Nights_ss.jpg',
  ),
  10 => 
  array (
    'id' => '13788',
    'manufacturer' => 'ELK Studios',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Knockout Diamonds',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Knockout_Diamonds_ss.jpg',
  ),
  11 => 
  array (
    'id' => '13777',
    'manufacturer' => 'StakeLogic',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Super Joker Megaways',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '1',
    'logo' => '/public/sync/game_ss/300x220/Super_Joker_Megaways_ss.jpg',
  ),
  12 => 
  array (
    'id' => '13771',
    'manufacturer' => 'Onlyplay',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Jungle Gold',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Jungle_Gold_ss.jpg',
  ),
  13 => 
  array (
    'id' => '13765',
    'manufacturer' => 'Realistic Games',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Bar X 7even',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '3',
    'logo' => '/public/sync/game_ss/300x220/Bar_X_7even_ss.jpg',
  ),
  14 => 
  array (
    'id' => '13761',
    'manufacturer' => 'Onlyplay',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Myths of Bastet',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Myths_of_Bastet_ss.jpg',
  ),
  15 => 
  array (
    'id' => '13729',
    'manufacturer' => 'Swintt',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Rainbow Gold',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Rainbow_Gold_ss.jpg',
  ),
  16 => 
  array (
    'id' => '13706',
    'manufacturer' => 'Nektan',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Mahjong Star',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '2',
    'logo' => '/public/sync/game_ss/300x220/Mahjong_Star_ss.jpg',
  ),
  17 => 
  array (
    'id' => '13704',
    'manufacturer' => 'Nektan',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Nektan Lucky Tiger',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '1',
    'logo' => '/public/sync/game_ss/300x220/Nektan_Lucky_Tiger_ss.jpg',
  ),
  18 => 
  array (
    'id' => '13619',
    'manufacturer' => 'Espresso Games',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Potion Trick',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '2',
    'logo' => '/public/sync/game_ss/300x220/Potion_Trick_ss.jpg',
  ),
  19 => 
  array (
    'id' => '13602',
    'manufacturer' => 'Nucleus Gaming',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'No Limit Bandit',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '3',
    'logo' => '/public/sync/game_ss/300x220/No_Limit_Bandit_ss.jpg',
  ),
  20 => 
  array (
    'id' => '13588',
    'manufacturer' => 'Spadegaming',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Three Lucky Stars',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Three_Lucky_Stars_ss.jpg',
  ),
  21 => 
  array (
    'id' => '13579',
    'manufacturer' => 'Gameplay Interactive',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Elf Surprise Jackpot',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '3',
    'logo' => '/public/sync/game_ss/300x220/Elf_Surprise_Jackpot_ss.jpg',
  ),
  22 => 
  array (
    'id' => '13571',
    'manufacturer' => 'Booming Games',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Jesters Joy',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '6',
    'logo' => '/public/sync/game_ss/300x220/Jesters_Joy_ss.jpg',
  ),
  23 => 
  array (
    'id' => '13540',
    'manufacturer' => 'Swintt',
    'type' => NULL,
    'quality' => NULL,
    'name' => 'Hawaiian Fantasy',
    'paylines' => NULL,
    'reels' => NULL,
    'rtp' => NULL,
    'min_cpl' => NULL,
    'max_cpl' => NULL,
    'max_wpl' => NULL,
    'min_cs' => NULL,
    'max_cs' => NULL,
    'priority' => NULL,
    'themes' => NULL,
    'volatility' => NULL,
    'date_launched' => '',
    'date_modified' => NULL,
    'is_open' => NULL,
    'is_flash' => NULL,
    'is_html5' => NULL,
    'is_progressive' => NULL,
    'is_non_progressive' => NULL,
    'is_3d_animation' => NULL,
    'is_3d_technology' => NULL,
    'is_autoplay' => NULL,
    'is_bonus_round' => NULL,
    'is_free_spins' => NULL,
    'is_live_dealer' => NULL,
    'is_multiplier' => NULL,
    'is_scatter' => NULL,
    'is_wild' => NULL,
    'is_macau' => NULL,
    'is_vegas' => NULL,
    'is_mobile' => NULL,
    'is_desktop' => NULL,
    'is_cascading_reels' => NULL,
    'is_win_both_ways' => NULL,
    'is_expanding_wilds' => NULL,
    'is_shifting_wilds' => NULL,
    'is_stacked_wilds' => NULL,
    'is_sticky_wilds' => NULL,
    'is_transferring_wilds' => NULL,
    'is_random_wilds' => NULL,
    'is_walking_wilds' => NULL,
    'is_split_symbol' => NULL,
    'is_reel_respins' => NULL,
    'is_rotating_reels' => NULL,
    'is_retriggering' => NULL,
    'is_slots_hold' => NULL,
    'is_gamble_feature' => NULL,
    'times_played' => '0',
    'logo' => '/public/sync/game_ss/300x220/Hawaiian_Fantasy_ss.jpg',
  ),
));
$this->response->attributes("filter", array (
  'game_type' => 'Slots',
));
$this->response->attributes("is_mobile", false);
$this->response->attributes("page_info", array (
  'head_title' => ' Play Slots Games for Free | Full List at CasinosLists.com',
  'head_description' => 'Play 633 Slots Games for free at CasinosLists.com | Catch up with all Slots games releases from major online casino software developers.',
  'body_title' => 'Free Online Slots Games',
));
$this->response->attributes("version", '1.0.0');
$this->response->attributes("use_bundle", false);
$this->response->attributes("widgets", array (
  'upper' => 
  array (
    0 => '<p>Slots are a simple concept, which can be summed up in spinning the reels by using either the machine&rsquo;s arm or, in&nbsp;virtual versions, a button, in order to achieve winning combinations and to win cash. Classic slots machines are a familiar sight in land-based casinos. With the apparition of online casinos, it was only a matter of time until the slots machines would be digitalized as well, preserving their features and old-fashioned mechanics and transporting them in the online gambling world. CasinosLists.com has put together a complete list of free online classic slots games for you to play and get a taste of the real casino experience. And don&rsquo;t forget that there&rsquo;s no download required!</p>

<p>Classic Slots vs. Video Slots</p>

<p>Classic slots usually have only three reels which means they also have fewer paylines, while Video Slots can have more than 200. This means that you&rsquo;ve got more chances of hitting a winning combination in a video slot, but at the same time a classic slot may provide bigger potential winnings.&nbsp;<br />
Video slots have more special features, such as bonus rounds and free spins, a field where their classic counterparts are rather lacking. However, with classic slots maintain a simple, polished model, so you&rsquo;ll always be able to feel that nostalgic, old-times thrill, reminiscent of land-based casinos.<br />
Both versions of slots can be progressive, therefore the more you play, the higher the chance of winning a bigger jackpot.&nbsp;</p>

<p><br />
CasinosLists.com has listed 633&nbsp;classic slots games from some of the most popular software providers in the field. Sort them by Most Played or Newest and use the Game Software filter to narrow down the results. These tools, used together, will help you find your next favorite classic slot. Try them out for free, and when you feel ready to play for real money, you&rsquo;ll have casino suggestions right on the game page.</p>

<p>Good luck!</p>
',
  ),
));

    }
}
        