<?php
class GameInfoController extends Controller {
    public function run() {
$this->response->setAttribute("country", array (
  'id' => '34',
  'code' => 'US',
  'name' => 'United States',
));
        $this->response->setAttribute("game_types", array (
  0 => 'Video Slots',
  1 => 'Video Poker',
  2 => 'Classic Slots',
  3 => 'Scratch Cards',
  4 => 'Blackjack',
  5 => 'Other',
  6 => 'Roulette',
  7 => 'Table Games',
  8 => 'Keno',
  9 => 'Bingo',
  10 => 'Baccarat',
  11 => 'Craps',
));
$this->response->setAttribute("game", array (
  'id' => '4276',
  'name' => 'Gamevy Roulette',
  'type' => 'Roulette',
  'software' => 'Gamevy',
  'release_date' => '2016-08-04',
  'technologies' => 
  array (
    0 => 'HTML5',
  ),
  'is_mobile' => true,
  'is_3d' => false,
  'overview' => 'Very few of the casinos we review attain a 5 star rating. High quality software, great games, and fast and convenient withdrawal processing are all a prerequisite. Most importantly, to be awarded this rating a casino must demonstrate the highest levels of customer service and player satisfaction over a number of years. We have no hesitation in recommending these casinos as safe and fun places to play online.',
  'times_played' => '0',
  'play' => 
  array (
    'width' => '500',
    'height' => '300',
    'screenshot' => '/public/img/sync/game_ss/500x300/Gamevy_Roulette_ss.jpg',
    'url' => 'https://games.gamevy.com/prod/roulette-eu/index.html?mode=fun&platform=gamevy',
    'status' => 'auto-play',
  ),
));
$this->response->setAttribute("recommended_casinos", array (
  0 => 
  array (
    'id' => '829',
    'name' => 'Touch Lucky Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'IGT',
      2 => 'NYX Interactive',
      3 => 'NextGen Gaming',
      4 => 'Nektan',
      5 => 'NetEnt',
      6 => 'Aristocrat',
      7 => 'ELK Studios',
      8 => 'Big Time Gaming',
      9 => 'Blueprint Gaming',
      10 => 'Realistic Games',
      11 => 'Lightning Box Games',
      12 => 'Scientific Games',
      13 => 'Gamevy',
      14 => 'Felt Gaming',
      15 => 'Iron Dog Studio',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 10 FS',
      'min_deposit' => '£10',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots (FS - Cleopatra)',
      'code' => 'No code required',
    ),
    'bonus_free' => 
    array (
      'amount' => '£5',
      'min_deposit' => '',
      'wagering' => '100xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2015-12-04',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  1 => 
  array (
    'id' => '724',
    'name' => 'Sapphire Rooms Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Realistic Games',
      2 => 'Lightning Box Games',
      3 => 'Scientific Games',
      4 => 'Gamevy',
      5 => 'Felt Gaming',
      6 => 'Iron Dog Studio',
      7 => 'Big Time Gaming',
      8 => 'Blueprint Gaming',
      9 => 'NYX Interactive',
      10 => 'NextGen Gaming',
      11 => 'Nektan',
      12 => 'NetEnt',
      13 => 'IGT',
      14 => 'Aristocrat',
      15 => 'ELK Studios',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200% ',
      'min_deposit' => '€/£10',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-11-10',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
  2 => 
  array (
    'id' => '629',
    'name' => 'Chomp Casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Gamevy',
      2 => 'NextGen Gaming',
      3 => 'Nektan',
      4 => 'NetEnt',
      5 => 'IGT',
      6 => 'Aristocrat',
      7 => 'ELK Studios',
      8 => 'Big Time Gaming',
      9 => 'Blueprint Gaming',
      10 => 'Realistic Games',
      11 => 'Lightning Box Games',
      12 => 'Scientific Games',
      13 => 'Felt Gaming',
      14 => 'Iron Dog Studio',
      15 => 'NYX Interactive',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 50 FS',
      'min_deposit' => '£10',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All ( FS - Starbust)',
      'code' => 'No code required',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-04-14',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'average_rating' => 0,
  ),
));
$this->response->setAttribute("recommended_games", array (
  6875 => 
  array (
    'id' => '6875',
    'name' => 'NetEnt French Roulette',
    'type' => NULL,
    'software' => 'NetEnt',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6868 => 
  array (
    'id' => '6868',
    'name' => 'LuckyStreak Roulette',
    'type' => NULL,
    'software' => 'LuckyStreak',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6637 => 
  array (
    'id' => '6637',
    'name' => 'Saucify European Roulette',
    'type' => NULL,
    'software' => 'Saucify',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6635 => 
  array (
    'id' => '6635',
    'name' => 'Intouch Games European Roulette',
    'type' => NULL,
    'software' => 'Intouch Games',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6489 => 
  array (
    'id' => '6489',
    'name' => 'Digital Gaming Solutions American Roulette',
    'type' => NULL,
    'software' => 'Digital Gaming Solutions',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6341 => 
  array (
    'id' => '6341',
    'name' => 'Visionary iGaming American Roulette',
    'type' => NULL,
    'software' => 'Visionary iGaming',
    'release_date' => NULL,
    'technologies' => NULL,
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
));

    }
}
        