<?php
class IndexController extends Controller {
    public function run() {
        $this->response->setAttribute("country", array (
  'id' => '34',
  'code' => 'US',
  'name' => 'United States',
));
$this->response->setAttribute("menu_top", array (
  0 => 
  array (
    'title' => 'NO DEPOSIT CASINOS',
    'url' => '/bonus-list/no-deposit-bonus',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'NEW CASINOS',
    'url' => '/casinos/new',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'CASINOS',
    'url' => '/casinos',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Best Casinos' => '/casinos/best',
      'Live Casinos' => '/features/live-dealer',
      'Mobile Casinos' => '/casinos/mobile',
      'eCOGRA Casinos' => '/features/ecogra-casinos',
      'Stay Away Casinos' => '/casinos/stay-away',
      'Popular Casinos' => '/casinos/popular',
      'All Casinos' => '/casinos',
    ),
    'have_submenu' => true,
  ),
  3 => 
  array (
    'title' => 'SOFTWARES',
    'url' => '/softwares',
    'is_active' => false,
    'submenuItems' => 
    array (
      'RTG Casinos' => '/softwares/rtg',
      'Rival Casinos' => '/softwares/rival',
      'NetEnt Casinos' => '/softwares/netent',
      'Playtech Casinos' => '/softwares/playtech',
      'MicroGaming Casinos' => '/softwares/microgaming',
      'BetSoft Casinos' => '/softwares/betsoft',
      'Saucify Casinos' => '/softwares/saucify',
      'Cryptologic Casinos' => '/softwares/cryptologic',
      'All Softwares' => '/softwares',
    ),
    'have_submenu' => true,
  ),
  4 => 
  array (
    'title' => 'COUNTRIES',
    'url' => '/countries',
    'is_active' => false,
    'submenuItems' => 
    array (
      'USA Casinos' => '/countries-list/united-states',
      'UK Casinos' => '/countries-list/united-kingdom',
      'Australia Casinos' => '/countries-list/australia',
      'Germany Casinos' => '/countries-list/germany',
      'New Zealand Casinos' => '/countries-list/new-zealand',
      'Netherlands Casinos' => '/countries-list/netherlands',
      'Sweden Casinos' => '/countries-list/sweden',
      'All Countries' => '/countries ',
    ),
    'have_submenu' => true,
  ),
  5 => 
  array (
    'title' => 'BANKING',
    'url' => '/banking',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Neteller Casinos' => '/banking/neteller',
      'Skrill Moneybookers Casinos' => '/banking/skrill-moneybookers',
      'PayPal Casinos' => '/banking/paypal',
      'Bitcoin Wallets Casinos' => '/banking/bitcoin-wallets',
      'EcoPayz EcoCard Casinos' => '/banking/ecopayz',
      'Paysafe Card' => '/banking/paysafe-card',
      'All Banking' => '/banking',
    ),
    'have_submenu' => true,
  ),
  6 => 
  array (
    'title' => 'GAMES',
    'url' => '/games',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Video Slots' => '/games/video-slots',
      'Classic Slots' => '/games/classic-slots',
      'Video Poker' => '/games/video-poker',
      'Scratch Cards' => '/games/scratch-cards',
      'Blackjack' => '/games/blackjack',
      'Roulette' => '/games/roulette',
      'Table Games' => '/games/table-games',
      'Bingo' => '/games/bingo',
      'Baccarat' => '/games/baccarat',
      'Craps' => '/games/craps',
      'Keno' => '/games/keno',
      'Other' => '/games/other',
      'All Games' => '/games',
    ),
    'have_submenu' => true,
  ),
));
$this->response->setAttribute("is_mobile", false);
$this->response->setAttribute("best_casinos", array (
));
$this->response->setAttribute("country_casinos", array (
  0 => 
  array (
    'id' => '1334',
    'name' => '24VIP Casino',
    'code' => 'casino_24vip',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'Vivo Gaming',
      2 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 240 FS',
      'min_deposit' => '$25',
      'wagering' => '15x(D+B)',
      'games_allowed' => 'Slots, Keno, Bingo, Specialty games (FS - Variety of Slots)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$15',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Slots, Keno, Bingo, Specialty Games and Scratch Cards',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Sep. 01, 2017',
    'status' => '0',
  ),
  1 => 
  array (
    'id' => '1371',
    'name' => 'Casino 5plusbet5',
    'code' => 'casino_5plusbet5',
    'rating' => 1,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Pariplay',
      2 => 'Patagonia Entertainment',
      3 => 'Genii',
      4 => 'Booming Games',
      5 => 'Pragmatic Play',
      6 => 'BetConstruct',
      7 => 'Zeus Services',
      8 => 'BetGames',
      9 => 'Iron Dog Studio',
      10 => 'Join Games',
      11 => 'Casino Technology',
      12 => 'MrSlotty Games',
      13 => 'GameArt',
      14 => 'Genesis Gaming',
      15 => 'ELK Studios',
      16 => 'Endorphina',
      17 => 'Playson',
      18 => 'Multislot',
      19 => '1X2 Gaming',
      20 => 'Cryptologic',
      21 => 'NextGen Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$5',
      'wagering' => '20xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2012-04-27',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Apr. 27, 2012',
    'status' => '0',
  ),
  2 => 
  array (
    'id' => '1369',
    'name' => 'UpTown Pokies Casino',
    'code' => 'uptown_pokies_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '250%',
      'min_deposit' => '20 AU$',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'Slots, Keno, Scratch Cards',
      'code' => 'POKIES1',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '10 AU$',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots, Keno, Scratch Cards',
      'code' => 'GDAY10',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-12-19',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Dec. 19, 2017',
    'status' => '0',
  ),
  3 => 
  array (
    'id' => '1351',
    'name' => 'EuroBets Casino',
    'code' => 'eurobets_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300%',
      'min_deposit' => '$25',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$10',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-08-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Aug. 01, 2017',
    'status' => '0',
  ),
  4 => 
  array (
    'id' => '1307',
    'name' => 'Spintastic Casino',
    'code' => 'spitastic_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Novomatic',
      2 => 'GreenTube',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 180 FS',
      'min_deposit' => '€20',
      'wagering' => '35xB',
      'games_allowed' => 'Slots (FS - Starburst)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '20',
      'min_deposit' => '',
      'wagering' => '35xB',
      'games_allowed' => 'Starburst',
      'code' => 'No code required',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jul. 01, 2017',
    'status' => '0',
  ),
));
$this->response->setAttribute("new_casinos", array (
  0 => 
  array (
    'id' => '1369',
    'name' => 'UpTown Pokies Casino',
    'code' => 'uptown_pokies_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '250%',
      'min_deposit' => '20 AU$',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'Slots, Keno, Scratch Cards',
      'code' => 'POKIES1',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '10 AU$',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots, Keno, Scratch Cards',
      'code' => 'GDAY10',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-12-19',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Dec. 19, 2017',
    'status' => '0',
  ),
  1 => 
  array (
    'id' => '1300',
    'name' => 'Cherry Jackpot Casino',
    'code' => 'cherry_jackpot_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$35',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots, Keno & Scratch Cards',
      'code' => 'CHERRY200',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-10-03',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Oct. 03, 2017',
    'status' => '0',
  ),
  2 => 
  array (
    'id' => '1296',
    'name' => 'Wild Tornado Casino',
    'code' => 'wild_tornado_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Belatra Games',
      2 => 'Ainsworth',
      3 => 'Amatic Industries',
      4 => 'NextGen Gaming',
      5 => 'ELK Studios',
      6 => 'SoftSwiss',
      7 => 'Endorphina',
      8 => 'Thunderkick',
      9 => 'Yggdrasil Gaming',
      10 => 'Amaya Gaming',
      11 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 250 FS',
      'min_deposit' => '50',
      'wagering' => '40xB',
      'games_allowed' => 'Slots, Keno, Bingo and Scratch Cards (FS - All slots except Jackpot games)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-10-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Oct. 01, 2017',
    'status' => '0',
  ),
  3 => 
  array (
    'id' => '1334',
    'name' => '24VIP Casino',
    'code' => 'casino_24vip',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'Vivo Gaming',
      2 => 'BetSoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 240 FS',
      'min_deposit' => '$25',
      'wagering' => '15x(D+B)',
      'games_allowed' => 'Slots, Keno, Bingo, Specialty games (FS - Variety of Slots)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$15',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Slots, Keno, Bingo, Specialty Games and Scratch Cards',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Sep. 01, 2017',
    'status' => '0',
  ),
  4 => 
  array (
    'id' => '1351',
    'name' => 'EuroBets Casino',
    'code' => 'eurobets_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300%',
      'min_deposit' => '$25',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$10',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-08-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Aug. 01, 2017',
    'status' => '0',
  ),
));
$this->response->setAttribute("no_deposit_casinos", array (
  0 => 
  array (
    'id' => '1369',
    'name' => 'UpTown Pokies Casino',
    'code' => 'uptown_pokies_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '250%',
      'min_deposit' => '20 AU$',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'Slots, Keno, Scratch Cards',
      'code' => 'POKIES1',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '10 AU$',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots, Keno, Scratch Cards',
      'code' => 'GDAY10',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-12-19',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Dec. 19, 2017',
    'status' => '0',
  ),
  1 => 
  array (
    'id' => '1334',
    'name' => '24VIP Casino',
    'code' => 'casino_24vip',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Rival',
      1 => 'BetSoft',
      2 => 'Vivo Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 240 FS',
      'min_deposit' => '$25',
      'wagering' => '15x(D+B)',
      'games_allowed' => 'Slots, Keno, Bingo, Specialty games (FS - Variety of Slots)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$15',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Slots, Keno, Bingo, Specialty Games and Scratch Cards',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Sep. 01, 2017',
    'status' => '0',
  ),
  2 => 
  array (
    'id' => '1351',
    'name' => 'EuroBets Casino',
    'code' => 'eurobets_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300%',
      'min_deposit' => '$25',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$10',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-08-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Aug. 01, 2017',
    'status' => '0',
  ),
  3 => 
  array (
    'id' => '1182',
    'name' => 'Casino Brango',
    'code' => 'casino_brango',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '150%',
      'min_deposit' => '$/€20',
      'wagering' => '15x(D+B)',
      'games_allowed' => 'Non Progressive Slots,Video Poker and Keno',
      'code' => 'BFCL150',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€40',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'Non-progressive slots',
      'code' => 'BFCL40',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-05-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'May. 01, 2017',
    'status' => '0',
  ),
  4 => 
  array (
    'id' => '1150',
    'name' => 'Fair Go Casino',
    'code' => 'fair_go_casino',
    'rating' => 0,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '20 AU$',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots,Keno & Scratch Cards',
      'code' => 'WELCOME',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '5 AU$',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots,Keno & Scratch Cards',
      'code' => 'CASINOSLISTSFREE',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Mar. 01, 2017',
    'status' => '0',
  ),
));
$this->response->setAttribute("new_games", array (
  6873 => 
  array (
    'id' => '6873',
    'name' => 'Divine Fortune',
    'type' => NULL,
    'software' => 'NetEnt',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6872 => 
  array (
    'id' => '6872',
    'name' => 'UFC',
    'type' => NULL,
    'software' => 'Endemol Games',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6871 => 
  array (
    'id' => '6871',
    'name' => 'Hulkamania',
    'type' => NULL,
    'software' => 'Endemol Games',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6870 => 
  array (
    'id' => '6870',
    'name' => 'Pixiu',
    'type' => NULL,
    'software' => 'Arrows Edge',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6869 => 
  array (
    'id' => '6869',
    'name' => 'Jester Bingo',
    'type' => NULL,
    'software' => 'Casino Technology',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  6868 => 
  array (
    'id' => '6868',
    'name' => 'LuckyStreak Roulette',
    'type' => NULL,
    'software' => 'LuckyStreak',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
));
$this->response->setAttribute("page_info", array (
  'head_title' => 'Online Casino Lists & Bonuses! CasinosLists.com - 2018',
  'head_description' => 'Detailed Online Casino Lists | Casino Bonuses Lists, Casino Softwares Lists, Casino Games Lists, Mobile Casinos Lists and More at CasinosLists.com – 2018',
  'body_title' => 'Welcome to casinoslists.com',
));
$this->response->setAttribute("version", '0.8.3.6');
$this->response->setAttribute("tms", array (
));

    }
}
        