<?php
class IndexController extends Controller {
    public function run() {
        $this->response->setAttribute("country", array (
  'id' => '43',
  'code' => 'RO',
  'name' => 'Romania',
));
$this->response->setAttribute("menu_top", array (
  0 => 
  array (
    'title' => 'NO DEPOSIT CASINOS',
    'url' => '/bonus-list/no-deposit-bonus',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'NEW CASINOS',
    'url' => '/casinos/new',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'CASINOS',
    'url' => '/casinos',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Best Casinos' => '/casinos/best',
      'Live Casinos' => '/features/live-dealer',
      'Mobile Casinos' => '/casinos/mobile',
      'eCOGRA Casinos' => '/features/ecogra-casinos',
      'Stay Away Casinos' => '/casinos/stay-away',
      'Popular Casinos' => '/casinos/popular',
      'All Casinos' => '/casinos',
    ),
    'have_submenu' => true,
  ),
  3 => 
  array (
    'title' => 'SOFTWARES',
    'url' => '/softwares',
    'is_active' => false,
    'submenuItems' => 
    array (
      'RTG Casinos' => '/softwares/rtg',
      'Rival Casinos' => '/softwares/rival',
      'NetEnt Casinos' => '/softwares/netent',
      'Playtech Casinos' => '/softwares/playtech',
      'MicroGaming Casinos' => '/softwares/microgaming',
      'BetSoft Casinos' => '/softwares/betsoft',
      'Saucify Casinos' => '/softwares/saucify',
      'Cryptologic Casinos' => '/softwares/cryptologic',
      'All Softwares' => '/softwares',
    ),
    'have_submenu' => true,
  ),
  4 => 
  array (
    'title' => 'COUNTRIES',
    'url' => '/countries',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Romania Casinos' => '/countries-list/romania',
      'USA Casinos' => '/countries-list/united-states',
      'UK Casinos' => '/countries-list/united-kingdom',
      'Australia Casinos' => '/countries-list/australia',
      'Germany Casinos' => '/countries-list/germany',
      'New Zealand Casinos' => '/countries-list/new-zealand',
      'Netherlands Casinos' => '/countries-list/netherlands',
      'Sweden Casinos' => '/countries-list/sweden',
      'All Countries' => '/countries ',
    ),
    'have_submenu' => true,
  ),
  5 => 
  array (
    'title' => 'BANKING',
    'url' => '/banking',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Neteller Casinos' => '/banking/neteller',
      'Skrill Moneybookers Casinos' => '/banking/skrill-moneybookers',
      'PayPal Casinos' => '/banking/paypal',
      'Bitcoin Wallets Casinos' => '/banking/bitcoin-wallets',
      'EcoPayz EcoCard Casinos' => '/banking/ecopayz',
      'Paysafe Card' => '/banking/paysafe-card',
      'All Banking' => '/banking',
    ),
    'have_submenu' => true,
  ),
  6 => 
  array (
    'title' => 'GAMES',
    'url' => '/games',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Video Slots' => '/games/video-slots',
      'Classic Slots' => '/games/slots',
      'Video Poker' => '/games/video-poker',
      'Scratch Cards' => '/games/scratch-cards',
      'Blackjack' => '/games/blackjack',
      'Roulette' => '/games/roulette',
      'Table Games' => '/games/table-games',
      'Bingo' => '/games/bingo',
      'Baccarat' => '/games/baccarat',
      'Craps' => '/games/craps',
      'Keno' => '/games/keno',
      'Other' => '/games/other',
      'All Games' => '/games',
    ),
    'have_submenu' => true,
  ),
));
$this->response->setAttribute("is_mobile", false);
$this->response->setAttribute("best_casinos", array (
  0 => 
  array (
    'id' => '170',
    'name' => 'Oshi Casino',
    'code' => 'oshi_casino',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'iSoftBet',
      2 => 'BetSoft',
      3 => 'Ezugi',
      4 => 'Endorphina',
      5 => 'SoftSwiss',
      6 => 'Habanero',
      7 => 'Belatra Games',
      8 => 'Amatic Industries',
      9 => 'Booming Games',
      10 => 'Pragmatic Play',
      11 => 'MrSlotty Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '0% - 150%',
      'min_deposit' => '€10',
      'wagering' => '40xB',
      'games_allowed' => 'Aztec Magic,Brave Viking,Domnitors,Fantasy Park,Platinum Lightning,Book of Pyramids,Cherry Fiesta & ',
      'code' => 'Unique generated codes',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2015-10-12',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Oct. 12, 2015',
    'status' => '0',
  ),
  1 => 
  array (
    'id' => '719',
    'name' => 'CasinoWilds',
    'code' => 'bling_city_casino',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Join Games',
      2 => 'Habanero',
      3 => 'GameArt',
      4 => 'Pariplay',
      5 => 'Amatic Industries',
      6 => 'Genii',
      7 => 'Booming Games',
      8 => 'Pragmatic Play',
      9 => 'EGT',
      10 => 'Zeus Services',
      11 => 'Spigo',
      12 => 'ELK Studios',
      13 => 'Wazdan',
      14 => 'Evolution Gaming',
      15 => 'OMI Gaming',
      16 => '1X2 Gaming',
      17 => 'Ezugi',
      18 => 'iGaming2Go',
      19 => 'Multislot',
      20 => 'Edict eGaming',
      21 => 'Playson',
      22 => 'Play n GO',
      23 => 'BetSoft',
      24 => 'iSoftBet',
      25 => 'NextGen Gaming',
      26 => 'Oryx Gaming',
      27 => 'World Match',
      28 => 'MicroGaming',
      29 => 'Cryptologic',
      30 => 'Endorphina',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200% + 60 FS',
      'min_deposit' => '€20',
      'wagering' => '38xB',
      'games_allowed' => 'All (FS - Starburst,Gonzo’s Quest and Aloha! Cluster Pays)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2014-02-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Feb. 01, 2014',
    'status' => '0',
  ),
  2 => 
  array (
    'id' => '806',
    'name' => 'BoyleSports Casino',
    'code' => 'boylecasino',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'Playtech',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 50 FS',
      'min_deposit' => '$/€/£20',
      'wagering' => '20xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2011-02-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Feb. 01, 2011',
    'status' => '0',
  ),
  3 => 
  array (
    'id' => '985',
    'name' => 'Bitstarz Casino',
    'code' => 'bitstarz_casino',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'SoftSwiss',
      2 => 'iSoftBet',
      3 => 'BetSoft',
      4 => 'Ezugi',
      5 => 'Amatic Industries',
      6 => 'Endorphina',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% +180 FS',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All (FS - Starburst,Fruit Zen or Boomanji)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '20',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Nov. 00, 0000',
    'status' => '0',
  ),
  4 => 
  array (
    'id' => '114',
    'name' => 'Play Casino Games',
    'code' => 'play_casino_games',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'NYX Interactive',
      2 => 'Scientific Games',
      3 => 'Gamevy',
      4 => 'Chance Interactive',
      5 => 'Core Gaming',
      6 => 'Iron Dog Studio',
      7 => 'Betdigital',
      8 => 'Lightning Box Games',
      9 => 'Blueprint Gaming',
      10 => 'NextGen Gaming',
      11 => 'NetEnt',
      12 => 'Thunderkick',
      13 => 'Quickspin',
      14 => '1X2 Gaming',
      15 => '2By2 Gaming',
      16 => 'ELK Studios',
      17 => 'Genesis Gaming',
      18 => 'Big Time Gaming',
      19 => 'Rabcat',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£10',
      'wagering' => '50xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Nov. 00, 0000',
    'status' => '0',
  ),
  5 => 
  array (
    'id' => '1005',
    'name' => 'Vulkan Platinum Casino',
    'code' => 'vulkan_platinum_casino',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Novomatic',
      2 => 'Igrosoft',
      3 => 'Evoplay',
      4 => 'Playsoft',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '500 RUB',
      'wagering' => '20xB',
      'games_allowed' => 'All except Roulette',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Nov. 00, 0000',
    'status' => '0',
  ),
  6 => 
  array (
    'id' => '1189',
    'name' => 'Hera Casino',
    'code' => 'hera_casino',
    'rating' => 9,
    'softwares' => 
    array (
      0 => 'RTG',
      1 => 'Yggdrasil Gaming',
      2 => 'Pragmatic Play',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200%',
      'min_deposit' => '$30',
      'wagering' => '30xD',
      'games_allowed' => 'All',
      'code' => 'TBFCL1ST',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$50',
      'min_deposit' => '',
      'wagering' => '50xB',
      'games_allowed' => 'All',
      'code' => 'TBFCLFREE50',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-02-02',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Feb. 02, 2016',
    'status' => '0',
  ),
  7 => 
  array (
    'id' => '1058',
    'name' => 'Jackpot Wheel Casino',
    'code' => 'jackpot_wheel_casino',
    'rating' => 9,
    'softwares' => 
    array (
      0 => 'Saucify',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£20',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'JACKPOT100',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£35',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'All',
      'code' => 'JACKPOT35',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2016-07-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jul. 01, 2016',
    'status' => '0',
  ),
  8 => 
  array (
    'id' => '1054',
    'name' => 'CasinoPop',
    'code' => 'casino_pop',
    'rating' => 9,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Play n GO',
      2 => 'ELK Studios',
      3 => 'Genesis Gaming',
      4 => 'Big Time Gaming',
      5 => 'Bally',
      6 => 'Barcrest Games',
      7 => 'Lightning Box Games',
      8 => 'Scientific Games',
      9 => 'iGaming2Go',
      10 => 'Quickspin',
      11 => 'NYX Interactive',
      12 => 'NextGen Gaming',
      13 => 'MicroGaming',
      14 => 'Cryptologic',
      15 => 'Aristocrat',
      16 => 'Yggdrasil Gaming',
      17 => 'Thunderkick',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '125% + 130 FS',
      'min_deposit' => '$/€/£15',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All (FS - Starburst,Lights & Second Strike)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2016-10-03',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Oct. 03, 2016',
    'status' => '0',
  ),
  9 => 
  array (
    'id' => '1022',
    'name' => 'Mummies Bingo',
    'code' => 'mummies_bingo',
    'rating' => 9,
    'softwares' => 
    array (
      0 => 'Cozy Games',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '£10',
      'wagering' => '10xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '£10',
      'min_deposit' => '',
      'wagering' => '20xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '0000-00-00',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '0',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Nov. 00, 0000',
    'status' => '0',
  ),
));
$this->response->setAttribute("country_casinos", array (
  0 => 
  array (
    'id' => '900',
    'name' => 'Thunderbolt Casino',
    'code' => 'thunderbolt_casino',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '150%',
      'min_deposit' => '25 ZAR',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots,Keno,Scratch Cards,Bingo & 7Stud Poker,European Slot Poker,Pai Gow Poker',
      'code' => '150MATCH',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '150 ZAR',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots,Keno,Scratch Cards,Bingo & 7Stud Poker,European Slot Poker,Pai Gow Poker',
      'code' => 'R150FREE',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2014-09-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Sep. 01, 2014',
    'status' => '0',
  ),
  1 => 
  array (
    'id' => '1223',
    'name' => 'Joker Casino',
    'code' => 'joker_casino',
    'rating' => 5,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NYX Interactive',
      2 => 'NextGen Gaming',
      3 => 'MicroGaming',
      4 => 'BetSoft',
      5 => 'MrSlotty Games',
      6 => 'Join Games',
      7 => 'Lightning Box Games',
      8 => 'GameArt',
      9 => 'Big Time Gaming',
      10 => 'ELK Studios',
      11 => 'Endorphina',
      12 => 'Play n GO',
      13 => 'Thunderkick',
      14 => 'Games OS',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200% + 40 FS',
      'min_deposit' => '€/£€50',
      'wagering' => '40xB',
      'games_allowed' => 'All except Jackpot and Live Casino games',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Apr. 01, 2017',
    'status' => '0',
  ),
  2 => 
  array (
    'id' => '1201',
    'name' => 'Casibon Casino',
    'code' => 'casibon_casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Betgames TV',
      2 => 'Pragmatic Play',
      3 => 'Ezugi',
      4 => 'Evolution Gaming',
      5 => 'Yggdrasil Gaming',
      6 => 'NetEnt',
      7 => 'NYX Interactive',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€10',
      'wagering' => '35xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '20',
      'min_deposit' => '',
      'wagering' => '35xB',
      'games_allowed' => 'Dead or Alive',
      'code' => 'FREECHIPS20',
      'type' => 'Free Spins',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-01-06',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 06, 2017',
    'status' => '0',
  ),
  3 => 
  array (
    'id' => '1207',
    'name' => 'Times Square Casino',
    'code' => 'times_square_casino',
    'rating' => 5,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'Lightning Box Games',
      2 => 'GGL live',
      3 => 'ELK Studios',
      4 => '1X2 Gaming',
      5 => 'Thunderkick',
      6 => 'GameScale',
      7 => 'Leander Games',
      8 => 'Amaya Gaming',
      9 => 'Nektan',
      10 => 'NextGen Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300%',
      'min_deposit' => '$/€/£20',
      'wagering' => '33x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€/£10',
      'min_deposit' => '',
      'wagering' => '33xB',
      'games_allowed' => 'All',
      'code' => 'CASINOSLISTS1ST',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2017',
    'status' => '0',
  ),
  4 => 
  array (
    'id' => '1167',
    'name' => 'Monster Casino',
    'code' => 'monster_casino',
    'rating' => 5,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Nektan',
      2 => 'Lightning Box Games',
      3 => 'Realistic Games',
      4 => 'Blueprint Gaming',
      5 => 'Big Time Gaming',
      6 => 'ELK Studios',
      7 => 'Aristocrat',
      8 => 'IGT',
      9 => 'NetEnt',
      10 => 'NextGen Gaming',
      11 => 'Scientific Games',
      12 => 'Gamevy',
      13 => 'Felt Gaming',
      14 => 'Iron Dog Studio',
      15 => 'NYX Interactive',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200% + 50 FS',
      'min_deposit' => '€/£10',
      'wagering' => '30xB',
      'games_allowed' => 'All (FS - Starburst)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '€/£5',
      'min_deposit' => '',
      'wagering' => '100xB',
      'games_allowed' => 'Slots',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2015-01-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jan. 01, 2015',
    'status' => '0',
  ),
));
$this->response->setAttribute("new_casinos", array (
  0 => 
  array (
    'id' => '1227',
    'name' => 'Pyramids Fortune Casino',
    'code' => 'pyramids_fortune_casino',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Lightning Box Games',
      2 => 'Realistic Games',
      3 => 'Aristocrat',
      4 => 'NetEnt',
      5 => 'Nektan',
      6 => 'NextGen Gaming',
      7 => 'NYX Interactive',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '200% + 50 FS',
      'min_deposit' => '€/£10',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All ( FS - Starburst)',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-06-30',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jun. 30, 2017',
    'status' => '0',
  ),
  1 => 
  array (
    'id' => '1195',
    'name' => 'Smashing Casino',
    'code' => 'smashing_casino',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'Spinomenal',
      2 => 'Booming Games',
      3 => 'GameArt',
      4 => 'Playson',
      5 => 'GameScale',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300% + 50 FS',
      'min_deposit' => '€/£20',
      'wagering' => '33x(D+B)',
      'games_allowed' => 'All Betsoft Games',
      'code' => 'SMASH50',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '€5',
      'min_deposit' => '',
      'wagering' => '99xB',
      'games_allowed' => 'Betsoft Slots',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-06-05',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jun. 05, 2017',
    'status' => '0',
  ),
  2 => 
  array (
    'id' => '1188',
    'name' => 'Schmitts Casino',
    'code' => 'schmitts_casino',
    'rating' => 5,
    'softwares' => 
    array (
      0 => 'MicroGaming',
      1 => 'Betdigital',
      2 => 'Iron Dog Studio',
      3 => 'Core Gaming',
      4 => 'NYX Interactive',
      5 => 'NextGen Gaming',
      6 => 'NetEnt',
      7 => 'Chance Interactive',
      8 => 'Gamevy',
      9 => 'Scientific Games',
      10 => 'Lightning Box Games',
      11 => 'Blueprint Gaming',
      12 => 'Rabcat',
      13 => 'Big Time Gaming',
      14 => 'Genesis Gaming',
      15 => 'ELK Studios',
      16 => '2By2 Gaming',
      17 => '1X2 Gaming',
      18 => 'Quickspin',
      19 => 'Thunderkick',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '$/€/£10',
      'wagering' => '50xB',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-04-03',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Apr. 03, 2017',
    'status' => '0',
  ),
  3 => 
  array (
    'id' => '1200',
    'name' => 'Kaiser Slots Casino',
    'code' => 'kaiser_slots_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'NextGen Gaming',
      2 => 'MicroGaming',
      3 => 'NeoGames',
      4 => 'Amaya Gaming',
      5 => 'NYX Interactive',
      6 => 'Thunderkick',
      7 => 'Scientific Games',
      8 => 'Lightning Box Games',
      9 => 'Realistic Games',
      10 => 'Blueprint Gaming',
      11 => 'ELK Studios',
      12 => 'Play n GO',
      13 => 'Evolution Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100% + 10 FS',
      'min_deposit' => '$/€/£10',
      'wagering' => '35x(D+B)',
      'games_allowed' => 'All',
      'code' => 'KAISER',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => NULL,
    'is_live_dealer' => NULL,
    'date_established' => '2017-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Apr. 01, 2017',
    'status' => '0',
  ),
  4 => 
  array (
    'id' => '1173',
    'name' => 'Casino Superlines',
    'code' => 'casino_superlines',
    'rating' => 5,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Air Dice',
      2 => 'Spinomenal',
      3 => 'Lightning Box Games',
      4 => 'Booming Games',
      5 => 'GameArt',
      6 => 'ELK Studios',
      7 => 'Playson',
      8 => '1X2 Gaming',
      9 => 'GameScale',
      10 => 'Leander Games',
      11 => 'Nektan',
      12 => 'BetSoft',
      13 => 'NextGen Gaming',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '400%',
      'min_deposit' => '€20',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '€10',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots & Scratch Cards',
      'code' => 'CASINOSLISTS10',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Apr. 01, 2017',
    'status' => '0',
  ),
));
$this->response->setAttribute("no_deposit_casinos", array (
  0 => 
  array (
    'id' => '1195',
    'name' => 'Smashing Casino',
    'code' => 'smashing_casino',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'BetSoft',
      1 => 'Booming Games',
      2 => 'GameScale',
      3 => 'Playson',
      4 => 'GameArt',
      5 => 'Spinomenal',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '300% + 50 FS',
      'min_deposit' => '€/£20',
      'wagering' => '33x(D+B)',
      'games_allowed' => 'All Betsoft Games',
      'code' => 'SMASH50',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '€5',
      'min_deposit' => '',
      'wagering' => '99xB',
      'games_allowed' => 'Betsoft Slots',
      'code' => 'No code required',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-06-05',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Jun. 05, 2017',
    'status' => '0',
  ),
  1 => 
  array (
    'id' => '1173',
    'name' => 'Casino Superlines',
    'code' => 'casino_superlines',
    'rating' => 5,
    'softwares' => 
    array (
      0 => 'NetEnt',
      1 => 'Lightning Box Games',
      2 => 'Spinomenal',
      3 => 'Air Dice',
      4 => 'Booming Games',
      5 => 'GameArt',
      6 => 'NextGen Gaming',
      7 => 'BetSoft',
      8 => 'Nektan',
      9 => 'Leander Games',
      10 => 'GameScale',
      11 => '1X2 Gaming',
      12 => 'Playson',
      13 => 'ELK Studios',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '400%',
      'min_deposit' => '€20',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'All',
      'code' => 'No code required',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '€10',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots & Scratch Cards',
      'code' => 'CASINOSLISTS10',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-04-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Apr. 01, 2017',
    'status' => '0',
  ),
  2 => 
  array (
    'id' => '1150',
    'name' => 'Fair Go Casino',
    'code' => 'fair_go_casino',
    'rating' => 8,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '100%',
      'min_deposit' => '20 AUD',
      'wagering' => '30x(D+B)',
      'games_allowed' => 'Slots,Keno & Scratch Cards',
      'code' => 'WELCOME',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '5 AUD',
      'min_deposit' => '',
      'wagering' => '60xB',
      'games_allowed' => 'Slots,Keno & Scratch Cards',
      'code' => 'CASINOSLISTSFREE',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Mar. 01, 2017',
    'status' => '0',
  ),
  3 => 
  array (
    'id' => '1155',
    'name' => 'BoVegas Casino',
    'code' => 'bovegas_casino',
    'rating' => 6,
    'softwares' => 
    array (
      0 => 'RTG',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '500%',
      'min_deposit' => '$25',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'Slots,Video Poker & Specialty games',
      'code' => 'CASINOSLISTS1ST500',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$30',
      'min_deposit' => '',
      'wagering' => '40xB',
      'games_allowed' => 'Slots,Video Poker & Specialty games',
      'code' => 'CASINOSLISTSNDB30',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-03-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Mar. 01, 2017',
    'status' => '0',
  ),
  4 => 
  array (
    'id' => '1139',
    'name' => 'Eclipse Casino',
    'code' => 'eclipse_casino',
    'rating' => 10,
    'softwares' => 
    array (
      0 => 'Rival',
    ),
    'languages' => NULL,
    'currencies' => NULL,
    'bonus_first_deposit' => 
    array (
      'amount' => '450%',
      'min_deposit' => '$/€25',
      'wagering' => '40x(D+B)',
      'games_allowed' => 'Slots & iSlots,Specialty Games',
      'code' => 'TBFCL1ST',
      'type' => 'First Deposit Bonus',
    ),
    'bonus_free' => 
    array (
      'amount' => '$/€25',
      'min_deposit' => '',
      'wagering' => '50xB',
      'games_allowed' => 'Slots & iSlots,Specialty Games',
      'code' => 'TBFCLNDB25',
      'type' => 'No Deposit Bonus',
    ),
    'is_live_dealer' => NULL,
    'date_established' => '2017-02-01',
    'emails' => NULL,
    'phones' => NULL,
    'is_live_chat' => NULL,
    'licenses' => NULL,
    'certifiers' => NULL,
    'affiliate_program' => NULL,
    'affiliate_link' => NULL,
    'withdrawal_minimum' => NULL,
    'withdrawal_limits' => NULL,
    'withdrawal_timeframes' => NULL,
    'deposit_methods' => NULL,
    'withdraw_methods' => NULL,
    'is_country_accepted' => '1',
    'is_language_accepted' => NULL,
    'is_currency_accepted' => NULL,
    'note' => NULL,
    'invision_casino_id' => NULL,
    'date_formatted' => 'Feb. 01, 2017',
    'status' => '0',
  ),
));
$this->response->setAttribute("new_games", array (
  7276 => 
  array (
    'id' => '7276',
    'name' => 'AmosTest2',
    'type' => NULL,
    'software' => '1X2 Gaming',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  7275 => 
  array (
    'id' => '7275',
    'name' => 'AmosTest',
    'type' => NULL,
    'software' => '021 test',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  7274 => 
  array (
    'id' => '7274',
    'name' => 'lucinda',
    'type' => NULL,
    'software' => '021 test',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  7273 => 
  array (
    'id' => '7273',
    'name' => 'Test3',
    'type' => NULL,
    'software' => 'RTG',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  7270 => 
  array (
    'id' => '7270',
    'name' => 'test2',
    'type' => NULL,
    'software' => 'RTG',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
  7269 => 
  array (
    'id' => '7269',
    'name' => 'Test',
    'type' => NULL,
    'software' => '1test233',
    'release_date' => NULL,
    'technologies' => 
    array (
    ),
    'is_mobile' => NULL,
    'is_3d' => NULL,
    'overview' => NULL,
    'times_played' => '0',
    'play' => NULL,
  ),
));
$this->response->setAttribute("page_info", array (
  'head_title' => 'Complete Online Casino Lists & Bonuses - CasinosLists.com',
  'head_description' => 'Updated Online Casino Lists for December 2018 | Find Online Casino Bonuses, Software Lists, Mobile Casinos and Authentic Reviews Made by Real Players',
  'body_title' => ' Welcome to CASINOSLISTS.COM',
));
$this->response->setAttribute("version", '0.8.3.7');
$this->response->setAttribute("tms", array (
));

    }
}
        