<?php
class SoftwaresController extends Controller {
    public function run() {
        $this->response->setAttribute("country", array (
  'id' => '43',
  'code' => 'RO',
  'name' => 'Romania',
));
$this->response->setAttribute("menu_top", array (
  0 => 
  array (
    'title' => 'NO DEPOSIT CASINOS',
    'url' => '/bonus-list/no-deposit-bonus',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  1 => 
  array (
    'title' => 'NEW CASINOS',
    'url' => '/casinos/new',
    'is_active' => false,
    'submenuItems' => 
    array (
    ),
    'have_submenu' => false,
  ),
  2 => 
  array (
    'title' => 'CASINOS',
    'url' => '/casinos',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Best Casinos' => '/casinos/best',
      'Live Casinos' => '/features/live-dealer',
      'Mobile Casinos' => '/casinos/mobile',
      'eCOGRA Casinos' => '/features/ecogra-casinos',
      'Stay Away Casinos' => '/casinos/stay-away',
      'Popular Casinos' => '/casinos/popular',
      'All Casinos' => '/casinos',
    ),
    'have_submenu' => true,
  ),
  3 => 
  array (
    'title' => 'SOFTWARES',
    'url' => '/softwares',
    'is_active' => true,
    'submenuItems' => 
    array (
      'RTG Casinos' => '/softwares/rtg',
      'Rival Casinos' => '/softwares/rival',
      'NetEnt Casinos' => '/softwares/netent',
      'Playtech Casinos' => '/softwares/playtech',
      'MicroGaming Casinos' => '/softwares/microgaming',
      'BetSoft Casinos' => '/softwares/betsoft',
      'Saucify Casinos' => '/softwares/saucify',
      'Cryptologic Casinos' => '/softwares/cryptologic',
      'All Softwares' => '/softwares',
    ),
    'have_submenu' => true,
  ),
  4 => 
  array (
    'title' => 'COUNTRIES',
    'url' => '/countries',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Romania Casinos' => '/countries-list/romania',
      'USA Casinos' => '/countries-list/united-states',
      'UK Casinos' => '/countries-list/united-kingdom',
      'Australia Casinos' => '/countries-list/australia',
      'Germany Casinos' => '/countries-list/germany',
      'New Zealand Casinos' => '/countries-list/new-zealand',
      'Netherlands Casinos' => '/countries-list/netherlands',
      'Sweden Casinos' => '/countries-list/sweden',
      'All Countries' => '/countries ',
    ),
    'have_submenu' => true,
  ),
  5 => 
  array (
    'title' => 'BANKING',
    'url' => '/banking',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Neteller Casinos' => '/banking/neteller',
      'Skrill Moneybookers Casinos' => '/banking/skrill-moneybookers',
      'PayPal Casinos' => '/banking/paypal',
      'Bitcoin Wallets Casinos' => '/banking/bitcoin-wallets',
      'EcoPayz EcoCard Casinos' => '/banking/ecopayz',
      'Paysafe Card' => '/banking/paysafe-card',
      'All Banking' => '/banking',
    ),
    'have_submenu' => true,
  ),
  6 => 
  array (
    'title' => 'GAMES',
    'url' => '/games',
    'is_active' => false,
    'submenuItems' => 
    array (
      'Video Slots' => '/games/video-slots',
      'Classic Slots' => '/games/slots',
      'Video Poker' => '/games/video-poker',
      'Scratch Cards' => '/games/scratch-cards',
      'Blackjack' => '/games/blackjack',
      'Roulette' => '/games/roulette',
      'Table Games' => '/games/table-games',
      'Bingo' => '/games/bingo',
      'Baccarat' => '/games/baccarat',
      'Craps' => '/games/craps',
      'Keno' => '/games/keno',
      'Other' => '/games/other',
      'All Games' => '/games',
    ),
    'have_submenu' => true,
  ),
));
$this->response->setAttribute("results", array (
  'RTG' => '82',
  'Rival' => '80',
  'NetEnt' => '555',
  'Playtech' => '114',
  'MicroGaming' => '482',
  'BetSoft' => '266',
  'Saucify' => '27',
  'Cryptologic' => '50',
  'IGT' => '134',
  'NYX Interactive' => '191',
  'NuWorks' => '4',
  'Evolution Gaming' => '221',
  'NextGen Gaming' => '191',
  'Play n GO' => '155',
  'Thunderkick' => '140',
  'Quickspin' => '135',
  'ELK Studios' => '132',
  'iSoftBet' => '111',
  '1X2 Gaming' => '108',
  'Amaya Gaming' => '102',
  'Blueprint Gaming' => '96',
  'Eyecon' => '96',
  'Aristocrat' => '81',
  'Pragmatic Play' => '80',
  'Ezugi' => '79',
  'Lightning Box Games' => '74',
  'Cozy Games' => '71',
  'Yggdrasil Gaming' => '71',
  'Scientific Games' => '69',
  'Playson' => '64',
  'Leander Games' => '64',
  'Pariplay' => '64',
  'Genesis Gaming' => '60',
  'Endorphina' => '59',
  'GameArt' => '59',
  'Big Time Gaming' => '54',
  'Realistic Games' => '52',
  'Amatic Industries' => '50',
  'Nektan' => '48',
  '2By2 Gaming' => '47',
  'Bally' => '44',
  'Rabcat' => '43',
  'Quickfire' => '41',
  'WMS' => '40',
  'Novomatic' => '40',
  'Dragonfish' => '39',
  'Games OS' => '37',
  '888 Software' => '34',
  'iGaming2Go' => '32',
  'GGP' => '32',
  'Booming Games' => '31',
  'Merkur Gaming' => '31',
  'SoftSwiss' => '30',
  'Williams Interactive' => '30',
  'EGT' => '29',
  '021 test' => '29',
  'Habanero' => '28',
  'GTS' => '27',
  'OpenBet' => '26',
  'Barcrest Games' => '25',
  'MrSlotty Games' => '25',
  'Genii' => '24',
  'Parlay' => '22',
  'Multicommerce Game Studio' => '22',
  'OMI Gaming' => '22',
  'Vivo Gaming' => '22',
  'Igrosoft' => '22',
  'WMS Gaming' => '20',
  'NeoGames' => '20',
  'Skillzz Gaming' => '19',
  'XPG' => '18',
  'Iron Dog Studio' => '17',
  'Spinomenal' => '17',
  'GameScale' => '17',
  'Gamevy' => '16',
  'BetConstruct' => '16',
  'Push Gaming' => '16',
  'World Match' => '15',
  'Aberrant' => '14',
  'White Hat Gaming' => '14',
  '1test233' => '13',
  'Felt Gaming' => '13',
  'Skill On Net' => '13',
  'GreenTube' => '13',
  'High 5 Games' => '13',
  'Oryx Gaming' => '13',
  'Betgames TV' => '12',
  'Ash Gaming' => '12',
  'Edict eGaming' => '12',
  'Wagermill' => '12',
  'Spigo' => '11',
  'Electracade' => '11',
  'Jadestone' => '11',
  'Endemol Games' => '11',
  'BetGames' => '11',
  'Chance Interactive' => '10',
  'Visionary iGaming' => '10',
  'Join Games' => '10',
  'Games Warehouse' => '10',
  'WagerWorks' => '9',
  'Intervision Gaming' => '9',
  'Fremantle' => '9',
  'Portomaso Gaming' => '9',
  'Virtue Fusion' => '9',
  'Zeus Services' => '8',
  'Octopus Gaming' => '7',
  'Mega Jack' => '7',
  'Multislot' => '7',
  'Casino Technology' => '7',
  'Relax Gaming' => '7',
  'AlteaGaming' => '7',
  'Unicum' => '6',
  '21GNET' => '6',
  'RCT Gaming' => '6',
  'Betdigital' => '6',
  'TAIN' => '6',
  'Gamesys' => '6',
  'ProgressPlay' => '6',
  'Ainsworth' => '5',
  'Tom Horn' => '5',
  'Wazdan' => '5',
  'Belatra Games' => '5',
  'WGS' => '5',
  'Gaminator' => '5',
  'GloboTech' => '5',
  'VistaGaming' => '5',
  'PopCap' => '5',
  'Win Interactive' => '4',
  'NetoPlay' => '4',
  'Pragmatic Play1' => '4',
  'Air Dice' => '4',
  'Mazooma Interactive' => '4',
  'Global Gaming Labs' => '4',
  'Patagonia Entertainment' => '4',
  'Actual Gaming' => '4',
  'GDI' => '3',
  'Intouch Games' => '3',
  'UC8 Slots' => '3',
  'PlayPearls' => '3',
  'GAMING1' => '3',
  'Core Gaming' => '3',
  'Inteplay' => '3',
  'GGL live' => '3',
  'Evoplay' => '3',
  'Ingenuity Gaming' => '3',
  'Playsoft' => '3',
  'Alps Games' => '3',
  'Cassava Enterprise' => '3',
  'SBTech' => '3',
  'Ace Gaming' => '3',
  'Tom Horn Gaming' => '2',
  'Allwilds' => '2',
  'Amuzi Gaming' => '2',
  'Instant Win Gaming' => '2',
  'Odobo Gaming' => '2',
  'JPM Interactive' => '2',
  'Wirex' => '2',
  'Side City Studios' => '2',
  'Opus Gaming' => '2',
  'Cayetano Gaming' => '2',
  'Kiron Interactive' => '2',
  'Bluberi Gaming' => '2',
  'LIONLINE' => '2',
  'Hybrino' => '2',
  'CasinoSkillGaming' => '2',
  'xGames' => '2',
  'Arrows Edge' => '2',
  'Takisto' => '2',
  'Saber Interactive' => '2',
  'Slotland Entertainment' => '2',
  'Omega Gaming' => '1',
  'MediaLive' => '1',
  'Incredible Technologies' => '1',
  'BetOnSoft' => '1',
  'R Franco' => '1',
  'Bookie' => '1',
  'Viaden' => '1',
  'Zukido' => '1',
  'Dr Vegas Games' => '1',
  'Megadice' => '1',
  'Spin3' => '1',
  'MGA' => '1',
  'AliQuantum Gaming' => '1',
  'Digital Gaming Solutions' => '1',
  'Geco Gaming' => '1',
  'Xatronic Software' => '1',
  'eGaming' => '1',
  'Spielo G2' => '1',
  'Ongame' => '1',
  'Soft Magic Dice' => '1',
  'Habanero Systemss' => '1',
  'GAN' => '1',
  'Habanero Systems' => '1',
  'Holland Power Gaming' => '1',
  'Infinity Gaming Solutions' => '1',
  'Capecod Gaming' => '1',
));
$this->response->setAttribute("tms", array (
  'upper_text' => '<p>test&nbsp;</p>
',
));
$this->response->setAttribute("page_info", array (
  'head_title' => 'Online Casinos by Software Developers | Full List at CasinosLists.com',
  'head_description' => 'All Online Casino Software Developers | We\'ve listed all gaming software providers, including top providers, such as NetEnt, Microgaming, RTG and others.',
  'body_title' => 'Online Casinos Software Providers',
));
$this->response->setAttribute("version", '0.8.3.7');

    }
}
        